import type { ResearchPost } from './fleet-content';

const commonFaq = [
  { question: 'Is this a payroll, tax, or legal opinion?', answer: 'No. It is bounded operational research. Confirm the employer-specific rule set and approval authority with the relevant Philippine authority and qualified advisers.' },
  { question: 'What can an outsourced support specialist do?', answer: 'A support specialist can collect source records, prepare comparisons, document exceptions, and route questions. An authorized payroll owner should approve sensitive changes, interpretations, and final results.' },
] as const;

const august23ResearchDrafts: readonly ResearchPost[] = [
  {
    slug: 'philippines-payroll-source-output-bridge-study',
    title: 'Philippines payroll source-to-output population bridge study',
    excerpt: 'Research question: can a payroll team prove that the prepared output contains the authorized population before it compares amounts?',
    published: '2026-08-23',
    stat: 'A population bridge compares source records, approved inclusions, approved exclusions, and the resulting payroll output.',
    image: '/research-heroes/philippines-payroll-source-output-bridge-study.png',
    takeaways: [
      'Question: does the payroll output contain the people and records the owner authorized for the stated period?',
      'Method: reconcile membership and change reasons before interpreting totals or variance percentages.',
      'Conclusion: a total can match while the population is wrong, so membership evidence is the first control.',
    ],
    sections: [
      { heading: 'Research question and evidence scope', body: 'A payroll comparison often starts with a total: gross pay, net pay, headcount, or a provider amount. That shortcut is unsafe when two totals describe different people or different effective periods. This study asks whether a source-to-output population bridge gives a reviewer enough evidence to understand what entered preparation, what was intentionally added or removed, and what reached the approved result. The scope is one employer, one pay period, and one defined output. It includes the source roster or change register, approved additions, approved exclusions, transformation rules, preparation timestamp, output population, and reviewer disposition. It does not attempt to decide who should legally be paid or how a tax obligation should be calculated.' },
      { heading: 'Method: reconcile membership before money', body: 'Build the bridge at record level using a stable employee or payroll identifier, period key, source status, output status, reason code, source link, and reviewer. Classify each source record as matched, approved exclusion, unexplained omission, or transformed into an output record. Then classify output-only records as approved addition, duplicate, or unexplained addition. Run the comparison before looking at amounts so an omitted person and an extra person cannot cancel each other out. Repeat across at least three comparable cycles, separating ordinary new hires and leavers from corrections and late approvals. A support specialist can assemble the bridge and flag incomplete evidence. The authorized payroll owner decides whether a population difference is valid.' },
      { heading: 'What the evidence can and cannot show', body: 'A complete bridge can show whether population membership was accounted for, whether an inclusion or exclusion has a source, and whether the reviewer recorded a decision. It cannot show that a source record was substantively correct, that a pay rate was lawful, or that an employer met a filing obligation. Those questions require the applicable employment, tax, contractual, and system context. Philippine privacy requirements also mean the bridge should contain only the fields needed to perform and review the comparison. Use a masked identifier where possible, restrict access, and retain the source link rather than copying an entire employee file into a working sheet.' },
      { heading: 'Limitations and evidence-led conclusion', body: 'The bridge depends on identifiers that remain stable across systems. Rehires, transfers, duplicate records, retroactive effective dates, and provider transformations can make a simple match ambiguous. A three-cycle sample may reveal a pattern without proving that every future cycle will behave the same way. The evidence-led conclusion is therefore narrow: reconcile membership before amount totals, keep every unexplained difference visible, and require an owner decision before release. This control helps an outsourced payroll support lane prepare an inspectable comparison while keeping population authority and final approval with the client’s designated owner. A useful bridge also distinguishes an approved business event from a repair made only to make two reports agree. For example, a late approved hire may be a legitimate addition, while an unexplained duplicate identifier is a defect even when the total payroll amount happens to remain unchanged. Record the reason category and the evidence link so a later reviewer can test the decision rather than trust a comment that says “resolved.” During the first cycle, the owner should review every unmatched item. In later cycles, a risk-based sample can be used only if the organization has demonstrated that the source systems, identifiers, and reason codes remain stable. If the population changes materially, restart the fuller review. The bridge should end with a named disposition for each difference, a timestamp, and a clear statement of whether the output is ready for the next control. That keeps preparation efficient without confusing reconciliation with authorization.' },
    ],
    sources: [
      { label: 'Philippine Statistics Authority, Labor Force Survey', url: 'https://psa.gov.ph/statistics/labor-force-survey' },
      { label: 'Bureau of Internal Revenue, official tax resources', url: 'https://www.bir.gov.ph/' },
      { label: 'National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/' },
    ],
    faq: commonFaq,
    related: ['philippines-payroll-reconciliation-false-positive-analysis', 'philippines-payroll-source-output-population-bridge', 'philippines-payroll-preparation-reconciliation'],
  },
  {
    slug: 'philippines-payroll-deadline-review-slack-study',
    title: 'Philippines payroll deadline review slack study',
    excerpt: 'Research question: how much usable review time remains after a payroll input is ready, handed off, and matched to the owner’s working calendar?',
    published: '2026-08-23',
    stat: 'Review slack is the usable time between an input becoming review-ready and the responsible owner’s decision cutoff.',
    image: '/research-heroes/philippines-payroll-deadline-review-slack-study.png',
    takeaways: [
      'Question: does nominal elapsed time overstate the window available for responsible payroll review?',
      'Method: record readiness, handoff, unavailable windows, questions, and decision time across comparable cycles.',
      'Conclusion: low slack should trigger escalation or scope decisions, never automatic approval.',
    ],
    sections: [
      { heading: 'Question, unit of analysis, and scope', body: 'A calendar may show two days between an input deadline and payroll submission while the owner has only a few usable hours after holidays, time-zone differences, meetings, and unanswered questions are removed. This study asks how much review slack is actually available for Philippines payroll operations that include a remote or outsourced preparation lane. The unit is one review item or coherent batch, not a whole pay period average. The scope records the period, canonical time zone, local equivalents, input readiness, handoff, owner availability, question-and-answer intervals, review start, decision, and final cutoff. It studies coordination conditions; it does not establish a statutory deadline or service-level promise.' },
      { heading: 'Method: turn the calendar into observable intervals', body: 'Use one canonical timestamp for each event and display the local equivalent to every participant. Mark the time an item became complete enough to review, the time it reached the authorized owner, and every interval when that owner was unavailable. Subtract response gaps and unresolved-question time from the nominal window. Report median slack, the tenth percentile, unresolved items at cutoff, and the share of items reaching the final day with no backup owner. Segment by input type and handoff stage because routine time records may have comfortable slack while bank, tax, or employment-status questions do not. A support specialist prepares timing evidence and low-slack alerts; only the owner chooses whether to wait, delegate within documented authority, or narrow scope.' },
      { heading: 'Interpretation: capacity is part of control design', body: 'Low slack is not proof that preparation was late. It may indicate an approval bottleneck, an unclear source rule, a holiday mismatch, or a handoff that crossed a working-day boundary. Conversely, generous average slack can conceal a small group of urgent, sensitive items. Compare slack with exception type, approval age, reviewer capacity, and decision quality. Do not reward a team for reducing slack by skipping evidence. The relevant operating question is whether the responsible reviewer had enough time to inspect the source, ask a question, and record a decision before the cutoff.' },
      { heading: 'Limitations and evidence-led conclusion', body: 'Slack calculations are sensitive to time-zone configuration, business-day conventions, incomplete availability records, and the organization’s chosen cutoff. A sample across three cycles can identify recurring pressure but cannot forecast every holiday or provider change. It also cannot determine tax treatment or employment rights. The evidence-led conclusion is to make usable review time visible, alert on low slack early, and preserve an owner decision when the window is short. An outsourced payroll support lane can help surface the timing risk, but it should never convert a deadline measure into an approval rule. The most useful review separates preventable delay from unavoidable constraint. A handoff sent late because a source was incomplete needs an intake correction; a handoff received on time but waiting for an unavailable approver needs coverage planning. A question that remains open because no one knows which record is authoritative needs a decision rule, not another reminder. Keep these causes separate in the measurement so the team does not respond to every low-slack item with more messages. The owner can define an escalation point, such as a low-slack alert with no answer, but the alert should route to a named person and include the evidence needed to decide. A backup reviewer should have documented scope rather than merely having technical access. After each cycle, inspect the items that reached the final day, compare their causes, and choose one improvement for the next period. This turns timing data into a control-learning loop while preserving the central boundary: only the authorized owner decides what may proceed.' },
    ],
    sources: [
      { label: 'Philippine Development Plan 2023–2028', url: 'https://pdp.depdev.gov.ph/' },
      { label: 'Department of Labor and Employment, official resources', url: 'https://www.dole.gov.ph/' },
      { label: 'International Labour Organization, Philippines', url: 'https://www.ilo.org/manila' },
    ],
    faq: commonFaq,
    related: ['philippines-payroll-deadline-slack-measurement', 'philippines-payroll-cross-border-time-window', 'philippines-payroll-approval-age-analysis'],
  },
  {
    slug: 'philippines-payroll-correction-lineage-review',
    title: 'Philippines payroll correction lineage review',
    excerpt: 'Research question: can a reviewer follow a payroll correction from its originating evidence to the confirmed downstream result without relying on memory?',
    published: '2026-08-23',
    stat: 'Correction lineage links the request, changed field, effective date, reviewer decision, resulting output, and confirmation.',
    image: '/research-heroes/philippines-payroll-correction-lineage-review.png',
    takeaways: [
      'Question: does the correction record explain what changed, why it changed, and how the result was confirmed?',
      'Method: sample correction chains by field, effective period, source, reviewer, and downstream confirmation.',
      'Conclusion: a corrected value without its original evidence is not a complete control record.',
    ],
    sections: [
      { heading: 'Research question and evidence boundary', body: 'Payroll corrections are often discussed as if the final value is the only important artifact. That loses the original problem, the authority for the change, and the evidence that the downstream result reflects the decision. This study asks whether a correction lineage record lets an independent reviewer reconstruct the chain without interviewing the preparer. The boundary is an employee or payroll field correction within a defined period: the originating request or source, original value where retention is permitted, corrected value, effective date, reason, preparer, authorized reviewer, resulting payroll record, and confirmation. It does not decide whether a particular correction is legally required or whether the underlying employment fact is true.' },
      { heading: 'Method: sample the chain, not just the ticket', body: 'Select corrections across pay, time, deductions, bank instructions, tax attributes, and employment status, then sample both routine and urgent items. For each item, test whether the source is authoritative for that field, whether the effective date matches the period, whether the preparer stayed within role boundaries, whether an authorized person approved the change, and whether the downstream result was checked. Record missing links as distinct findings rather than collapsing them into a generic incomplete label. A support specialist can index the chain, compare the old and new field descriptions, and route mismatches. The payroll owner interprets the evidence and approves the correction.' },
      { heading: 'Analysis: distinguish correction quality from correction speed', body: 'A fast correction can still be weak if it uses an unverified request or changes a future period unintentionally. A slower correction may be appropriate when the source conflicts or a sensitive field requires independent verification. Measure time to prepare, time waiting for owner review, source completeness, effective-date conflicts, repeated corrections, and downstream confirmation. Look for concentrations by request channel, field type, manager, or cycle. The analysis should separate a source-data problem from an entry mistake, a policy ambiguity, and a provider transformation. This distinction matters because each cause calls for a different response: better intake, clearer authority, system validation, or reviewer training.' },
      { heading: 'Limitations and evidence-led conclusion', body: 'Lineage quality depends on systems that preserve versions and on a retention approach that protects personal information. A record can prove that a decision was made without proving that the underlying request was honest or complete. Sampling also misses rare, high-impact failures. The evidence-led conclusion is to preserve a compact chain from source to result, require a date and named decision owner, and check the downstream effect before closing the item. Outsourced payroll support can make the chain easier to inspect, while sensitive interpretation and approval remain with the authorized company owner. The chain should be readable by someone who did not prepare the correction. Use field-level descriptions rather than vague labels such as “employee update,” and record whether the date is the request date, approval date, effective date, or processing date. These are different facts and can lead to different payroll outcomes. When a correction changes a future period, show that scope explicitly so a repair for one pay run is not silently applied to later runs. When the source conflicts with the existing record, pause and record the conflict instead of choosing the most recent message. A second reviewer may be required for bank details, sensitive identity data, or corrections that affect a closed cycle. The record should also show the post-change check: the output field, period, result, and person who confirmed it. If confirmation is not possible because the provider has not returned a result, keep the item open with an owner and next review time. This approach makes correction work explainable, supports targeted quality sampling, and protects the role boundary between preparation and approval.' },
    ],
    sources: [
      { label: 'National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/' },
      { label: 'NIST, Zero Trust Architecture SP 800-207', url: 'https://www.nist.gov/publications/zero-trust-architecture' },
      { label: 'Official Gazette of the Republic of the Philippines', url: 'https://www.officialgazette.gov.ph/' },
    ],
    faq: commonFaq,
    related: ['philippines-payroll-employee-data-lineage', 'philippines-payroll-effective-date-conflicts', 'philippines-payroll-sensitive-change-verification'],
  },
  {
    slug: 'philippines-payroll-provider-rejection-cohort-study',
    title: 'Philippines payroll provider rejection cohort study',
    excerpt: 'Research question: do recurring provider rejections originate in source data, timing, transformation, or an unclear review boundary?',
    published: '2026-08-23',
    stat: 'A rejection cohort groups failed payroll submissions by field, cause, pay period, correction owner, and resubmission outcome.',
    image: '/research-heroes/philippines-payroll-provider-rejection-cohort-study.png',
    takeaways: [
      'Question: what does a provider rejection reveal about the point where the payroll chain stopped accepting an input?',
      'Method: retain original rejection evidence and compare cohorts by cause, source, timing, and repeat occurrence.',
      'Conclusion: successful resubmission alone hides recurring defects; the original rejection must remain measurable.',
    ],
    sections: [
      { heading: 'Research question and cohort definition', body: 'A provider rejection is commonly closed when a corrected file is accepted. That outcome is useful but incomplete: it does not tell a payroll team whether the defect came from a missing source field, an invalid format, a conflicting employee state, a late input, a duplicate, or a provider-specific rule. This study asks what rejection cohorts can reveal about the control point that failed. The cohort contains the original provider message, field or record, source link, pay period, first submission time, correction owner, correction reason, resubmission result, and repeat history. It does not infer undocumented provider behavior or assign blame to a worker.' },
      { heading: 'Method: preserve the first failure', body: 'Capture the original rejected payload reference and message before preparing a correction. Normalize the reason into a small, reviewable taxonomy while retaining the provider’s original wording. Segment by source system, field, pay period, arrival time, employee state, and whether the same record was rejected before. Calculate rejection rate per 100 submitted records, repeat-rejection rate, time to correction, and unresolved count at cutoff. Compare at least three cycles so a one-off provider outage is not treated as a recurring source defect. A support specialist can collect evidence and maintain the cohort register. The authorized owner decides whether a correction is safe to submit.' },
      { heading: 'Analysis: choose the control that matches the cause', body: 'A high missing-field cohort points toward intake completeness or earlier manager review. An invalid-format cohort may call for a validation rule or a controlled transformation. Conflicting employee-state rejections need a source-of-truth decision and owner interpretation. Late arrivals expose cutoff and capacity problems, while repeated rejection of the same record may indicate that the correction addressed the symptom rather than the cause. Track rejected, corrected, accepted, and re-rejected states separately. Avoid celebrating a high acceptance rate if the same records circulate through multiple attempts or if the original evidence is discarded after success.' },
      { heading: 'Limitations and evidence-led conclusion', body: 'Provider vocabularies, interfaces, validation rules, and service windows are product-specific. Public Philippine labor and payment sources provide context but cannot explain a private provider’s implementation. A rejection cohort also cannot prove that a provider accepted a substantively correct result. The evidence-led conclusion is to preserve the first failure, classify it consistently, route the cause to the right owner, and re-measure later cycles. Outsourced payroll preparation can organize the register and flag repeat patterns, while the client-side owner retains authority over corrections, sensitive data, and final submission. Cohort analysis becomes more useful when a rejection is tied to the earliest controllable point in the chain. If a missing field was known before the file was prepared, the process should improve intake or validation. If the field was present but transformed incorrectly, the transformation deserves review. If the provider rule changed, the owner needs an updated source or implementation note rather than repeated manual repairs. Keep original messages and timestamps so a later analyst can tell whether the problem was present at first submission or introduced during correction. Measure re-rejections separately from first-time failures; otherwise a difficult record can look like several unrelated issues. Use a fixed reason taxonomy, but allow a documented “uncertain” category until qualified review resolves it. That prevents false precision. A monthly or per-cycle review can rank recurring cohorts by volume, cutoff impact, sensitivity, and repeat rate. The output should be an owned improvement with a verification sample in a later cycle, not a promise that all rejections will disappear. This preserves evidence, improves handoffs, and keeps final submission decisions with the authorized payroll owner.' },
    ],
    sources: [
      { label: 'Philippine Statistics Authority, Labor Force Survey', url: 'https://psa.gov.ph/statistics/labor-force-survey' },
      { label: 'Bangko Sentral ng Pilipinas, 2024 Report on E-payments Measurement', url: 'https://www.bsp.gov.ph/PaymentAndSettlement/2024_Report_on_E-payments_Measurement.pdf' },
      { label: 'Department of Information and Communications Technology', url: 'https://dict.gov.ph/' },
    ],
    faq: commonFaq,
    related: ['philippines-payroll-provider-rejection-patterns', 'philippines-payroll-source-validation', 'philippines-payroll-query-sampling-and-resolution'],
  },
  {
    slug: 'philippines-payroll-evidence-retention-minimization-study',
    title: 'Philippines payroll evidence retention and minimization study',
    excerpt: 'Research question: how can payroll operations retain enough evidence to explain a decision without turning working copies into an uncontrolled archive?',
    published: '2026-08-23',
    stat: 'A retention review connects each evidence class to its purpose, minimum fields, owner, access group, review trigger, and disposition.',
    image: '/research-heroes/philippines-payroll-evidence-retention-minimization-study.png',
    takeaways: [
      'Question: does each retained payroll record still serve a defined review, operational, contractual, or legal purpose?',
      'Method: sample closed cycles for duplicate copies, missing approvals, stale access, and records without a disposition owner.',
      'Conclusion: keep evidence understandable and bounded; neither “keep everything” nor “delete everything” is a control.',
    ],
    sections: [
      { heading: 'Research question and evidence classes', body: 'Payroll teams need records that explain a result, answer an employee or provider question, and support an authorized review. They also create exports, screenshots, email attachments, temporary spreadsheets, and duplicate working folders that may outlive their purpose. This study asks how to retain enough evidence while limiting unnecessary copies and access. The scope separates the approved payroll result, source records, approval evidence, exception decisions, reconciliation workpapers, temporary exports, and communications. For each class, record purpose, minimum fields, owner, approved access group, retention trigger, review date, and disposition action. This study does not set a universal number of years or interpret a legal hold.' },
      { heading: 'Method: test purpose and recoverability together', body: 'Sample closed pay periods and trace a set of decisions from output back to source, approval, exception treatment, and final confirmation. Then count duplicate copies, files with no owner, expired access, records containing more personal data than the task requires, and evidence that cannot be understood without a private conversation. Review both retention and minimization: a short record with no source may be insufficient, while a complete export copied into five folders may create avoidable exposure. A support specialist can inventory and classify records, link the approved source, and flag stale copies. The responsible owner approves retention and deletion decisions.' },
      { heading: 'Analysis: evidence value changes over time', body: 'A record can be essential during an open correction and unnecessary after a defined review point, but that decision should be observable. Distinguish active-cycle evidence from closed-cycle evidence, litigation or examination holds, contractual requirements, and ordinary working copies. Examine whether access still matches the task and whether a retained field remains necessary for the stated purpose. Privacy governance is not served by deleting the only explanation for a sensitive change, and operational quality is not served by preserving every raw export indefinitely. The useful measure is not the number of files removed; it is the percentage of evidence classes with an owner, purpose, access boundary, and documented next review.' },
      { heading: 'Limitations and evidence-led conclusion', body: 'Retention duties vary with jurisdiction, tax rules, employment records, contracts, litigation holds, system capabilities, and the facts of the employer. Public privacy guidance supports accountable processing but cannot determine the correct schedule for every company. Inventory findings can also undercount copies hidden in personal devices or unmanaged channels. The evidence-led conclusion is to maintain a purpose-based schedule, minimize fields and access, preserve the chain needed to explain a decision, and require qualified review before disposition. Outsourced payroll support may maintain the register and surface stale access, but it should not unilaterally delete or interpret records. The review should distinguish the authoritative result from a convenient copy. The authoritative result may need controlled retention, while a temporary export created to sort missing inputs may be deleted after the work is accepted, subject to the owner’s schedule and any hold. A screenshot that contains more employee information than the decision requires should be replaced by a narrower evidence note when possible. Access should be reviewed separately from retention: a record can still be required while its audience becomes smaller. For each class, document the event that starts the review clock, the person who confirms the disposition, and the evidence that the action occurred. If deletion cannot be verified in a system, record the limitation rather than claiming certainty. Sample closed cycles for both missing evidence and excess evidence. Missing approval records threaten explainability; excess copies increase access and discovery burden. Neither outcome is solved by a universal rule to keep or delete. A support lane can prepare the inventory, identify duplicate locations, and route proposed actions. The company’s authorized privacy, payroll, legal, or records owner must decide the schedule and any exception. That separation keeps minimization practical without turning an operational checklist into unsupported compliance advice.' },
    ],
    sources: [
      { label: 'National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/' },
      { label: 'NIST, Zero Trust Architecture SP 800-207', url: 'https://www.nist.gov/publications/zero-trust-architecture' },
      { label: 'Official Gazette of the Republic of the Philippines', url: 'https://www.officialgazette.gov.ph/' },
    ],
    faq: commonFaq,
    related: ['philippines-payroll-evidence-retention-balance', 'philippines-payroll-review-evidence-retention', 'philippines-payroll-access-recertification-by-task'],
  },
];

const depthNote = 'A practical review should name the record owner, the evidence location, the period covered, and the next decision. It should preserve uncertainty instead of converting an incomplete source into a confident status. Preparation work can be delegated when the task, access, and stop rule are explicit; interpretation and final approval remain with the authorized payroll owner. Review the first cycle closely, then use a documented sample only after the evidence pattern is stable. If the source system, provider rule, calendar, or authority changes, reset the baseline and explain the change. This keeps operational research honest: it measures a bounded process, identifies what the evidence supports, and avoids turning a context signal into a promise. The resulting record should be understandable to a reviewer who was not present for the original handoff and should point to one accountable person for unresolved work. Use a short status vocabulary, attach the source rather than paraphrasing it, and distinguish an unresolved exception from an approved exception. Record the date of the review and the person who made the disposition. A later quality check should test whether the record still supports the original conclusion, especially after a process or system change. This is how a daily support routine becomes evidence-led without expanding a preparation role into unapproved decision-making.';

export const august23ResearchPosts: readonly ResearchPost[] = august23ResearchDrafts.map(post => ({
  ...post,
  sections: [...post.sections, { heading: 'Operating interpretation', body: depthNote }],
}));
