const DATE = '2026-08-31';

const blogTopics = [
  ['payroll-variance-review','Payroll variance review before final approval','Compare gross-to-net totals, headcount, overtime, and one-time payments with the prior approved cycle.','Separate expected changes from unexplained differences.'],
  ['payroll-deadline-escalation','Payroll deadline escalation without last-minute confusion','Track late timesheets, missing approvals, employee changes, and provider questions against one cutoff.','Route unresolved items to the person who can accept, reject, or defer them.'],
  ['payroll-audit-trail-basics','Payroll audit trail basics for outsourced support','Link source requests, working files, approvals, corrections, and submission receipts.','Keep the decision record without copying sensitive data into extra systems.'],
  ['payroll-preprocessing-checks','Payroll preprocessing checks that catch avoidable errors','Check duplicate employees, blank fields, unusual hours, effective dates, and unapproved changes.','Return incomplete items to a named owner instead of guessing.'],
  ['off-cycle-payroll-request-intake','Off-cycle payroll request intake and approval','Record the reason, affected worker, amount basis, source record, and requested pay date.','Keep calculation and release approval with authorized payroll staff.'],
  ['payroll-garnishment-routing','Payroll garnishment document routing for support teams','Record the receipt date, issuing body, employee identifier, response deadline, and owner.','Route the document promptly without interpreting what the order requires.'],
  ['multi-entity-payroll-intake','Multi-entity payroll intake without mixed records','Label every record with its legal entity, pay group, work location, currency, and approver.','Stop when the employing entity or pay group cannot be confirmed.'],
  ['payroll-returned-payment-workflow','Returned payroll payment workflow and case log','Start with the provider or bank notice and record the payment reference and resolution owner.','Verify through a known contact method before any payment destination changes.'],
  ['payroll-year-to-date-validation','Payroll year-to-date validation after a system change','Reconcile gross pay, taxable wages, taxes, deductions, benefits, and prior corrections.','Document every difference before closing the migration check.'],
  ['payroll-case-priority-rules','Payroll case priority rules for employee questions','Prioritize missed pay, suspected fraud, deadline-bound notices, document requests, and status questions.','Give urgent cases a named owner and next update time.'],
  ['payroll-file-transfer-checklist','Payroll file transfer checklist for outside providers','Verify file name, period, entity, recipient, secure channel, row count, and sender approval.','Record the transfer receipt and remove temporary copies under the retention rule.'],
  ['payroll-service-review-agenda','Payroll service review agenda for monthly vendor meetings','Review cutoff performance, open cases, recurring exceptions, access changes, and calendar risks.','End each topic with an owner, action, and review date.'],
] as const;

const sources = [
  {name:'CISA: Turn on multifactor authentication',url:'https://www.cisa.gov/secure-our-world/turn-mfa',note:'Official account-security guidance.'},
  {name:'NIST: Zero Trust Architecture',url:'https://www.nist.gov/publications/zero-trust-architecture',note:'Official guidance on explicit verification and limited access.'},
  {name:'Philippine National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official text covering personal-information accountability.'},
  {name:'IRS: Publication 15',url:'https://www.irs.gov/publications/p15',note:'Official U.S. employer payroll reference; verify rules for the applicable jurisdiction.'},
];

export const august31BlogPosts = blogTopics.map(([slug,title,method])=>({slug,title,excerpt:method,minutes:10}));
export const august31BlogDetails = Object.fromEntries(blogTopics.map(([slug,title,method,stop])=>[slug,{
  takeaways:[method,stop,'Keep final payroll approval with a named company owner or authorized provider.'],
  readinessRows:[
    {area:'Scope',ready:'The expected records and finish line are written down.',ownerCheck:'The owner confirms the scope for this pay cycle.'},
    {area:'Source',ready:'Each item links to an approved request or system record.',ownerCheck:'The owner resolves missing or conflicting evidence.'},
    {area:'Access',ready:'Named accounts have only the permissions needed for preparation.',ownerCheck:'The access owner removes unused permissions.'},
    {area:'Approval',ready:'Prepared work and exceptions are dated and reviewable.',ownerCheck:'An authorized person records the final decision.'},
  ],
  sections:[
    {heading:'Start with the records in front of you',paragraphs:[`${method} Define each field in plain language so two people would classify the same request the same way.`, `Use a real source for every row. A support specialist can organize evidence and flag gaps, but should not fill a blank with an assumption. ${stop}`]},
    {heading:'Set ownership before the cutoff',paragraphs:['Name the preparer, reviewer, final approver, and backup before work begins. Put the cutoff and escalation time in UTC and in the local time used by the payroll owner.','The preparer reports what is complete, what is late, and what needs a decision. The approver owns sensitive changes and final submission.'],bullets:['Use a named account.','Link questions to their source.','Record the decision and time.','Pause when authority is unclear.']},
    {heading:'Review the population before exceptions',paragraphs:['Check the entity, pay group, date range, and expected record count before opening individual cases. A line-by-line check can miss an absent group.','Sort exceptions by worker impact and deadline. Every open row needs an owner, next action, and review time.']},
    {heading:'Protect employee information',paragraphs:['Payroll files can contain identity, pay, tax, benefit, and bank information. Store them in approved systems, restrict exports, and share links instead of extra copies when possible.','Outside support does not remove the company’s responsibility for data. Confirm retention and processing duties with the relevant adviser.']},
    {heading:'Close the cycle with evidence',paragraphs:['Send one dated note with completed work, remaining exceptions, approvals, and the next cutoff. A manager should not need to reconstruct the result from chat.','Sample several items back to their sources. Correct unclear instructions, remove unneeded access, and keep the routine narrow until results are consistent.']},
  ],
  roleBrief:[`Routine: ${title}`,'Output: dated tracker with sources, exceptions, and decisions','Access: named account with task-specific permissions','Approval: authorized payroll owner','Stop rule: pause when evidence or authority is unclear'],
  faqs:[{question:`Who should own ${title.toLowerCase()}?`,answer:'A support specialist can prepare and track the work. A named payroll owner should resolve exceptions and approve actions that change payroll records.'},{question:'How should a team test this routine?',answer:'Run one complete pay cycle, sample items back to their sources, and correct the checklist before adding scope.'},{question:'Is this legal or tax advice?',answer:'No. Confirm legal, tax, privacy, and employment requirements with the relevant authority or qualified adviser.'}],
  sources,
  rich:{keyword:title.toLowerCase(),marker:`opc-20260831-${slug}`,published:DATE,directAnswer:[`${method} Assign one preparer and one approver, define the source record, and write a stop rule for uncertain changes.`,`${stop} Test the workflow for one complete pay cycle before adding scope.`],stats:[{value:'1',label:'named final approver',note:'Minimum control for the work lane'},{value:'1 cycle',label:'initial pilot',note:'Review before expansion'}],quote:{text:'Never trust, always verify.',attribution:'NIST zero trust principle, summarized',url:'https://www.nist.gov/publications/zero-trust-architecture'},chart:{title:'Preparation and approval stay separate',description:'A two-step control from preparation to owner approval.',methods:'Illustrative workflow; it does not report measured performance.'},graphic:{title:'Payroll review path',description:'A path from source to decision.',steps:['Source','Prepare','Review','Decision']},banners:[{eyebrow:'Next pay cycle',heading:'Define one payroll support lane',text:'Start with a repeat task, owner, and stop rule.',href:'/contact',label:'Discuss payroll support'}],internalLinks:[{href:'/services/payroll-data-entry',label:'Payroll data entry support'},{href:'/services/payroll-reporting',label:'Payroll reporting support'},{href:'/research',label:'Payroll operations research'}]},
}]));

const researchTopics = [
 ['philippines-payroll-digital-payment-readiness','Philippines payroll digital payment readiness','57.4%','BSP reported that digital payments accounted for 57.4% of retail payment volume in 2024.','Payment readiness depends on verified destinations, maker-checker approval, and a transfer receipt.'],
 ['philippines-payroll-privacy-impact-review','Philippines payroll privacy impact review','Section 21','Section 21 of the Philippine Data Privacy Act addresses accountability for information transferred to a third party for processing.','Review purpose, fields, access, recipients, retention, and escalation before launch.'],
 ['philippines-payroll-workforce-capacity-planning','Philippines payroll workforce capacity planning','49.01M','PSA estimated 49.01 million employed people in the Philippines in its 2025 annual labor statistics.','Plan capacity from transaction volume, deadlines, exception rates, and backup coverage.'],
 ['philippines-payroll-business-continuity-test','Philippines payroll business continuity test','4 roles','A payroll continuity test should name the preparer, reviewer, approver, and backup.','Test a realistic interruption and correct the recovery checklist before the next cutoff.'],
 ['philippines-payroll-quality-sampling','Philippines payroll quality sampling','2 layers','A review can combine a population-level control check with a documented sample of individual items.','Choose the sample before reviewing outcomes and trace each item to its source.'],
] as const;
const researchSources=[
 {label:'Philippine Statistics Authority labor-force statistics',url:'https://psa.gov.ph/statistics/labor-force-survey'},
 {label:'Bangko Sentral ng Pilipinas e-payments report',url:'https://www.bsp.gov.ph/PaymentAndSettlement/2024_Report_on_E-payments_Measurement.pdf'},
 {label:'National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},
 {label:'Bureau of Internal Revenue',url:'https://www.bir.gov.ph/'},{label:'Department of Labor and Employment',url:'https://www.dole.gov.ph/'},
 {label:'Official Gazette of the Philippines',url:'https://www.officialgazette.gov.ph/'},{label:'ILO Philippines',url:'https://www.ilo.org/manila'},
 {label:'World Bank Philippines',url:'https://www.worldbank.org/en/country/philippines/overview'},{label:'NIST Zero Trust Architecture',url:'https://www.nist.gov/publications/zero-trust-architecture'},
 {label:'CISA MFA guidance',url:'https://www.cisa.gov/secure-our-world/turn-mfa'},
] as const;
export const august31ResearchPosts=researchTopics.map(([slug,title,stat,measure,finding],index)=>({slug,title,excerpt:finding,published:DATE,stat,takeaways:[finding,'Assign a person to each cutoff, exception, and approval.','Keep the source, working note, and decision in one chain.'],sections:[{heading:'Research question and context',body:`The headline measure is ${measure} This is context for process design, not a claim about a worker or provider. The operating question is whether the team can show who prepared an item, which source they used, who reviewed it, and when the decision was made.`},{heading:'Control design',body:`${finding} Define the expected population and allowed records. Use named accounts and task-specific permissions. Keep disputed pay, tax treatment, deductions, bank changes, and final approval with authorized owners.`},{heading:'Testing method',body:'Pilot the control on one complete cycle. Check population totals, then select a documented sample with routine records and higher-risk exceptions. Trace each item to its source and approval. Assign corrections and repeat failed checks.'},{heading:'Limits and implementation',body:'Public sources provide context but do not prove that a workflow is compliant or effective. Requirements differ by employer and jurisdiction. Confirm duties with the relevant authority or qualified adviser.'}],sources:researchSources,faq:[{question:'Is this a compliance opinion?',answer:'No. This is operational research. Confirm requirements with the relevant authority or qualified adviser.'},{question:'What is the first step?',answer:'Define one lane, its source records, preparer, reviewer, approver, cutoff, and stop rule, then test one cycle.'}],related:researchTopics.filter((_,i)=>i!==index).slice(0,3).map(x=>x[0])}));
