type Step = { heading: string; text: string };
type Spec = { slug: string; title: string; excerpt: string; image: string; theme: string; steps: Step[] };

const common = (s: Spec) => s.steps.map((x, i) => ({
  heading: x.heading,
  paragraphs: [
    `${x.text} In outsourced payroll support, this is a working control rather than a slogan. The support specialist can gather records, compare them with the named source, update a tracker, and make a factual follow-up request. The payroll owner keeps the authority to interpret policy, approve a sensitive change, resolve a disagreement, or release a final submission. That division matters because a clean preparation record is useful only when everyone can see what was observed, what remains uncertain, and who is expected to decide. Keep the covered pay period visible on every row and make the next action concrete enough that another person can pick up the work without reconstructing the conversation.

For a Philippines-based support lane, write the example before assigning the task. Show one complete good record, one incomplete record, and one item that must stop for owner review. Use the same vocabulary across the tracker, handoff note, and review meeting. Avoid asking the support role to “handle payroll” when the intended work is collecting timesheets, checking a roster, routing a provider question, or preparing evidence. Narrow language reduces accidental authority and makes quality review faster. It also gives a manager a fair way to assess the output: the record either contains the required source, period, status, owner, and next action or it does not.

The practical test is whether the control still works when the deadline is close. A missing document should be visible, not silently inferred. A conflicting value should retain both source references, not be “fixed” by choosing the more convenient one. An urgent message should follow the approved escalation route, not create a new permission. Treat a hold as a valid result when identity, source authority, access, or approval is unclear. The point of this step is to make payroll preparation easier to inspect while keeping final judgment with the authorized payroll owner.`,
  ],
}));

const specs: Spec[] = [
  { slug: 'payroll-cutoff-evidence-window', title: 'How to Build a Payroll Cutoff Evidence Window', excerpt: 'Define the records, timestamps, and owner checks that make a payroll cutoff review possible.', image: '/blog-heroes/aug21-payroll-cutoff-evidence-window.png', theme: 'cutoff evidence', steps: [
    { heading: 'Start with the cutoff question', text: 'A cutoff window should answer which inputs were expected, when they arrived, and whether the owner had enough evidence to review them.' }, { heading: 'Separate arrival from approval', text: 'A file can arrive on time without being approved, and an approval can exist without proving the underlying record is complete.' }, { heading: 'Record the covered period', text: 'Place the pay period, cutoff point, source system, and last update beside every item so an old file cannot look current.' }, { heading: 'Use an exception clock', text: 'Give missing or disputed items a next-action time and named owner instead of allowing an exception to disappear in a message thread.' }, { heading: 'Prepare the review view', text: 'Summarize ready, held, and owner-decision items in separate lanes so the final reviewer sees risk before routine detail.' }, { heading: 'Protect the boundary', text: 'Preparation may identify a late change, but it must not approve pay, tax, banking, benefit, or employment-status outcomes.' }, { heading: 'Inspect one full cycle', text: 'A complete cycle reveals whether the window captures real work or only records activity after the deadline has passed.' }, { heading: 'Close with evidence', text: 'Finish with the owner decision, unresolved items, downstream receipt, and the adjustment needed for the next cutoff.' }, ] },
  { slug: 'payroll-timesheet-reconciliation-lane', title: 'A Safer Timesheet Reconciliation Lane for Payroll Support', excerpt: 'Reconcile hours to their source without turning an outsourced preparation role into an approval role.', image: '/blog-heroes/aug21-payroll-timesheet-reconciliation.png', theme: 'timesheet reconciliation', steps: [
    { heading: 'Define the population', text: 'List the employees, work dates, pay code categories, and source reports included before comparing any hours.' }, { heading: 'Compare like with like', text: 'Reconcile the same period and unit across scheduling, timekeeping, and payroll preparation records instead of comparing summaries with detail.' }, { heading: 'Flag differences neutrally', text: 'A variance is a question for the owner or manager, not permission for support to change a value.' }, { heading: 'Trace the correction', text: 'Keep the original value, source reference, person asked, response, and resulting owner decision in one visible chain.' }, { heading: 'Handle late approvals', text: 'Record what is missing and when it was requested, then escalate through the approved route when the deadline is at risk.' }, { heading: 'Limit sensitive visibility', text: 'Give the worker only the fields and systems needed to reconcile hours, with approved access and named review.' }, { heading: 'Review patterns carefully', text: 'Repeated differences may justify a process question, but they are not proof of misconduct, underpayment, or a policy violation.' }, { heading: 'Hand back the lane', text: 'The closeout should show reconciled rows, held rows, owner decisions, and a concrete change to the next cycle checklist.' }, ] },
  { slug: 'payroll-change-approval-boundary', title: 'Payroll Change Requests: Where Preparation Must Stop', excerpt: 'Create an explicit boundary for employee changes so support can prepare evidence without deciding the outcome.', image: '/blog-heroes/aug21-payroll-change-approval-boundary.png', theme: 'change approval', steps: [
    { heading: 'Classify the request', text: 'Distinguish a request to collect information from a request to change pay, tax, bank, benefit, or employment-status data.' }, { heading: 'Verify the source', text: 'Record where the request originated, which employee and effective date it concerns, and whether the identity check is complete.' }, { heading: 'Build the packet', text: 'Support can assemble the form, related record, missing-field list, and routing note for an authorized reviewer.' }, { heading: 'Name the decision owner', text: 'Every change should have a responsible owner who can approve, reject, or ask for clarification before the record moves.' }, { heading: 'Use effective-date logic', text: 'An effective date should be checked against the pay period and existing changes without being silently rewritten by preparation staff.' }, { heading: 'Create a stop rule', text: 'Unverified identity, conflicting instructions, missing approval, and unusual urgency all require a hold and escalation.' }, { heading: 'Check the downstream record', text: 'After approval, compare the accepted record or provider receipt with the request while keeping the owner accountable for the result.' }, { heading: 'Remove loose copies', text: 'Close by storing the approved evidence in the approved system and deleting unnecessary working copies under the organization’s retention rules.' }, ] },
  { slug: 'payroll-exception-aging-review', title: 'How to Review Aging Payroll Exceptions Without Losing Context', excerpt: 'Use age, owner, source, and risk together when deciding which payroll exceptions need attention first.', image: '/blog-heroes/aug21-payroll-exception-aging-review.png', theme: 'exception aging', steps: [
    { heading: 'Define an exception', text: 'An exception is a missing, conflicting, rejected, or unexplained item that prevents a stated preparation step from being marked ready.' }, { heading: 'Measure age from an event', text: 'Start the clock at receipt, detection, or last requested action and record which event was used.' }, { heading: 'Add consequence context', text: 'Age alone is not risk; note the affected period, downstream dependency, sensitivity, and decision needed.' }, { heading: 'Assign a real owner', text: 'A queue steward can coordinate reminders, but the policy or payroll owner must decide how a disputed item is handled.' }, { heading: 'Use aging bands carefully', text: 'Bands help sort work, yet they should never pressure support into making a decision merely because a card is old.' }, { heading: 'Preserve the history', text: 'Keep prior requests, replies, source links, and holds so a reviewer can see why the item remains open.' }, { heading: 'Escalate with a brief', text: 'A useful escalation states the fact, gap, consequence, attempted follow-up, and exact question for the owner.' }, { heading: 'Close the cause', text: 'After resolution, record the accepted answer and whether a form, calendar, source list, or training example should change.' }, ] },
  { slug: 'payroll-provider-handoff-packet', title: 'The Payroll Provider Handoff Packet: What to Include and What to Hold', excerpt: 'Prepare a provider-ready packet that is traceable, reviewable, and bounded by owner approval.', image: '/blog-heroes/aug21-payroll-provider-handoff-packet.png', theme: 'provider handoff', steps: [
    { heading: 'State the handoff purpose', text: 'Name the pay period, requested provider action, included population, and person responsible for final release.' }, { heading: 'List source records', text: 'Every material field should point to an approved source or clearly state that it is awaiting owner confirmation.' }, { heading: 'Separate preparation from release', text: 'Support may organize and quality-check a packet, while an authorized owner decides whether it can be submitted.' }, { heading: 'Show exceptions plainly', text: 'Do not hide a late timesheet, rejected file, uncertain change, or unresolved employee question inside a clean-looking summary.' }, { heading: 'Use a handoff checklist', text: 'Check names, period, file version, required approvals, secure location, and recipient before asking the owner to review.' }, { heading: 'Keep provider questions factual', text: 'Ask the provider to confirm a rule or status without promising an outcome or interpreting tax, legal, or policy matters.' }, { heading: 'Capture the receipt', text: 'The closeout record should link the sent version, owner approval, provider receipt, and any follow-up item.' }, { heading: 'Review the next handoff', text: 'Use one cycle’s questions to improve the packet structure, not to make unsupported claims about performance or results.' }, ] },
  { slug: 'payroll-backup-coverage-plan', title: 'A Payroll Backup Coverage Plan for Narrow, Reviewable Support', excerpt: 'Design backup coverage around repeatable payroll preparation lanes, clear ownership, and safe handbacks.', image: '/blog-heroes/aug21-payroll-backup-coverage-plan.png', theme: 'backup coverage', steps: [
    { heading: 'Choose the lane', text: 'Backup coverage works best for a defined tracker, inbox triage, document route, or follow-up list rather than an undefined payroll role.' }, { heading: 'Write the normal finish line', text: 'Describe what a complete daily handoff contains so a backup worker can recognize ready, held, and owner-review work.' }, { heading: 'Prepare access in advance', text: 'Use named accounts, least privilege, multifactor authentication, and a short access review before an absence begins.' }, { heading: 'Publish the escalation map', text: 'A backup should know who owns pay, tax, banking, benefits, employment status, provider release, and urgent employee questions.' }, { heading: 'Use a handover note', text: 'Record current status, pending items, source links, deadlines, owner decisions, and any known limitation without copying unnecessary personal data.' }, { heading: 'Practice a small scenario', text: 'A mock late approval or rejected source can show whether the backup knows how to pause and route the decision.' }, { heading: 'Review the return', text: 'When the primary owner returns, transfer open items with evidence rather than leaving temporary decisions or access unexamined.' }, { heading: 'Retire unused access', text: 'Coverage ends when the approved window ends; remove unneeded permissions and note any process gap revealed by the absence.' }, ] },
  { slug: 'payroll-access-review-cycle', title: 'How to Run a Payroll Data Access Review Cycle', excerpt: 'Review payroll access by task and evidence so permissions match current support responsibilities.', image: '/blog-heroes/aug21-payroll-access-review-cycle.png', theme: 'access review', steps: [
    { heading: 'Inventory the systems', text: 'List payroll, HR, timekeeping, storage, communication, and provider locations that the support lane can reach.' }, { heading: 'Map access to tasks', text: 'Explain why each permission exists and which preparation step would fail without it.' }, { heading: 'Check the named user', text: 'Confirm the account belongs to the assigned person, uses approved authentication, and is not a shared credential.' }, { heading: 'Review the period', text: 'Permissions should reflect the current assignment, not every task the person might perform in the future.' }, { heading: 'Separate visibility from action', text: 'Viewing a source, uploading a prepared file, editing a tracker, and approving payroll are different authorities.' }, { heading: 'Record owner confirmation', text: 'The responsible manager or payroll owner should accept, reduce, or revoke access with a dated decision.' }, { heading: 'Investigate mismatches', text: 'An unused permission is a review question, while an unlogged change is an escalation requiring evidence.' }, { heading: 'Close the review', text: 'Store the decision record, update the access register, and schedule the next review based on the task’s risk and cadence.' }, ] },
  { slug: 'payroll-question-triage-lane', title: 'Payroll Question Triage: A Safe Lane for Routine Employee Support', excerpt: 'Sort routine payroll questions from owner decisions without promising an answer the support role cannot authorize.', image: '/blog-heroes/aug21-payroll-question-triage.png', theme: 'question triage', steps: [
    { heading: 'Capture the question', text: 'Record the topic, received date, employee reference, pay period, requested outcome, and minimum necessary context.' }, { heading: 'Use known categories', text: 'Separate status, document, timing, pay amount, tax, benefit, banking, deduction, and employment-status questions.' }, { heading: 'Answer only from approved material', text: 'Routine replies can explain a documented process or request a missing detail without predicting a payroll result.' }, { heading: 'Route sensitive topics', text: 'Pay disputes, tax questions, garnishments, bank changes, benefits, and status decisions belong with an authorized owner.' }, { heading: 'Avoid identity assumptions', text: 'Use the approved verification route and do not disclose sensitive information because a message sounds familiar.' }, { heading: 'Track the response', text: 'Save the source of the answer, responder, date, next step, and any promise made by the owner.' }, { heading: 'Review repeat questions', text: 'Patterns may indicate a clearer notice or FAQ is needed, but they do not establish a cause without checking the underlying facts.' }, { heading: 'Close respectfully', text: 'A complete ticket states what was answered, what remains with the owner, and where the employee should follow up.' }, ] },
  { slug: 'payroll-cycle-closeout-record', title: 'The Payroll Cycle Closeout Record: A Practical Final Check', excerpt: 'Close each payroll preparation cycle with evidence of decisions, held items, receipts, and next actions.', image: '/blog-heroes/aug21-payroll-cycle-closeout-record.png', theme: 'cycle closeout', steps: [
    { heading: 'Define closeout', text: 'Closeout is the point where preparation is handed back with a visible result, not the claim that every payroll issue disappeared.' }, { heading: 'Confirm the population', text: 'Record the employee or transaction scope, pay period, source version, and any exclusions that the owner should know.' }, { heading: 'List owner decisions', text: 'Capture approvals, holds, rejections, and questions with dates and responsible people rather than relying on a status label.' }, { heading: 'Attach downstream evidence', text: 'Use a provider receipt, accepted file, review note, or other approved evidence that shows where the prepared work went.' }, { heading: 'Carry open items forward', text: 'Unfinished work needs a next owner and next action so it does not become invisible at the start of the next cycle.' }, { heading: 'Check temporary access', text: 'Remove or review access that was granted for the cycle, and retain only what the ongoing assignment requires.' }, { heading: 'Note process friction', text: 'Record late sources, unclear fields, repeated chases, and approval bottlenecks as improvement questions rather than performance claims.' }, { heading: 'Set the next start', text: 'End with the first expected input and the date the next tracker opens, making the routine easier to repeat.' }, ] },
  { slug: 'payroll-source-authority-map', title: 'Payroll Source Authority: How to Resolve Competing Records', excerpt: 'Create a source authority map that helps payroll support surface conflicts without choosing silently.', image: '/blog-heroes/aug21-payroll-source-authority-map.png', theme: 'source authority', steps: [
    { heading: 'Name the decision field', text: 'Start with the exact field or fact that conflicts, such as hours, effective date, status, or approval.' }, { heading: 'List every candidate source', text: 'Record the systems, forms, messages, and reports that contain the competing values and their covered periods.' }, { heading: 'Identify the policy owner', text: 'The owner of the process decides which source governs; support should not infer authority from convenience or recency alone.' }, { heading: 'Check version and scope', text: 'A newer record can still be the wrong period, employee, or transaction, so verify scope before treating it as authoritative.' }, { heading: 'Preserve the conflict', text: 'Keep the original references and describe the mismatch neutrally so the owner can inspect the reasoning.' }, { heading: 'Route the question', text: 'A good escalation asks one answerable question and includes enough evidence to avoid another round of searching.' }, { heading: 'Update the register', text: 'After a decision, record the authority rule and effective scope without overwriting the historical evidence.' }, { heading: 'Teach the next cycle', text: 'Turn recurring confusion into a source note, example, or checklist field that helps the next preparer find the right record.' }, ] },
  { slug: 'payroll-owner-review-meeting-packet', title: 'Build a Payroll Owner Review Meeting Packet', excerpt: 'Give the payroll owner a concise packet for decisions, exceptions, and evidence before the handoff.', image: '/blog-heroes/aug21-payroll-owner-review-meeting-packet.png', theme: 'owner review', steps: [
    { heading: 'Lead with decisions', text: 'Put the exact approvals, holds, and questions first so the meeting does not begin with an unstructured file tour.' }, { heading: 'Show the scope', text: 'Name the pay period, population, source cutoff, preparation owner, and items excluded from the packet.' }, { heading: 'Use evidence links', text: 'Each decision item should connect to a source record, requested change, prior response, or provider note.' }, { heading: 'Keep routine detail behind it', text: 'A supporting register can contain row-level completeness checks without burying the owner’s decisions in every field.' }, { heading: 'Mark confidence honestly', text: 'Use ready, held, conflicting, and awaiting owner terms instead of implying certainty that the record does not support.' }, { heading: 'Ask bounded questions', text: 'Phrase questions so the owner can decide the specific action, effective date, or escalation route required.' }, { heading: 'Record the meeting result', text: 'Capture the owner, date, decision, excluded scope, and next action while the context is still available.' }, { heading: 'Send the handback', text: 'Distribute only the approved summary through the approved channel and update the working register with the result.' }, ] },
  { slug: 'payroll-work-queue-owner-matrix', title: 'A Payroll Work Queue Owner Matrix That Survives Busy Weeks', excerpt: 'Assign payroll preparation work by outcome, backup, evidence, and escalation rather than by vague job title.', image: '/blog-heroes/aug21-payroll-work-queue-owner-matrix.png', theme: 'queue ownership', steps: [
    { heading: 'Describe the outcome', text: 'Name the finished artifact or reviewed state for each queue lane instead of assigning an undefined responsibility.' }, { heading: 'Assign one accountable owner', text: 'A support worker can prepare or coordinate, but one authorized person must own the decision and result.' }, { heading: 'Name the backup', text: 'Coverage should be visible before an absence, with a limited scope and handback date.' }, { heading: 'Specify evidence', text: 'State the source, tracker field, receipt, or decision record that proves the lane reached its finish line.' }, { heading: 'Add escalation triggers', text: 'Missing identity, conflicting source, sensitive request, missed cutoff, and rejected file should each have a route.' }, { heading: 'Review load without guessing', text: 'A full queue may show a capacity issue, but it does not justify changing priorities or outcomes without the owner.' }, { heading: 'Audit transitions', text: 'When work moves between people, record why, when, and what evidence was transferred.' }, { heading: 'Refine after a cycle', text: 'Remove ambiguous lanes, split overloaded outcomes, and keep the matrix aligned with the actual payroll routine.' }, ] },
];

export const august21BlogPosts = specs.map((s, i) => ({ slug: s.slug, title: s.title, excerpt: s.excerpt, minutes: 11 + (i % 4), published: '2026-08-21', order: i + 1 }));
export const august21BlogDetails = Object.fromEntries(specs.map(s => [s.slug, {
  takeaways: s.steps.slice(0, 4).map(x => x.text),
  readinessRows: [
    { area: 'Source', ready: 'The source and covered period are named.', ownerCheck: 'The owner confirms authority and scope.' },
    { area: 'Exceptions', ready: 'Each gap has a named next action.', ownerCheck: 'The owner decides whether to hold or proceed.' },
    { area: 'Sensitive work', ready: 'The role has an explicit stop rule.', ownerCheck: 'An authorized owner approves the action.' },
    { area: 'Closeout', ready: 'The handoff has a date and evidence.', ownerCheck: 'The owner confirms the final scope.' },
  ],
  sections: common(s), roleBrief: [`Role focus: ${s.theme} preparation for payroll operations support`, 'Daily output: a dated, source-linked record with status, owner, and next action', 'Access: named task-specific account with multifactor authentication', 'Stop rule: pause disputed, sensitive, or unsupported decisions for the authorized owner', 'Review point: payroll owner checks the evidence before any final provider action'],
  faqs: [{ question: 'What may outsourced payroll support do?', answer: 'Collect, organize, compare, route, and document information within an approved task boundary. Final payroll, tax, banking, benefit, and employment decisions remain with the authorized owner.' }, { question: 'What should happen when evidence conflicts?', answer: 'Preserve the sources, record the conflict, hold the item, and ask the named owner one factual question through the approved route.' }, { question: 'What proves the lane is complete?', answer: 'A dated source reference, visible status, owner decision or hold, downstream evidence where applicable, and a clear next action for anything unresolved.' }],
  sources: [{ name: 'NIST: Zero Trust Architecture', url: 'https://www.nist.gov/publications/zero-trust-architecture', note: 'Official guidance for explicit verification and bounded access.' }, { name: 'CISA: Multifactor Authentication', url: 'https://www.cisa.gov/secure-our-world/turn-mfa', note: 'Official account-security guidance.' }],
  rich: { keyword: s.title, marker: `opc-aug21-${s.slug}`, published: '2026-08-21', image: s.image, directAnswer: [`The practical answer is to use ${s.theme} as an evidence-led preparation lane with a named reviewer, explicit stop rules, and a dated closeout.`], stats: [], quote: { text: 'There is no implicit trust granted to assets or user accounts based solely on location or ownership.', attribution: 'NIST SP 800-207', url: 'https://www.nist.gov/publications/zero-trust-architecture' }, chart: { title: 'A bounded payroll support lane', description: 'Source, preparation, owner review, and closeout.', methods: 'Process illustration, not a performance claim.' }, graphic: { title: 'Preparation to approval', description: 'A four-step payroll support boundary.', steps: ['Source', 'Prepare', 'Owner review', 'Closeout'] }, banners: [], internalLinks: [{ href: '/services/operations-support', label: 'Payroll operations support' }, { href: '/services/reporting-and-qa', label: 'Payroll reporting and QA support' }] }
}])) as any;
