const DATE='2026-09-28';
export const decisionSources=[
 {name:"IRS Publication 15 (2026), Employer's Tax Guide",url:'https://www.irs.gov/publications/p15',note:'Official employer guidance for federal payroll records, deposits, reporting, and corrections.'},
 {name:'U.S. Department of Labor Fact Sheet #21',url:'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping',note:'Official summary of federal wage and hour recordkeeping requirements.'},
 {name:'NIST SP 800-53 Rev. 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Official security and privacy control guidance.'},
 {name:'Philippine National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/',note:'Official Philippine privacy resource for teams handling personal information.'},
];
export type DecisionTopic={slug:string;title:string;excerpt:string;subject:string;artifact:string;fields:string;authority:string;scenario:string;failure:string;test:string;metrics:string;lens:string;service:string;image:string;independent?:boolean};
type T=DecisionTopic;
const serviceRoute=(route:string)=>({
 '/services/operations-support':'/services/payroll-preparation',
 '/services/reporting-and-qa':'/services/payroll-reporting',
 '/services/customer-support':'/services/payroll-query-support',
 '/services/admin-support':'/services/payroll-data-entry',
}[route]??route);
const topics:readonly T[]=[
 {slug:'payroll-outsourcing-rfp-scorecard',title:'Build a payroll outsourcing RFP scorecard that exposes operating differences',excerpt:'Compare providers through observable workflows, ownership, evidence, security, implementation, and exit readiness instead of polished feature lists.',subject:'provider selection',artifact:'an evidence-backed RFP scorecard tied to a representative pay-cycle walkthrough',fields:'service boundary, named owner, cutoff behavior, exception route, review evidence, security scope, implementation dependency, export format, and exit obligation',authority:'weights, mandatory conditions, acceptable risk, contractual remedies, and final provider selection',scenario:'a late employee change arrives after cutoff while the payroll owner is unavailable',failure:'a proposal earns credit for approvals even though no approver, evidence field, or late-change behavior is defined',test:'give every finalist the same redacted change request and request the resulting queue record, escalation, approval evidence, and corrected output',metrics:'unanswered evidence requests, owner ambiguities, workflow gaps, scenario exceptions, and buyer dependencies',lens:'Separate mandatory conditions from scored preferences. A long list of equally weighted questions hides the buying team’s priorities. Score demonstrations, contract language, sample records, and dated follow-up answers rather than confident sales language. Two reviewers should calibrate the rubric on one proposal, preserve their first disagreement, clarify the rule, and then rescore every finalist consistently. The recommendation should expose unpriced buyer work and open evidence; a high average must not erase a mandatory security or authority failure.',service:'/services/operations-support',image:'/blog-heroes/payroll-handoff-qa-scorecard.png'},
 {slug:'payroll-outsourcing-service-level-agreement',title:'Write payroll outsourcing service levels around decisions and evidence',excerpt:'Turn vague responsiveness promises into measurable service windows, owner actions, exception states, and verification records.',subject:'service-level design',artifact:'a service schedule connected to the payroll calendar and responsibility matrix',fields:'event definition, start timestamp, pause rule, time zone, severity, provider action, buyer dependency, evidence source, remedy, and review cadence',authority:'commercial remedies, severity policy, statutory interpretation, release approval, and acceptance of service risk',scenario:'an urgent correction is reported before payday but after the ordinary processing window',failure:'a fast response promise never says whether acknowledgement, human triage, owner decision, or completed correction stops the clock',test:'replay ordinary, late, incomplete, and high-impact requests against the proposed clock rules',metrics:'eligible events, human review time, owner-wait time, completion time, reopened cases, and disputed classifications',lens:'Define response and resolution separately. An automated acknowledgement can be useful, but it is not diagnosis, workaround, corrected file, approved rerun, or verified employee outcome. Name the evidence for every stage and use the source calendar for business-day promises. Review event-level misses before percentages because thousands of low-impact acknowledgements can conceal one failed payroll release. Watch for incentives to close and reopen tickets or request unnecessary information simply to pause a timer.',service:'/services/reporting-and-qa',image:'/blog-heroes/payroll-cycle-closeout-ledger.png'},
 {slug:'payroll-outsourcing-implementation-timeline',title:'Plan a payroll outsourcing implementation timeline from inventory to controlled go-live',excerpt:'Build the implementation around decisions, data, testing, owner readiness, and reversible launch gates rather than one target date.',subject:'implementation planning',artifact:'a dependency plan with entry criteria, exit evidence, owners, contingency dates, and rollback gates',fields:'workstream, predecessor, owner, source, decision deadline, environment, test evidence, defect state, readiness gate, and rollback trigger',authority:'scope, policy interpretation, configuration acceptance, defect acceptance, go-live, rollback, and final payroll release',scenario:'parallel testing finds a recurring deduction difference five business days before launch',failure:'the project reports ninety percent complete because tasks started although source data and acceptance evidence remain open',test:'walk one employee event from source through mapping, provider input, calculated output, approval, and downstream record',metrics:'dependencies cleared, overdue decisions, cases executed, defects by consequence, reconciled totals, and rollback readiness',lens:'Arrange the plan by dependency. Calendars depend on pay groups, holidays, funding windows, and approval times; mapping depends on authoritative fields and transformation owners. Evidence-based gates are stronger than green status opinions. Conditional acceptance must name the defect, population, workaround, risk owner, expiry, and closure proof. Preserve a reversible checkpoint near launch and rehearse the delay or rollback decision, including change capture and duplicate prevention, before schedule pressure is real.',service:'/services/operations-support',image:'/blog-heroes/payroll-cycle-closeout-review.png'},
 {slug:'payroll-data-migration-reconciliation',title:'Reconcile payroll data during a provider migration without losing history',excerpt:'Use field lineage, population controls, transformation evidence, exception ownership, and output checks to prove what moved.',subject:'data migration reconciliation',artifact:'a source-to-target reconciliation pack for every approved migration population',fields:'source, extraction timestamp, record key, definition, transformation, target, rejected row, control total, reviewer, correction version, and retention instruction',authority:'authoritative source, mapping interpretation, legal retention, acceptable variance, correction method, and migration acceptance',scenario:'the employee count matches while year-to-date taxable wages differ for transferred workers',failure:'a matching grand total hides omitted and duplicated worker values that cancel each other',test:'compare counts, identifiers, dated events, monetary lines, cohort totals, and selected histories before the aggregate',metrics:'records extracted, fields mapped, rejected rows, unmatched keys, line variances, cohort variances, and retests',lens:'Freeze and hash each extract before transformation. A later extract receives a new version instead of silently replacing history. Define effective date, transaction date, pay date, and period end because similar labels may drive different logic. Reconcile population, keys, fields, event sequence, and money at line and cohort levels before totals. Close an exception only after a corrected target is generated and compared again. If the target cannot represent a source field, record the owner’s explicit design decision rather than calling it matched.',service:'/services/reporting-and-qa',image:'/blog-heroes/payroll-record-source-register.png'},
 {slug:'payroll-parallel-run-acceptance-criteria',title:'Set payroll parallel-run acceptance criteria before comparing results',excerpt:'Define populations, expected differences, tolerances, defect severity, and retest rules before results become a go-live argument.',subject:'parallel-run acceptance',artifact:'a preapproved comparison protocol and decision pack for one representative cycle',fields:'frozen population, input version, configuration, expected result, comparison field, tolerance basis, known difference, defect owner, and retest',authority:'test scope, expected variance, defect consequence, acceptance threshold, go-live, rollback, and employee response',scenario:'most net pay matches while one material deduction error sits among small rounding differences',failure:'the project changes tolerance after seeing results so an inconvenient variance no longer fails',test:'declare exact-match fields, justified tolerances, expected differences, and stop conditions before calculating comparisons',metrics:'population coverage, exact matches, expected differences, unexplained variances, severe defects, and retest passes',lens:'Decide whether the old output is a trusted expectation or merely another calculation requiring source verification. Trace each variance from authoritative event to the first divergent transformation. Separate timing, source, mapping, calculation, configuration, and unexplained differences. Never offset positive and negative worker errors to make a reassuring total. Write the gate rule before the results meeting, and preserve who accepts any residual defect, its affected population, expiry, workaround, and production monitoring.',service:'/services/reporting-and-qa',image:'/blog-heroes/payroll-input-control-map.png'},
 {slug:'payroll-outsourcing-pricing-model-comparison',title:'Compare payroll outsourcing pricing models against the work you will buy',excerpt:'Normalize base fees, volume units, exceptions, implementation work, buyer labor, and exit costs before comparing prices.',subject:'pricing-model comparison',artifact:'a scenario cost model connected to service scope and operating assumptions',fields:'base period, billed unit, included population, minimum, implementation, integration, off-cycle event, support tier, currency, indexation, buyer work, and exit charge',authority:'forecast assumptions, negotiation, tax and accounting treatment, affordability, risk allowance, and provider selection',scenario:'one proposal charges per employee paid while another bills active workers plus off-cycle and interface fees',failure:'headline monthly fees are compared without normalizing population definitions or excluded work',test:'price the same ordinary month, peak, correction-heavy cycle, implementation, entity addition, and exit under each offer',metrics:'recurring cost, one-time cost, variable exposure, unpriced dependency, internal effort, scenario range, and open terms',lens:'Map who collects, validates, prepares, answers, corrects, approves, funds, files, and retains before comparing price. Employee, employee paid, active record, payslip, entity, payroll, interface, ticket, and hour are different units. Show provider fees and buyer work separately, using an approved range where uncertainty matters. The model is not a savings promise. It should expose proposal facts, buyer assumptions, exclusions, sensitivity, and commercial terms that require clarification before signature.',service:'/services/operations-support',image:'/blog-heroes/payroll-owner-review-packet.png'},
 {slug:'payroll-provider-exit-plan',title:'Build a payroll provider exit plan before signing the contract',excerpt:'Define export formats, access, knowledge transfer, open cases, verification, and deletion evidence while leverage exists.',subject:'provider exit planning',artifact:'an exit schedule tied to contract rights, data inventory, payroll calendar, and receiving owner',fields:'trigger, notice, export population, dictionary, format, channel, open case, archive access, credential end, knowledge owner, deletion evidence, fee, and acceptance test',authority:'contract termination, transition provider, retention interpretation, legal hold, final acceptance, and access extension',scenario:'the relationship ends while a correction, tax notice, and employee inquiry remain open across systems',failure:'the contract promises data return without fields, history depth, usable format, delivery time, or correction support',test:'request a sample export and reconstruct one worker history, one exception, and one control total',metrics:'datasets inventoried, export fields verified, open cases assigned, access removed, retained records located, and deletion attestations',lens:'Inventory master data, inputs, calculations, approvals, filings, payment references, balances, correspondence, exceptions, audit logs, configuration, and integrations. PDF may support retrieval but not migration; a database export without code meanings may be unusable. Put notice, final payroll, year-end work, filings, corrections, funding, communication, and new-provider testing on one calendar. Accept the exit only after reconciling counts and totals, tracing histories, verifying attachments, correcting defects, and assigning every open obligation.',service:'/services/operations-support',image:'/blog-heroes/payroll-access-exit-register.png'},
 {slug:'payroll-multi-country-vs-local-provider',title:'Choose between multi-country and local payroll providers with operating scenarios',excerpt:'Compare governance, local ownership, data flow, funding, support, consolidation, continuity, and exit instead of country counts.',subject:'multi-country versus local provider selection',artifact:'a country operating model and comparable scenario record',fields:'entity, population, local owner, adviser, provider role, data route, currency, funding owner, cutoff, language, consolidation definition, exception route, and exit dependency',authority:'provider architecture, local interpretation, contracting entity, treasury model, data-transfer risk, and selection',scenario:'a global provider offers one portal but relies on an unnamed in-country calculation partner',failure:'a common dashboard earns integration credit without testing who corrects a local filing',test:'walk the same hire, retroactive change, correction, funding issue, and year-end request through each priority country',metrics:'owner handoffs, systems crossed, manual transformations, local dependencies, response paths, and transition risks',lens:'Start with actual employing entities, populations, calendars, currencies, funding routes, systems, statutory owners, and exceptions. Make subcontractors visible. One portal may still hide several engines; local providers may still support a coherent common control model. Inspect consolidated field definitions because gross, cost, headcount, and effective date can differ across countries. Include the response to a partner change, country-level exit, platform outage, and loss of history. Name the internal governance burden honestly under either architecture.',service:'/services/operations-support',image:'/blog-heroes/payroll-input-ownership-map.png'},
 {slug:'payroll-in-house-vs-outsourced-payroll',title:'Decide between in-house and outsourced payroll by mapping real work',excerpt:'Compare recurring preparation, specialist decisions, systems, controls, continuity, retained authority, and change.',subject:'in-house versus outsourced payroll',artifact:'a task-and-authority map with cost, capacity, risk, and transition scenarios',fields:'task, frequency, volume, skill, system, access, preparer, reviewer, decision owner, backup, cutoff consequence, evidence, current effort, and destination',authority:'operating model, retained authority, staffing, provider selection, budget, transition timing, and risk acceptance',scenario:'a small internal team owns preparation, provider coordination, employee support, reporting, and specialist questions with no trained backup',failure:'the analysis labels the whole function in-house or outsourced and misses retained work',test:'map one ordinary and one correction-heavy cycle, assigning every preparation, review, decision, and verification step',metrics:'recurring work, peak capacity, owner time, specialist dependencies, failure points, system cost, provider fees, and transition effort',lens:'Break payroll into collection, validation, calculation, investigation, approval, funding, support, filing, reporting, access review, and correction. Neither model is self-contained. Measure an ordinary cycle and a difficult cycle that combines late inputs, an owner absence, and an approaching cutoff. A hybrid can be deliberate: support may chase approved inputs and reconcile fields while company owners retain policy, treasury, tax, legal, employment, and release authority. Pilot one narrow lane before expanding it.',service:'/services/operations-support',image:'/blog-heroes/aug21-payroll-work-queue-owner-matrix.png'},
 {slug:'payroll-provider-security-due-diligence',title:'Run payroll provider security due diligence through evidence and scenarios',excerpt:'Connect assurance reports to data flows, access, incidents, subcontractors, retention, continuity, and exit.',subject:'provider security due diligence',artifact:'a risk-and-evidence register tied to the proposed payroll workflow',fields:'data category, purpose, system, transfer, storage, role, authentication, privileged access, log, retention, subprocessor, incident duty, continuity control, evidence date, and owner',authority:'security risk acceptance, contract terms, transfer basis, retention, incident response, provider approval, and access authorization',scenario:'a current assurance report exists but the proposed workflow sends payroll exports through an unmanaged mailbox',failure:'policy documents are collected without comparison to the actual implementation and support path',test:'trace a sensitive change, privileged request, incident, restoration, user departure, and exit through controls',metrics:'evidence received, scope gaps, workflow exceptions, risky access, unresolved subprocessors, remediation, and evidence expiry',lens:'Map personal, payroll, bank, tax, benefit, identity, and employment data before sending a questionnaire. Record why it moves, who sees it, where it resides, and when it should be removed. Assurance may cover only part of a service or an earlier period. Test user approval, privileged support, bank-change verification, logging, termination, outage, backup, subprocessor notice, and secure exit. Distinguish missing evidence, design gaps, implementation exceptions, contract ambiguity, and accepted residual risk.',service:'/services/admin-support',image:'/blog-heroes/payroll-sensitive-request-verification.png'},
 {slug:'payroll-business-continuity-test',title:'Test payroll business continuity before an outage makes the decisions',excerpt:'Exercise people, data, access, provider, funding, communication, and recovery against a real payroll deadline.',subject:'payroll business continuity',artifact:'a timed tabletop and recovery record linked to one payroll calendar',fields:'scenario, service, start, detection, deadline, minimum output, data version, alternate access, decision owner, backup, provider contact, funding dependency, communication rule, and recovery evidence',authority:'continuity priority, emergency authority, workaround, delayed processing, employee communication, restoration acceptance, and return to normal',scenario:'the payroll platform is unavailable on cutoff morning while the primary approver cannot be reached',failure:'the plan lists contacts and backups but never tests access, data freshness, authority, or minimum payroll',test:'run a no-notice tabletop with current roles and protected synthetic records, requiring the evidence participants would use',metrics:'detection, owner contact, accessible dependencies, recovery point, decisions, workaround gaps, verification, and overdue actions',lens:'Choose a scenario that removes a real dependency rather than discussing a generic outage. State the last known good data, cutoff, minimum outcome, and actions that cannot bypass authority. Ask the backup to locate calendars, queues, contacts, approvals, funding dependencies, and restoration instructions. Recovery continues after the system returns: reconcile changes, find duplicates and omissions, verify output, remove temporary access, and obtain owner acceptance. Every lesson needs an owner, due date, evidence, and retest condition.',service:'/services/operations-support',image:'/blog-heroes/aug21-repair-payroll-absence-continuity-runbook.png'},
 {slug:'payroll-error-responsibility-matrix',title:'Assign responsibility for payroll errors without losing the correction path',excerpt:'Separate source, preparation, decision, processing, detection, correction, communication, and prevention responsibilities.',subject:'payroll error responsibility',artifact:'an event-based responsibility matrix connected to correction evidence and service terms',fields:'error type, source, detection, preparer, decision owner, processor, approver, employee contact, funding owner, filing owner, root-cause owner, deadline, evidence, escalation, and closure test',authority:'employee entitlement, legal or tax response, correction amount and timing, funding, filing amendment, communication, liability, and prevention investment',scenario:'a correct manager change reaches the provider after cutoff and creates an incorrect payment',failure:'every party is responsible for accuracy while nobody owns the next action, deadline, or verified outcome',test:'walk source, mapping, calculation, approval, payment, filing, and communication errors through the matrix',metrics:'errors by first failure point, detection time, owner wait, correction completion, reopened cases, repeated causes, and prevention',lens:'Define responsibility by event. A pay-rate error can begin with an unauthorized source, missed cutoff, mapping defect, calculation problem, approval failure, or unchecked output. Immediate employee recovery and later root-cause work need separate owners. Preserve the original event, approved correction, provider response, communication, and fresh output rather than editing history. Operational next action, commercial liability, and statutory liability are separate questions. Test urgent underpayment, wrong destination, duplicate payment, missing deduction, tax-field error, filing notice, and privacy incident.',service:'/services/reporting-and-qa',image:'/blog-heroes/payroll-exception-root-cause-review.png'},
] as const;

function evidenceDrill(t:T){
 const items=t.fields.split(', ');
 const paragraphs=items.map((item,index)=>{
  const actions=[
   `Document ${item} inside ${t.artifact}; preserve the source for ${item}, the person who supplied it, the observation time, and the owner who can resolve a conflict.`,
   `For ${t.subject}, test ${item} against a current protected record. Mark whether ${item} is confirmed, missing, stale, contradictory, assumed, or waiting for an authorized decision.`,
   `Trace ${item} through the proposed workflow for ${t.subject}. Show where ${item} enters, who may change it, which validation applies, and what output proves the approved value survived.`,
   `Give ${item} a named acceptance check in ${t.artifact}. A reviewer should reproduce the check without relying on oral history, a private spreadsheet, or access beyond the declared role.`,
  ];
  return actions[index%actions.length];
 });
 return {heading:`Inspect the ${t.subject} evidence field by field`,paragraphs:[paragraphs.slice(0,Math.ceil(paragraphs.length/2)).join(' '),paragraphs.slice(Math.ceil(paragraphs.length/2)).join(' ')]};
}
function measurementDrill(t:T){
 const items=t.metrics.split(', ');
 return {heading:`Read the ${t.subject} measures without hiding exceptions`,paragraphs:items.map((item,index)=>`Measure ${item} for the declared ${t.subject} population and period. Record the numerator, denominator, exclusions, source system, observation time, and owner for ${item}. ${index%2===0?'Inspect the underlying cases before treating the result as a trend or provider comparison.':'Keep owner-wait time and unresolved evidence visible instead of removing them to improve the result.'}`)};
}
function correctedPairAnalysis(t:T){
 if(t.slug==='payroll-outsourcing-rfp-scorecard') return {heading:'Challenge an RFP score with contrary evidence',paragraphs:[`Take the highest-scoring finalist and find the three ratings most likely to change the decision. For each one, write the evidence that earned the score and a contrary case that would lower it. A provider may demonstrate a clean standard approval while giving no evidence for a rejected file, absent owner, revised input, or compromised communication channel. Ask the provider to work the contrary case, then update the rating and citation without changing the rubric. This check reveals where presentation quality or reviewer optimism entered the result.`,`Run the same challenge against the lowest-cost finalist and the preferred operational finalist. Compare mandatory failures separately from weighted differences. Record remediation proposed after the bid, who would pay for it, whether it must be complete before access, and how the buyer would verify completion. The selection note should show why evidence changed a score and which conditions survive into contracting and implementation.`]};
 if(t.slug==='payroll-multi-country-vs-local-provider') return {heading:'Map a cross-border exception without a global shortcut',paragraphs:[`Choose a worker transfer between two employing entities and draw both country workflows on the same timeline. Show the last payroll in the first country, first payroll in the second, overlapping benefits or deductions, local owner decisions, currency and funding routes, year-to-date treatment, access changes, and consolidated reporting. A global portal may display both records while leaving the transition to separate local teams. A local-provider model may expose the separation more clearly but require the buyer to coordinate it.`,`Next remove one in-country partner from the scenario. Identify who holds the historical data, current configuration, filing evidence, employee contacts, and authority to appoint a replacement. Test whether the central contract supplies continuity or only forwards the problem. Compare that result with the buyer's local contracts, notice rights, and internal backup. This exercise gives country coverage an operational meaning instead of treating a map or logo list as proof of resilience.`]};
 if(t.slug==='payroll-outsourcing-implementation-timeline') return {heading:'Calculate the last responsible launch decision',paragraphs:[`Place the provider configuration freeze, final source extract, access activation, funding rehearsal, user training, employee communication, and first live cutoff on one clock. For each dependency, record the latest time an authorized owner can reject it without creating an uncontrolled workaround. The last responsible go-live decision is the earliest irreversible boundary among those dependencies, not the date printed on the project slide. If a required owner will be unavailable, move the review earlier or name a qualified backup. Do not solve the absence by treating project management approval as payroll, security, treasury, or legal authority.`,`Model a reduced-scope launch separately from a full delay. A smaller population may reduce some exposure but can create duplicate data entry, split support routes, inconsistent year-to-date records, and unclear ownership between old and new processes. List those consequences before calling reduced scope safer. The sponsor should see the exact records and services that remain in each system, how changes are synchronized, who answers employees, and what evidence permits later migration. This calculation turns a vague contingency into a reviewable operating choice.`]};
 if(t.slug==='payroll-parallel-run-acceptance-criteria') return {heading:'Adjudicate a mixed parallel-run result',paragraphs:[`Build the decision pack around each variance class rather than one match percentage. Suppose a display label differs for every worker, approved rounding affects a defined earning code, three records used stale source data, and one deduction calculation is materially wrong. The label may need no payroll correction, the rounding needs policy-backed tolerance evidence, the stale records require a fresh source and rerun, and the deduction defect may stop the gate. Counting all lines together would blur those different consequences. Record the population, source, first divergence, owner, correction, and retest for every class.`,`Retest the changed logic against the original failing cases and a nearby set of ordinary cases. A repaired deduction formula can correct the reported worker while introducing a problem for workers with a different limit, effective date, or negative adjustment. Preserve the configuration version and expected result for both sets. Acceptance applies to the tested version only; a later mapping or configuration change reopens the relevant evidence. This prevents a clean rerun from becoming permanent approval for an evolving system.`]};
 return null;
}
function ownerExercise(t:T){return {heading:`Run an owner exercise for ${t.subject}`,paragraphs:[`Give the declared ${t.subject} owner this situation without a recommended answer: ${t.scenario}. Ask the owner to identify the authoritative record, immediate decision, prohibited shortcut, last reversible time, backup authority, and evidence that would close the event. Compare that response with ${t.artifact}. Any missing field becomes a specific design action rather than a general request for better communication. Preserve the owner's reasoning beside the scenario so a later reviewer can tell whether the operating rule changed or the facts were different.`,`Now introduce the known failure mode: ${t.failure}. Ask the preparer to stop at the first point where written authority or current evidence is absent. Then apply ${t.test}. The exercise should produce an exception owner, next action, due time, protected source link, and observable acceptance check. Review ${t.metrics} after the exercise, but keep individual high-consequence cases visible even when the aggregate looks acceptable.`]};}
function sharedSections(t:T){return[
 {heading:`Start the ${t.subject} review with a bounded decision`,paragraphs:[`${t.excerpt} The working output is ${t.artifact}. Name the entities, worker populations, payroll periods, systems, currencies, deadlines, and owners inside scope. Put exclusions beside the scope. A Philippines-based support specialist can collect records, maintain the comparison, and chase approved follow-ups. The specialist must stop when the work requires ${t.authority}.`,`Capture ${t.fields}. Keep protected details in approved systems and use masked references in coordination views. Label every item as a source fact, provider statement, buyer assumption, calculation, owner decision, or observed result. A copied value without a source, a date without a time zone, and an approval without scope remain gaps.`]},
 {heading:'Use a scenario that exposes the handoffs',paragraphs:[`Test this event: ${t.scenario}. Before discussing a solution, write the expected source, preparer, reviewer, decision owner, backup, deadline, escalation, system record, and output check. Repeat the exercise with an ordinary event. The contrast shows whether the operating model works every cycle or depends on improvised attention during an emergency.`,`Watch for this failure: ${t.failure}. Record what is missing and who can supply it. Do not reward a workaround that uses personal memory, shared credentials, an unverified message, or authority the preparer does not hold. A successful walkthrough is evidence about the proposed workflow, not a guarantee of future accuracy.`]},
 {heading:'Make the topic-specific comparison',paragraphs:[t.lens,`Apply this reproducible test: ${t.test}. Preserve the source version, observation time, participant role, output, exception, and follow-up. Ask for records that match the proposed service instead of generic marketing material. When evidence is confidential, note its scope, date, authorized reviewer, and conclusion without copying protected contents into a broad project file.`]},
 evidenceDrill(t),
 {heading:'Separate evidence from consequential decisions',paragraphs:[`Payroll support may organize facts, apply an approved comparison, maintain statuses, and prepare questions. It must not silently convert ambiguity into a company instruction. Decisions about ${t.authority} stay with named client owners and qualified advisers. If several functions participate, split the questions so payroll, HR, finance, treasury, tax, legal, privacy, security, and the provider accept only the portions within their authority.`,`Use authoritative sources for changeable recordkeeping, tax, privacy, and security statements. The IRS employer guide, Department of Labor recordkeeping summary, NIST control guidance, and Philippine privacy law support their respective subjects, but none replaces advice for the buyer's jurisdiction, workforce, contract, or facts. State an unresolved interpretation plainly and route it to its owner.`]},
 {heading:'Build a decision record another reviewer can follow',paragraphs:[`The record should connect the original question, approved scope, sources, comparison method, exceptions, owner responses, and current result. Preserve rejected or superseded versions rather than rewriting the path after correction. Use statuses that name the next action, such as missing source, conflicting evidence, owner decision required, access blocked, provider response due, retest required, or output unverified.`,`A decision-ready summary leads with the choice required, affected population, deadline, last confirmed state, material conflicts, assumptions, evidence links, and consequence of no response. Separate mandatory conditions from desirable improvements. The owner should be able to accept, reject, condition, or escalate without reconstructing the case from meetings and private messages.`]},
 {heading:'Protect payroll data throughout the review',paragraphs:[`Store payroll, tax, identity, banking, benefit, and employment records only in approved systems. A coordination view usually needs a case reference, masked population, period, status, owner, due time, and protected link. Do not move full exports into chat or private spreadsheets merely because the approved repository takes longer to open.`,`Use named accounts, multifactor authentication where available, and access limited to the task and population. Review permissions after the first cycle and remove what was not used. Unexpected payment instructions, identity documents, executable files, or urgent requests from an unverified sender belong in the company's verification or security process. A cutoff never makes an unsafe channel acceptable.`]},
 {heading:'Pilot one complete cycle before expanding',paragraphs:[`Define one representative population, period, source set, expected output, reviewer, stop conditions, and rollback or exit path. Set an overlap window and time zone between the Philippines-based support lane and the client owner. Include at least one ordinary case, one late or incomplete case, and one high-consequence exception. Keep the pilot small enough that the owner can inspect every handoff.`,`Track ${t.metrics}. These counts and times describe workflow performance; they do not prove payroll correctness, legal compliance, savings, or employee outcomes. At closeout, examine every consequential exception, remove unused access, keep unresolved items with owners and dates, and decide whether the evidence supports expansion, correction, negotiation, or a stop.`]},
 measurementDrill(t),
 ...(correctedPairAnalysis(t)?[correctedPairAnalysis(t)!]:[]),
 ownerExercise(t),
 {heading:'Turn the finding into an accountable handoff',paragraphs:[`For Outsource Payroll Company, the practical boundary is preparation and evidence coordination. The support lane can maintain the register, compare approved fields, prepare follow-ups, and package exceptions for review. The client retains consequential decisions and final payroll authority. That division should appear in the working instructions, responsibility map, access design, and owner review.`,`Bring one redacted example, the current cutoff calendar, source systems, and owner map to a scoping call. Those materials are enough to design a checked first cycle around ${t.artifact}. Expansion should follow an observable successful handoff, not a broad promise that all payroll work can move at once.`]},
]}
function sections(t:T){
 const all=sharedSections(t);
 if(!t.independent)return all;
 const candidates=all.filter(section=>!section.heading.startsWith(`Inspect the ${t.subject}`)&&![
  'Separate evidence from consequential decisions',
  'Build a decision record another reviewer can follow',
  'Protect payroll data throughout the review',
  'Pilot one complete cycle before expanding',
  'Turn the finding into an accountable handoff',
 ].includes(section.heading));
 const seed=[...t.slug].reduce((sum,char)=>sum+char.charCodeAt(0),0);
 const offset=seed%candidates.length;
 const rotated=[...candidates.slice(offset),...candidates.slice(0,offset)];
 return seed%2?rotated.reverse():rotated;
}
export function buildDecisionBlogBatch(batchTopics:readonly DecisionTopic[],date:string,marker:string){
 const posts=batchTopics.map((t,batchIndex)=>({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:14,published:date,batchIndex}));
 const details=Object.fromEntries(batchTopics.map((t,index)=>[t.slug,{takeaways:[`Define the ${t.subject} scope, evidence, and owners before comparison.`,`Use ${t.artifact} instead of general claims.`,'Pilot one bounded cycle before expanding the handoff.'],readinessRows:[{area:'Scope',ready:'Population, period, systems, deadline, and exclusions are written.',ownerCheck:'Confirm the decision and authority.'},{area:'Evidence',ready:'Facts, claims, assumptions, and observations remain distinct.',ownerCheck:'Resolve conflicts.'},{area:'Access',ready:'Named access is limited to the task.',ownerCheck:'Approve removal date.'},{area:'Decision',ready:'Consequential questions have owners.',ownerCheck:'Record the decision.'}],sections:sections(t),roleBrief:[`Routine: ${t.title}`,`Output: ${t.artifact}`,'Access: named, least-privilege accounts','Approval: authorized client owners','Stop: unclear source, identity, channel, scope, or authority'],faqs:[{question:`Who owns ${t.subject}?`,answer:`Support prepares ${t.artifact}; authorized client owners retain ${t.authority}.`},{question:'What should the first pilot include?',answer:`Use one representative cycle including ${t.scenario}.`},{question:'How is progress reviewed?',answer:`Track ${t.metrics}, then verify consequential exceptions with their owners.`}],sources:decisionSources,rich:{keyword:t.subject,marker:`${marker}-${t.slug}`,published:date,image:t.image,directAnswer:[t.excerpt,`Base the decision on ${t.artifact} and keep consequential authority with the client.`],stats:[],quote:{text:'There is no implicit trust granted to assets or user accounts based solely on their physical or network location.',attribution:'NIST SP 800-207',url:'https://csrc.nist.gov/pubs/sp/800/207/final'},chart:{title:`A controlled ${t.subject} review`,description:'Scope, evidence, owner decision, pilot, and verified handoff.',methods:'Process illustration, not a measured result.'},graphic:{title:t.title,description:'A bounded path from buyer question to accountable decision.',steps:['Scope','Evidence','Decide','Pilot']},banners:[{eyebrow:'Plan one payroll support lane',heading:'Turn the decision into a checked first cycle',text:'Bring a redacted example, cutoff, systems, and owner map.',href:'/contact',label:'Plan payroll support'}],internalLinks:[{href:serviceRoute(t.service),label:'Relevant payroll support service'},{href:'/services/payroll-reporting',label:'Payroll reporting support'},{href:'/contact',label:'Plan payroll support'}]},publication:{internalLinks:[serviceRoute(t.service),'/services/payroll-reporting','/contact'],externalLink:decisionSources[index%decisionSources.length].url,related:batchTopics.filter((_,i)=>i!==index).slice(0,2).map(x=>x.slug)}}]));
 return {posts,details};
}
const september28Batch=buildDecisionBlogBatch(topics,DATE,'opc-20260928');
export const september28BlogPosts=september28Batch.posts;
export const september28BlogDetails=september28Batch.details;
