import { sectionsFor, type ResearchStudyFrame } from './september22-research';

const DATE = '2026-10-02';
const sources = [
  { label: "Internal Revenue Service — Publication 15 (2026), Employer's Tax Guide (checked October 2, 2026)", url: 'https://www.irs.gov/publications/p15' },
  { label: 'U.S. Department of Labor — Fact Sheet #21: Recordkeeping Requirements under the FLSA (checked October 2, 2026)', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { label: 'NIST — SP 800-53 Rev. 5, Security and Privacy Controls (checked October 2, 2026)', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
  { label: 'Philippine National Privacy Commission — Data Privacy Act of 2012 (checked October 2, 2026)', url: 'https://privacy.gov.ph/data-privacy-act/' },
] as const;

type Study = ResearchStudyFrame & { uniqueSections: readonly { heading: string; body: string }[] };

const studies: readonly Study[] = [
  {
    slug: 'payroll-calendar-compression-readiness-study', title: 'Payroll calendar compression readiness study',
    question: 'When holidays, year-end work, or provider closures shorten a payroll cycle, can the owner see which inputs, reviews, and decisions lost usable time before choosing a safe response?',
    subject: 'compressed payroll calendar readiness', unit: 'one payroll cycle whose usable preparation or review window is shorter than the ordinary approved calendar',
    states: 'ordinary window retained, earlier cutoff accepted, review capacity reassigned, approved scope reduced, contingency invoked, unresolved dependency, or deadline missed',
    service: '/services/payroll-preparation', cta: 'Review payroll preparation support',
    decision: 'whether a preparation lane can make calendar pressure visible early enough for an owner to change timing, staffing, or scope without treating urgency as approval',
    evidence: 'entity, pay group, period, source-zone cutoff, provider closure, banking day, input-ready event, reviewer availability, decision deadline, contingency owner, exception disposition, and output confirmation',
    image: '/research-heroes/philippines-payroll-deadline-review-slack-study.png',
    uniqueSections: [
      { heading: 'Measure usable time rather than nominal days', body: 'A calendar may show the same number of dates as an ordinary cycle while offering far less usable review time. A local holiday can delay an input owner, a provider may close before the employer, or a banking window may end several hours before the payroll platform cutoff. Build the study from events, not colored calendar cells. Preserve every deadline in its source time zone and record when the required evidence actually became complete. Then calculate preparation time, waiting time, owner-review time, and contingency time separately. Do not call an input late merely because it arrived after an internal target if the approved source deadline was different. Equally, do not call a cycle ready because a file existed while material questions were still open. This framing lets support identify where capacity disappeared without deciding that a deadline should be waived or that incomplete payroll should proceed.' },
      { heading: 'Construct a dependency path for each cycle', body: 'List the events that must occur before release: source population freeze, approved changes, preparation, variance review, owner decisions, provider upload, provider acceptance, funding preparation, and output confirmation. Mark which can run in parallel and which genuinely block the next step. For every dependency, name a primary owner, backup, evidence of completion, and latest useful handoff time. A reminder is not completion evidence, and an acknowledged message is not an accepted payroll input. Compare the compressed path with at least one ordinary cycle using the same definitions. The comparison should reveal whether the problem is fewer working hours, a shifted provider cutoff, unavailable authority, unusually high exceptions, or an avoidable serial handoff. Keep those mechanisms distinct because they imply different remedies. Administrative support can maintain the path and escalate approaching gates; authorized owners choose revised cutoffs, staffing, scope, or release decisions.' },
      { heading: 'Test contingencies before the short window', body: 'A contingency that exists only in a policy document may fail when used. Before the compressed cycle, run a tabletop case with a missing approver, a rejected provider file, a late high-impact input, and an unavailable transmission account. Verify that the backup can reach the source records through named access, understands the authority limit, and can produce the required acceptance evidence. Do not share credentials or broaden permanent access for the exercise. Record how the workflow distinguishes an approved earlier cutoff from a silent omission, and how a deferred item is carried into the next authorized action. The test should also expose false flexibility: tasks that appear movable but depend on a provider, bank, or system window outside the team’s control. A successful exercise proves only that the declared route was observable on the test date. It does not guarantee a future deadline or authorize the backup to resolve pay, tax, banking, or employment questions.' },
      { heading: 'Interpret readiness without rewarding unsafe speed', body: 'Report the distribution of usable review hours, dependencies completed by their latest useful handoff, unresolved items at each gate, contingency activations, and output confirmations. Pair speed with evidence quality. A fast cycle with missing source links is not more ready than a slower cycle in which the owner deliberately stopped an ambiguous item. Avoid a single red-amber-green score that hides which deadline, population, or authority is at risk. Instead, publish the affected cycle, remaining decision, responsible owner, consequence of waiting, and next evidence check. Look for recurring pressure at the same interface across multiple periods before recommending a process change. An earlier internal cutoff may create more review time, but it can also shift burden upstream or increase corrections. Treat that as a hypothesis to test. The study supports a buyer deciding whether structured preparation and escalation help; it does not promise that outsourced support can overcome an immovable external deadline.' },
    ],
  },
  {
    slug: 'payroll-self-service-change-audit-study', title: 'Payroll self-service change audit study',
    question: 'Can employee self-service changes be traced from authenticated request through field-level review, effective date, approval rule, payroll import, and confirmed output?',
    subject: 'employee self-service payroll changes', unit: 'one self-service event expected to alter a payroll-relevant field for a defined period',
    states: 'authorized and confirmed, awaiting required review, effective-date conflict, field outside self-service scope, duplicate or replayed event, output mismatch, or unresolved',
    service: '/services/payroll-data-entry', cta: 'Review payroll data-entry support',
    decision: 'whether administrative support can monitor self-service change evidence and prepare exceptions without impersonating users, approving sensitive changes, or deciding the meaning of disputed records',
    evidence: 'protected worker identifier, event identifier, field class, prior-value hash, submitted-value hash, request time, authentication result reference, effective date, approval rule, import batch, output field, and disposition',
    image: '/research-heroes/philippines-payroll-source-output-bridge-study.png',
    uniqueSections: [
      { heading: 'Separate employee entry from effective authority', body: 'A portal submission is evidence that a recorded account entered data; it is not automatically evidence that every requested field may take effect. Some organizations allow contact details to flow directly while routing bank, tax, identity, status, or deduction changes through added verification. Document that field-class rule before sampling events. The research record should use protected identifiers and hashes rather than copying old and new sensitive values. Capture the authenticated session or verification outcome by reference, not the credentials or secret factors themselves. Where another system is authoritative, preserve its decision reference and effective date. A support specialist may compare the event with the written rule, identify missing review, and route the case. The specialist must not impersonate the employee, infer identity from a familiar email, or decide that a sensitive change is genuine because it looks plausible. Those boundaries make the audit useful without turning it into a second ungoverned store of payroll data.' },
      { heading: 'Follow the event across technical boundaries', body: 'Assign one durable event identifier at intake and carry it through middleware, approval, import, provider processing, and payroll output. Record batch identifiers and transformation versions where the same field name changes between systems. Test whether a correction creates a linked event or silently overwrites history. A current-state screen cannot prove what was submitted before cutoff, so use event logs or versioned exports when the approved systems provide them. Compare the intended effective period with the period used by payroll; a valid change can still land in the wrong run. Search for duplicates caused by retries, integration replay, or a user submitting through two channels. When identifiers cannot be joined, classify the event as unresolved instead of matching on name alone. The objective is a reproducible lineage, not a claim that every technical success represents an authorized business decision.' },
      { heading: 'Design tests around risk and privacy', body: 'Freeze a prospective population of payroll-relevant self-service events and stratify it by field class, processing route, and required review. Include every high-risk field under a declared rule and use a reproducible sample for ordinary changes if volume is large. Seed only synthetic test records; never alter a real employee record to see whether a control catches it. Measure missing approvals, effective-date conflicts, unmatched outputs, replayed events, and time from complete evidence to disposition. Reviewers should see only the minimum fields needed for classification. The privacy owner determines lawful access and retention, while the study records that decision rather than inventing one. If the portal does not retain prior values, document that limitation and test whether an authorized audit log supplies equivalent evidence. Do not infer a clean history from the absence of visible changes on the current profile.' },
      { heading: 'Use findings to define a monitorable support lane', body: 'Translate results into a queue that distinguishes routine observable events from authority questions. Support can check completeness, preserve event links, compare effective periods, reconcile batch membership, and prepare a concise exception packet. It should stop at identity disputes, unusual channel changes, conflicting authoritative sources, or fields reserved for an owner. Report event counts and state distributions by field class without exposing individual values. A high match rate shows that the declared records usually connect; it does not prove identity, statutory compliance, or the correctness of every underlying choice. A low match rate may indicate logging gaps, integration design, unclear field ownership, or inconsistent approval rules. Test those explanations before recommending more manual review. The buyer decision is whether a bounded monitoring lane improves visibility and response, not whether support should receive broader access to compensate for weak system evidence.' },
    ],
  },
  {
    slug: 'payroll-off-cycle-payment-authorization-study', title: 'Payroll off-cycle payment authorization study',
    question: 'For an urgent off-cycle payment, can the organization bind the reason, population, calculation source, approval scope, funding instruction, provider result, and later reconciliation to one case?',
    subject: 'off-cycle payment authorization', unit: 'one request for payroll-related payment outside the ordinary approved cycle',
    states: 'authorized and reconciled, authority incomplete, ordinary-cycle duplicate risk, calculation source unresolved, funding evidence detached, provider result unconfirmed, or unresolved',
    service: '/services/payroll-preparation', cta: 'Review payroll preparation support',
    decision: 'whether a support lane can assemble urgent case evidence and track completion without deciding entitlement, calculating disputed pay, moving funds, or treating urgency as authority',
    evidence: 'case identifier, reason class, affected entity and period, protected population, calculation owner, approved amount reference, approval scope, provider request, funding reference, output confirmation, and ordinary-cycle reconciliation',
    image: '/research-heroes/philippines-payroll-approval-authority-boundary-research.png',
    uniqueSections: [
      { heading: 'Define an off-cycle case before acting', body: 'Off-cycle work compresses review and often arrives through escalation channels, which makes an explicit case boundary essential. Record why the request cannot wait for the ordinary cycle, the affected entity and period, the protected population, and the owner who determined the amount or treatment. Distinguish a correction, missed input, rejected payment, advance, statutory response, and discretionary payment because their sources and later reconciliation differ. The protocol does not judge whether the reason is legally sufficient or calculate what a person is owed. It asks whether the approved decision is attached to the exact case that support prepares. A message marked urgent is not approval, and a prior approval is not portable to a different amount or population. Support may open the register, collect source references, and surface missing fields; it must stop when authority or calculation ownership is unclear.' },
      { heading: 'Bind preparation, funding, and provider evidence', body: 'Create a versioned case packet whose identifier appears on the approved calculation, provider instruction, funding request, and returned output. Preserve content hashes or controlled repository links so later edits cannot be mistaken for the reviewed version. Record currency, payment rail, requested date, provider cutoff, and destination reference without copying full account data into the analysis. Separate technical receipt, provider acceptance, funding availability, payment processing, and observable output. None of those states alone proves all the others. If a rejected file is corrected, retain both versions and the rejection reason. If an amount changes, require evidence that the authorized owner reviewed the revised case rather than assuming approval of the first amount extends to the second. This linkage helps a second reviewer reconstruct the event while keeping authentication and fund release with the designated account owner.' },
      { heading: 'Reconcile the next ordinary cycle', body: 'An off-cycle case is not closed when a provider reports processing. Determine in advance how the next ordinary payroll should reflect the event: excluded from ordinary payment, shown as a prior payment, reversed, taxed, or otherwise treated under an owner-approved rule. The study records the rule and checks the observable result; it does not choose the treatment. Compare the off-cycle population with the next eligible ordinary population using stable identifiers, periods, earning or deduction codes, and case references. Search for full duplicates, partial duplicates, failed payments that were resubmitted, and corrections that lost their original link. Preserve unexplained differences as open cases. This forward reconciliation is especially important because a rapid payment can solve an immediate problem while creating a later duplicate or reporting mismatch if its lineage ends at the bank or provider receipt.' },
      { heading: 'Assess urgency without normalizing exceptions', body: 'Publish counts by reason, evidence state, elapsed stage, repeat source, and next-cycle reconciliation result. Separate time waiting for an owner from active administrative preparation. A faster completion time is not favorable when it reflects bypassed review, and a stopped case may be the correct control outcome. Examine repeated off-cycle reasons across several periods: recurring missed inputs may support an intake change, while repeated provider rejection may support earlier validation. Do not infer individual fault or recommend a universal turnaround promise from a small case series. Record privacy limitations and inaccessible banking evidence accurately. The operational inference should identify which steps a support team can reliably prepare and which decisions must remain outside its lane. Any expansion should follow a representative pilot that includes at least one correction and one deliberately stopped synthetic scenario.' },
    ],
  },
  {
    slug: 'payroll-benefit-deduction-interface-study', title: 'Payroll benefit deduction interface study',
    question: 'Can each benefit deduction change be traced from an owner-approved enrollment or eligibility source through effective period, payroll code, arrears rule, output, and carrier or ledger reconciliation?',
    subject: 'benefit deduction interfaces', unit: 'one deduction event expected to start, change, pause, refund, or stop in a defined payroll period',
    states: 'source-to-output matched, effective-period mismatch, code or amount conflict, arrears decision pending, duplicate deduction, downstream reconciliation missing, or unresolved',
    service: '/services/benefits-administration', cta: 'Review benefits administration support',
    decision: 'whether benefits administration support can prepare and reconcile deduction records while plan, eligibility, tax, refund, and arrears decisions remain with authorized owners',
    evidence: 'protected participant identifier, plan and coverage reference, approved event, effective date, deduction code, amount source, frequency, arrears instruction, payroll period, output amount, downstream comparison, and disposition owner',
    image: '/research-heroes/philippines-payroll-correction-lineage-review.png',
    uniqueSections: [
      { heading: 'Map the interface without interpreting the plan', body: 'Benefit deductions cross several ownership boundaries. An enrollment platform may establish a coverage event, a benefits owner may approve eligibility or cost allocation, payroll may apply a code and frequency, and a carrier or ledger may later show a different period basis. Map those sources before comparing amounts. Record the effective date and the meaning of that date in each system; enrollment, coverage, deduction, and remittance dates are not interchangeable. Support can assemble the records and apply a written mapping, but it should not interpret plan terms, decide eligibility, choose tax treatment, or invent an arrears policy. When source records conflict, keep both references and route a specific question to the named owner. Avoid copying health details into the research file. The analysis usually needs a protected participant identifier, plan reference, event type, dates, codes, amounts, and decision evidence—not diagnosis or dependent documents.' },
      { heading: 'Reconcile events before aggregate totals', body: 'Start with event-level matching. Confirm that each approved start, change, pause, refund, or stop has a corresponding payroll action for the intended period. Then compare cohort counts by plan, entity, frequency, and event type, followed by value totals. Equal aggregate deductions can hide one omitted participant and one duplicated participant, so totals are a final control rather than the first test. Record legitimate differences such as timing offsets, employer-only amounts, capped contributions, and owner-approved arrears, but require a source for each explanation. Keep refunds and reversals linked to the original event instead of netting them away. Where payroll and benefit systems use different identifiers, document the authorized crosswalk and version. A name-only match remains a review cue, not conclusive evidence.' },
      { heading: 'Test difficult timing patterns prospectively', body: 'Include new enrollments near cutoff, retroactive eligibility changes, unpaid leave, insufficient net pay, termination, rehire, frequency changes, and a correction after remittance. Declare expected evidence and owner decisions before observing outcomes. For insufficient pay or arrears, the protocol records the approved rule and its application; it does not decide whether to collect, defer, waive, or refund an amount. Preserve the original scheduled deduction, actual payroll result, later recovery or refund, and downstream reconciliation as separate events. Check whether a correction in one system reaches the others or creates an orphaned difference. Use synthetic records for destructive tests and ordinary real records only within approved access. This design reveals whether the interface can represent exceptional states without asking administrative support to make benefit or employment decisions.' },
      { heading: 'Frame conclusions for a bounded administration lane', body: 'Report matched events, mismatches by mechanism, unresolved owner decisions, time to correction, next-period carryover, and independently reviewed classifications. A clean payroll output does not prove carrier acceptance, and a carrier total does not prove each payroll deduction was appropriate. State exactly which endpoints were observed. If mismatches cluster around one event type, test the mapping, cutoff, or ownership rule before concluding that more staff are needed. Support can maintain the bridge, prepare exception packets, and verify owner-approved changes against output. It should stop when plan meaning, eligibility, tax, refund, or arrears authority is missing. The buyer can use the findings to decide whether this preparation lane is sufficiently defined for outsourcing while retaining accountable internal and professional decision owners.' },
    ],
  },
  {
    slug: 'payroll-provider-assurance-evidence-study', title: 'Payroll provider assurance evidence study',
    question: 'Can a buyer translate a payroll provider assurance report and related commitments into controls, exceptions, complementary customer duties, and follow-up evidence relevant to the proposed service lane?',
    subject: 'payroll provider assurance evidence', unit: 'one provider control claim or exception mapped to one payroll workflow dependency and accountable customer owner',
    states: 'relevant and evidenced, relevant with provider exception, customer duty assigned, scope or period gap, subservice dependency unresolved, claim unsupported, or not applicable with reason',
    service: '/services/payroll-reporting', cta: 'Review payroll reporting support',
    decision: 'whether reporting support can maintain an evidence map for provider oversight without issuing an audit opinion, guaranteeing security, or substituting a document checklist for buyer judgment',
    evidence: 'provider and service scope, report type and period, control identifier, auditor result, exception, management response, complementary customer control, subservice treatment, workflow dependency, owner, remediation evidence, and review date',
    image: '/research-heroes/philippines-payroll-evidence-retention-minimization-study.png',
    uniqueSections: [
      { heading: 'Begin with the buyer workflow, not the report index', body: 'An assurance report can be lengthy and still omit the exact service, location, period, system, or subservice on which a buyer relies. Start by mapping the proposed payroll lane: intake, storage, processing, approval, transmission, support access, incident routing, continuity, and exit. For each dependency, locate the report scope and control evidence that appears relevant. Record gaps explicitly. A clean opinion is not a promise that every control operated perfectly, and an exception is not automatically proof that the buyer’s data was affected. The study does not issue an audit opinion or assess legal sufficiency. It builds a traceable question set for the buyer, provider, security owner, privacy owner, procurement team, and qualified advisers. Administrative support may maintain that map and chase dated evidence, but cannot certify the provider or accept residual risk on the company’s behalf.' },
      { heading: 'Read exceptions in operational context', body: 'For each control exception, capture the population, test period, described deviation, management response, and any limitation on available detail. Then link it to the buyer workflow. Ask whether the relevant control protects a payroll input, privileged account, change path, backup, transmission, or incident response. Distinguish a design gap from an operating exception and a period gap from a service-scope gap. Do not rank severity from wording alone; use the buyer’s data, access, timing, and consequence context. Seek follow-up evidence through the approved diligence channel, preserving dates and versions. If evidence is unavailable, keep the dependency unresolved rather than rewriting the provider’s statement as reassurance. The resulting record should show what is reported, what the provider asserts, what the buyer infers, and what remains unknown.' },
      { heading: 'Assign complementary customer controls', body: 'Provider reports often describe controls the customer must operate, such as authorized-user review, timely access removal, secure configuration, input validation, backup contact maintenance, or incident notification routing. Convert each applicable duty into an owner, frequency, source, acceptance evidence, and escalation point. Do not assign a duty to “the business” or assume the provider performs it because the platform supports it. Test a sample through actual workflow evidence: an access review decision, a configuration change, a rejected input, or a restored backup contact. Where a subservice organization is carved out, identify the dependency and the separate evidence or contractual route used to understand it. Support can maintain due dates and evidence links; authorized owners decide applicability, configuration, exceptions, and risk treatment.' },
      { heading: 'Keep assurance current without manufacturing certainty', body: 'Record the report period, bridge-letter period where applicable, review date, open questions, remediation commitments, and next expected evidence. A document that was relevant during selection can become stale before implementation or renewal. Track changes in service scope, hosting, subprocessors, privileged support, integrations, and incident channels because they can alter the mapping even when the next report is not yet available. Report coverage and unresolved dependencies as separate measures; a high percentage of mapped controls does not show that the service is secure or suitable. State limitations, including evidence withheld for security reasons or conclusions reserved for qualified reviewers. This protocol helps a payroll buyer organize diligence and ongoing oversight. It does not guarantee provider performance, replace independent assurance, or transfer the company’s accountability for its own controls and decisions.' },
    ],
  },
] as const;

const faq = [
  { question: 'Does this research determine legal, tax, payroll, privacy, or security compliance?', answer: 'No. It tests whether declared workflow evidence supports reproducible classifications. Authorized owners and qualified advisers retain consequential decisions.' },
  { question: 'What may a Philippines-based payroll support specialist do?', answer: 'Within approved access, support may assemble records, maintain source links, apply written checks, prepare exceptions, and compare defined outputs. It must stop at authority or interpretation questions.' },
  { question: 'How should a buyer pilot one of these protocols?', answer: 'Freeze one representative population and the rules in advance, review every exception, preserve disagreements, and expand only after the owners accept the evidence and stop conditions.' },
] as const;

export const october2ResearchPosts = studies.map((study, index) => ({
  slug: study.slug, title: study.title, excerpt: `Research protocol: ${study.question}`, published: DATE, order: 1600 + index,
  stat: `One ${study.unit} is the predeclared unit; no measured result is asserted.`, image: study.image,
  takeaways: [`Define ${study.subject} states and authority boundaries before extracting records.`, 'Publish missing evidence, reviewer disagreements, and unresolved units beside successful classifications.', 'Use the result to bound preparation work while named owners retain consequential decisions.'],
  sections: [...study.uniqueSections, ...[0, 1, 2, 3, 5, 7, 8, 9].map((sectionIndex) => sectionsFor(study)[sectionIndex])], sources, faq,
  related: ['payroll-event-sequence-integrity-study', 'payroll-output-confirmation-gap-study', 'payroll-exception-owner-transfer-study'],
  serviceHandoff: { heading: 'Apply the protocol to a bounded support lane', body: `Use one representative cycle to test ${study.decision}. Preserve source references and route interpretation or authority questions to the named owner.`, href: study.service, cta: study.cta },
}));
