const source = (heading: string, body: string) => ({heading, body});

export const august21ResearchPosts = [
  {
    slug: 'philippines-payroll-cutoff-slack-research',
    title: 'Philippines payroll cutoff slack: research on the evidence window',
    excerpt: 'A research question about whether Philippines-based payroll preparation leaves enough documented time for review, decisions, and correction.',
    published: '2026-08-21',
    order: 1,
    image: '/research-heroes/philippines-payroll-cutoff-slack-research.png',
    stat: 'The International Labour Organization publishes country and labor resources for the Philippines.',
    takeaways: ['Research question: what evidence shows that a Philippines payroll cutoff left usable decision time rather than merely producing a file on schedule?', 'Method: compare source arrival, authority review, owner decision, correction, and release events for defined pay periods.', 'Conclusion: cutoff quality is a property of the evidence window and decision ownership, not the calendar date alone.'],
    sections: [
      source('Question, scope, and evidence boundary', 'A payroll cutoff is commonly described as a date by which inputs must arrive. That description hides the operating question this research asks: when a Philippines-based payroll preparation lane reaches its cutoff, is there enough documented slack for a reviewer to understand the source, ask a bounded question, receive an owner decision, and correct an error before release? The unit of analysis is one defined pay period and one agreed population of time, status, deduction, or other payroll inputs. The study does not establish a legal deadline, calculate an employer liability, or claim that a late item caused a particular payroll result. It asks whether the record can show what happened and who could decide.'),
      source('Method: reconstruct the window', 'Build a timeline with separate events for source availability, intake acknowledgement, completeness check, authority check, exception creation, owner response, correction, review, and release. Do not collapse these into one “received” timestamp. A source can arrive early but remain unusable because the covered period or approving person is unclear. Conversely, a late source may still be workable if its authority is clear and the owner has a real decision window. Compare at least several ordinary periods with periods containing late or conflicting inputs. Preserve the source version and timezone used for each event. The method is documentary and comparative, not a statistical estimate of all payroll teams.'),
      source('What the public evidence can and cannot say', 'The ILO provides labor research and country resources, while Philippine government agencies publish employment, tax, and privacy materials. These sources provide context for why payroll work needs accountable handling, but they do not define the private calendar, approval chain, provider cutoff, or employee facts of a particular employer. That distinction matters. A public source may support a governance principle; it cannot turn an internal timestamp into proof that a payment was correct. The evidence packet should label observed event times, interpretations made by the research, and decisions made by the authorized payroll owner. This separation keeps the article from turning general guidance into a legal or tax conclusion.'),
      source('Analysis: slack is more than elapsed hours', 'Elapsed time is useful only when the lane’s decision steps are visible. Measure the interval between a usable source and the owner’s decision, but also note whether the interval included a complete source, a clear question, a reachable decision-maker, and an available correction route. A long interval with no question may indicate that the source was never assessed. A short interval with a documented approval may be safer than a longer interval filled with unowned waiting. Review the earliest point at which the team knew the item could affect the period. If an exception was raised only after release, the nominal calendar slack overstated the usable window. A preparation specialist can calculate these observations and route evidence; the owner decides whether to proceed, hold, or seek qualified advice.'),
      source('Limitations and role boundaries', 'This research cannot prove that a cutoff will work in a future period. Provider calendars, holidays, system availability, staffing, policy, and the complexity of the input population can change. It also cannot infer employee entitlement from a timestamp sequence. Small samples may miss rare but material failures, and incomplete logs can make apparent slack look larger than it was. For an outsourced lane, the safe boundary is to collect and compare timestamps, identify missing evidence, and ask the owner a precise question. The lane should not promise a payroll result, move a disputed item into final approval, or invent a rule for late submissions.'),
      source('Operational test for the next cycle', 'Use one completed period to test the timeline before changing the calendar. Pick a source that arrived early, one that arrived close to cutoff, and one that required an owner question. Ask a reviewer to locate the first usable evidence, identify the waiting interval, and say whether a correction could still have been made. If the answer depends on a chat message or personal memory, mark that dependency as a control gap. The test should produce a small list of observed delays, such as incomplete source labeling, an unavailable approver, or a provider window that was assumed rather than documented. Those observations support a targeted change. They do not support a claim that the whole operation is slow or that a support role should absorb owner decisions.'),
      source('Evidence-led conclusion', 'The evidence supports treating cutoff review as a window-design question. A credible Philippines payroll cutoff record names the population, source version, usable-arrival point, review events, owner decision, correction opportunity, and release evidence. If one of those links is absent, the record can show that a date was met but not that the decision was workable. The practical research conclusion is not to lengthen every calendar; it is to discover where decision time disappears and make that loss visible. Repeat the comparison after a provider or policy change. When the result is uncertain, hold the uncertainty in the record and escalate it rather than replacing it with a reassuring status label.')
    ],
    sources: [{label:'International Labour Organization, Philippines resources',url:'https://www.ilo.org/manila'},{label:'Department of Labor and Employment, official resources',url:'https://www.dole.gov.ph/'},{label:'National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'}],
    faq: [{question:'Does a cutoff date prove enough review time existed?',answer:'No. It proves only that a calendar point was defined; the evidence window must show usable source, review, decision, and correction events.'},{question:'Who decides whether a late payroll input is accepted?',answer:'The authorized payroll or employer owner decides. Support can organize evidence and route the question.'}],
    related: []
  },
  {
    slug: 'philippines-payroll-effective-date-collision-research',
    title: 'Philippines payroll effective-date collisions: research on competing change records',
    excerpt: 'A study of how payroll teams can distinguish request, approval, entry, and effective dates when employee-change records disagree.',
    published: '2026-08-21',
    order: 2,
    image: '/research-heroes/philippines-payroll-effective-date-collision-research.png',
    stat: 'The Philippine National Privacy Commission publishes accountability guidance for personal-information processing.',
    takeaways: ['Research question: how can a Philippines payroll record reveal that two valid-looking changes compete for the same effective period?', 'Method: compare field, population, source authority, event dates, period coverage, and approval lineage.', 'Conclusion: an effective-date collision belongs in an accountable decision queue, not in silent data cleanup.'],
    sections: [
      source('The research question and unit of analysis', 'Payroll change records often carry request date, approval date, entry date, effective date, pay-period date, and confirmation date. This research asks how a Philippines payroll preparation process can detect when two records appear valid but imply different treatment for the same worker, field, or pay period. The unit is one contested field and its surrounding evidence, not an entire employee file. Examples include a status change, pay input, deduction, leave event, or bank instruction, but the study does not decide the correct employment, tax, or payment treatment. Its narrower question is whether the organization can make the disagreement visible and send it to the person with authority.'),
      source('Method: compare meaning before recency', 'For each candidate record, capture what event it describes, who originated it, what period it covers, what source authorizes it, when it was approved, and how it entered the payroll system. Compare like with like: a request timestamp should not be treated as an effective date, and a later system entry should not automatically outrank an earlier approved instruction. Add the downstream population that would be affected and the exact question the owner must answer. Review ordinary records alongside collisions so the method does not overreact to harmless duplicate timestamps. The resulting comparison is qualitative and traceability-focused; it is not a model for predicting which date will win.'),
      source('Evidence interpretation for Philippines payroll operations', 'Philippine labor, tax, and privacy agencies publish material that can frame governance and record-handling questions. None of those public sources resolves a private employer’s conflicting facts. A privacy accountability principle can support limiting an evidence packet to the decision, while an official labor or tax resource may identify a topic for qualified review. Neither source authorizes a support worker to choose between competing dates. In the public article, facts should be attributed to the source, the organization’s internal observations should be labeled as observations, and analysis should be presented as a bounded interpretation. This is especially important when a date collision could affect a person’s pay or status.'),
      source('Analysis: preserve the collision as evidence', 'The common operational temptation is to keep the newest value and discard the disagreement. That may make a tracker look tidy while removing the reason a later reviewer needs to understand the result. A better research record keeps both candidate values, their provenance, the covered period, the affected field, and the owner’s decision. If the owner confirms that one record governs, record the rule and scope without rewriting the original history. If neither source is sufficient, hold the item and name the next evidence request. A Philippines-based specialist can assemble this comparison, highlight duplicate or incompatible dates, and update the queue. The specialist should not infer authority from the newest file or silently amend a sensitive field.'),
      source('Limitations, risks, and role boundaries', 'Date collisions can arise from system migrations, timezone conversion, retroactive approvals, duplicate requests, policy changes, or simple data-entry mistakes. The proposed method cannot determine whether a particular worker is entitled to a payment or whether a date satisfies a legal obligation. It also cannot recover an event that was never recorded. The sample can understate collisions if teams only log the final value. Keep personal information to the minimum needed for the review, use task-based access, and escalate material questions to the employer’s authorized owner and qualified advisers. Treat a repeated collision pattern as a design question, not as proof of individual fault.'),
      source('Decision record test', 'A useful test is to give a second reviewer only the collision packet and ask that person to state the competing values, their covered periods, the authority question, and the owner’s final scope. If the reviewer cannot distinguish request, approval, entry, and effective dates, the record is not ready for a conclusion. If the reviewer can reconstruct the decision but cannot find the downstream field or population check, the evidence chain ends too early. Record the missing link and improve the next packet. This exercise is deliberately modest: it measures explainability for one decision, not the accuracy of every payroll record. It also exposes whether a support lane is being asked to make an interpretation that belongs with the owner.'),
      source('Evidence-led conclusion', 'The research indicates that the safest handling of an effective-date collision is explicit comparison followed by accountable interpretation. A defensible record links the competing dates to their source, field, covered population, approval lineage, owner decision, and downstream check. This does not make a private payroll rule universal and does not remove legal or tax judgment. It does show whether a Philippines payroll support lane can keep an ambiguity from disappearing inside a final file. When the organization changes systems or policy, replay known collision examples against the new process. If the process cannot explain why one value governed, the right conclusion is an escalation and a better evidence boundary, not a guessed date.')
    ],
    sources: [{label:'National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{label:'Department of Labor and Employment, official resources',url:'https://www.dole.gov.ph/'},{label:'Bureau of Internal Revenue, official tax resources',url:'https://www.bir.gov.ph/'}],
    faq: [{question:'Should the latest payroll timestamp always win?',answer:'No. Recency is one observation; authority, scope, and the applicable internal rule require owner interpretation.'},{question:'What should support do with two plausible dates?',answer:'Preserve both sources, identify the affected period and field, hold the item, and route one bounded question.'}], related: []
  },
  {
    slug: 'philippines-payroll-query-cohort-research',
    title: 'Philippines payroll query cohorts: research on routing and resolution evidence',
    excerpt: 'A research method for learning from employee payroll questions without confusing a sample with a legal or performance claim.',
    published: '2026-08-21',
    order: 3,
    image: '/research-heroes/philippines-payroll-query-cohort-research.png',
    stat: 'The International Labour Organization provides labor research and country resources for the Philippines.',
    takeaways: ['Research question: what can a sample of Philippines payroll questions show about routing, evidence quality, and unresolved ownership?', 'Method: define the population, stratify questions by subject and state, and inspect answered and unresolved cases together.', 'Conclusion: a query sample supports process learning only when it preserves denominator, scope, and uncertainty.'],
    sections: [
      source('Question and evidence scope', 'A payroll question can be a routine status request, a missing-document prompt, a correction request, a pay-impact concern, or a matter requiring employer judgment. This research asks what a sample of questions can legitimately reveal about a Philippines payroll support lane. It does not ask whether a sample proves employee satisfaction, legal compliance, or the correctness of individual pay. Define the population first: questions received through named channels during a stated period, with duplicates and reopened cases handled by an explicit rule. The unit is the question and its disposition evidence, not the person’s full employment record.'),
      source('Method: construct cohorts instead of anecdotes', 'Group questions by subject, pay period, source channel, urgency, evidence state, responsible owner, and outcome state. Possible states include answered from approved material, awaiting source, routed for owner decision, corrected with evidence, unresolved at period end, and closed without a supported conclusion. Keep the count of every included and excluded item. Sample across cohorts rather than selecting memorable conversations. For each sampled case, ask what source supported the reply, whether the question was within the preparer’s authority, whether the next action had an owner, and whether closure meant an answer or merely a handoff. This method describes the queue; it does not estimate a market-wide rate.'),
      source('What external sources contribute', 'The ILO’s Philippines resources can provide labor and employment context for research readers, while government sources may point to official tax, employment, or privacy material relevant to a question category. They do not answer a private employee’s individual circumstances. A public source should be cited for the context it actually supports, not pasted beneath a queue count as if it validates every response. In a defensible study, public facts, observed queue facts, and analytical judgments are separated. The support lane should also avoid copying unnecessary personal details into the research sample. Use an identifier, topic, period, source state, and decision owner sufficient for review.'),
      source('Analysis: unresolved cases are part of the result', 'A sample that counts only closed questions creates a misleading picture. Unresolved questions show where source authority, policy clarity, access, timing, or owner capacity may be limiting the lane. They do not by themselves establish the cause. Compare the proportion of cases with a named next owner, the age of the oldest open item, repeated subjects, and the evidence attached to closure. Read those observations alongside the actual cases. A high number of routine questions may reflect an unclear notice; a small number of bank or deduction questions may carry greater sensitivity. A Philippines-based specialist can classify, summarize, and route questions, but should not promise an outcome or interpret a disputed entitlement.'),
      source('Limitations and safe boundaries', 'Question records are shaped by channel habits, language, access to support, and whether employees choose to ask. A sample can miss people who never raised a concern and can overrepresent unusual events. Category labels may drift between reviewers, and a “closed” status may mean different things unless the evidence rule is explicit. The research cannot establish that a response was legally sufficient or that a private policy was applied correctly. Keep sensitive subjects behind approved access, use minimum necessary context, and route tax, banking, benefits, employment-status, and disputed-pay matters to authorized owners. Treat patterns as hypotheses for investigation, not as accusations or performance statistics.'),
      source('Cohort review exercise', 'Before comparing periods, have two reviewers classify the same small set of questions independently, then reconcile differences in the category definitions. Pay attention to a question that contains several subjects, a reopened case, and a case closed after an owner decision. The purpose is not to force perfect agreement; it is to make the classification rule visible. Once the rule is recorded, compare the cohort counts with the underlying cases and check whether unresolved items have a next owner. This exercise can reveal that a queue label describes an inbox state rather than a resolved question. That distinction makes the research more useful to a payroll owner without turning a support classification into a claim about employee outcomes.'),
      source('Evidence-led conclusion', 'A Philippines payroll query sample is useful when it tells the truth about its population, categories, source scope, and unresolved work. The strongest conclusion is operational: the organization can see where questions enter, which ones fit a documented answer, which ones need owner judgment, and whether closure preserves evidence. That visibility can inform a clearer notice, a better intake field, or a different escalation path. It cannot prove every answer was correct or explain a person’s entitlement without the relevant facts and authority. Re-run the cohort method after a channel, payroll system, calendar, or policy change, and retain the category definitions so comparisons remain meaningful.')
    ],
    sources: [{label:'International Labour Organization, Philippines resources',url:'https://www.ilo.org/manila'},{label:'National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{label:'Department of Labor and Employment, official resources',url:'https://www.dole.gov.ph/'}],
    faq: [{question:'Can a query sample prove payroll support quality?',answer:'No. It can describe the sampled population and evidence states; broader quality claims need a defined method and additional evidence.'},{question:'Should unresolved questions be removed from the sample?',answer:'No. Excluding them hides an important part of routing and ownership performance.'}], related: []
  },
  {
    slug: 'philippines-payroll-provider-rejection-evidence-research',
    title: 'Philippines payroll provider rejection evidence: research on traceable correction',
    excerpt: 'A study of whether a rejected payroll submission can be followed from its original source through correction and confirmed outcome.',
    published: '2026-08-21',
    order: 4,
    image: '/research-heroes/philippines-payroll-provider-rejection-evidence-research.png',
    stat: 'Bangko Sentral ng Pilipinas publishes payment-system resources and oversight material.',
    takeaways: ['Research question: can a Philippines payroll provider rejection be traced to the original source, correction authority, resubmission, and final confirmation?', 'Method: compare rejection message, source version, correction record, approvals, transmission receipt, and outcome evidence.', 'Conclusion: provider acceptance is an event in the chain, not proof that the payroll matter is complete.'],
    sections: [
      source('Research question and boundary', 'A provider rejection creates pressure to repair quickly. This research asks whether a Philippines payroll operating lane can preserve enough evidence to explain what failed, what changed, who authorized the change, and what ultimately happened. The study is about traceability, not about deciding tax treatment, payment entitlement, provider liability, or settlement. The unit is one rejected population or transaction set, tied to a specific source version and provider response. A rejection can be a validation message, an incomplete file, a mismatch, or an outcome that needs owner interpretation. Classify the event without assuming the provider message tells the whole story.'),
      source('Method: retain the full correction chain', 'For each case, capture the source population and version, preparation checks, provider response, exact error or status, investigation notes, proposed correction, approval authority, resubmitted version, provider receipt, and final confirmation required by the process. Compare the original with the corrected record instead of overwriting it. Separate transmission from acceptance and acceptance from a confirmed downstream outcome. Review ordinary accepted cases as a control comparison, but do not treat acceptance frequency as a performance measure without a defined denominator. The method is a case-trace review using available documentary evidence; missing logs are a limitation, not an invitation to fill gaps.'),
      source('External context and source discipline', 'BSP payment-system resources provide public context for payment and settlement operations. Philippine tax, labor, and privacy sources may frame other parts of a payroll case, but none of these materials settles a private provider rejection. Public citations should explain the context they support, while the case record should identify internal observations and the provider’s own message. Avoid placing personal banking or employee details into a research narrative when a de-identified field description is enough. The distinction between public fact and internal analysis protects the reader from treating a general payment resource as proof of a specific payroll outcome.'),
      source('Analysis: do not make the failed version disappear', 'Editing a source until a provider accepts it may create a clean-looking final file and a poor explanation. Keep the failed version, response, interpretation, and change rationale connected. Ask whether the correction addressed the provider’s stated issue, whether the correction changed other fields, whether a second approval was required, and whether the final evidence confirms the intended downstream state. Repeated rejections should be grouped by message, source condition, provider format, period, and owner decision. A preparation specialist can maintain this ledger and show a comparison; an authorized owner approves material changes and decides when qualified provider, tax, or legal input is needed.'),
      source('Limitations and role boundaries', 'A provider code can identify a validation symptom without explaining an employer’s underlying policy or a bank’s final action. Provider documentation can change, and confirmation may arrive through a separate channel. A small case set cannot establish the frequency or cause of all rejections. The method also cannot prove that a corrected file resolved every downstream issue. Keep access task-specific, avoid copying sensitive payment data, and leave a case open when the required confirmation is absent. Never infer settlement from transmission or acceptance alone. If the business changes provider, format, calendar, or approval chain, repeat the trace with known cases before relying on old categories.'),
      source('Correction replay test', 'Select a rejection whose original source and final outcome are available and replay the case as a neutral reviewer. Can the reviewer identify the first failed condition without opening an unrelated full export? Can the reviewer see which field changed, why the change was authorized, and whether the resubmission covered the same population? Can the reviewer tell what evidence is still missing? If the answer to any question is no, record the gap instead of calling the case complete. A replay is not a provider audit and does not prove the correction was substantively right. It is a test of whether the organization can explain its own response and separate a transmission event from a confirmed outcome.'),
      source('Evidence-led conclusion', 'The evidence supports a simple conclusion for Philippines payroll operations: a rejection is controlled only when the original failure remains visible beside the correction and the final outcome has its own proof. A traceable case names the affected population, source version, provider response, correction authority, resubmission, receipt, and confirmation. That chain improves the next decision but does not remove provider, banking, calendar, tax, or source-data risk. The research result is therefore bounded. A support lane can organize the story and route unresolved questions; the accountable owner decides whether the case is complete and what the organization should change.')
    ],
    sources: [{label:'Bangko Sentral ng Pilipinas, payment systems resources',url:'https://www.bsp.gov.ph/Pages/PaymentsAndSettlements/PaymentsAndSettlements.aspx'},{label:'Bureau of Internal Revenue, official tax resources',url:'https://www.bir.gov.ph/'},{label:'National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'}],
    faq: [{question:'Is provider acceptance the same as settlement?',answer:'No. Preserve the confirmation evidence required by the applicable process.'},{question:'Should the rejected source be overwritten?',answer:'No. Retain the original record under the approved evidence and retention policy so the correction remains explainable.'}], related: []
  },
  {
    slug: 'philippines-payroll-review-export-minimization-research',
    title: 'Philippines payroll review exports: research on minimization without lost lineage',
    excerpt: 'A research framework for reducing payroll review exports to purpose-defined fields while keeping source authority and decision history visible.',
    published: '2026-08-21',
    order: 5,
    image: '/research-heroes/philippines-payroll-review-export-minimization-research.png',
    stat: 'The National Privacy Commission publishes organizational and technical security guidance for personal information.',
    takeaways: ['Research question: can a Philippines payroll review be completed with a smaller evidence set without losing source lineage or decision context?', 'Method: map each review question to required fields, authority, access, recipients, retention purpose, and reconstruction test.', 'Conclusion: minimization is successful only when the packet is smaller and the decision remains reproducible.'],
    sections: [
      source('Question and evidence scope', 'Payroll teams often export more fields than a reviewer needs because the source system makes broad extracts convenient. This research asks whether a Philippines payroll support lane can reduce a review packet to purpose-defined information while preserving enough lineage to explain the decision later. The unit is one review question and its evidence packet, not the entire employee record. The study does not prescribe a universal retention period, decide privacy compliance for a particular employer, or claim that the smallest file is always safest. It tests whether a reviewer can answer the stated question, identify the authoritative source, understand the period, and locate the owner decision.'),
      source('Method: map purpose to fields', 'Start with the decision the packet must support: completeness, a source conflict, a provider rejection, an owner approval, or another defined question. For each field, record why it is needed, which source owns it, which role may see it, who receives the packet, how long the working copy is needed, and what would be lost if it were removed. Test the reduced packet against an ordinary case, a correction, and an unresolved exception. Ask a second reviewer to reconstruct the decision from the packet and its source links. If the reviewer cannot tell the population, period, version, or authority, the export is too small even if it contains fewer fields. This is a qualitative control test, not a privacy-impact determination.'),
      source('What public guidance contributes', 'The National Privacy Commission’s Data Privacy Act materials provide a public accountability and security context for personal-information processing. NIST privacy and security resources can help readers think about purpose, access, and risk. These sources do not define an employer’s approved field set or retention decision. Public guidance should be used to frame questions, while the employer’s own policies, systems, agreements, and qualified advisers determine what is permitted. In a Philippines payroll context, the article should be careful not to claim that a minimized export by itself proves compliance. It is evidence of a design choice only when its purpose, authority, access, and disposition are documented.'),
      source('Analysis: smaller is not automatically better', 'Removing a field can reduce exposure, but removing the source link, covered period, version, or decision owner can make a later correction impossible to understand. Conversely, including full bank, identity, or unrelated employment details may create exposure without improving the review. Compare packets by decision usefulness rather than file size alone. Trace who can open the packet, where it is stored, whether it is copied to a message or download, and when the working copy is reviewed for disposition. A Philippines-based specialist can inventory fields, create a purpose map, and flag excess or missing evidence. The owner approves the field set and decides sensitive access or retention questions.'),
      source('Limitations and boundaries', 'The right export depends on the question, the source system, the population, the employment context, the provider relationship, and applicable obligations. A generic field list can become unsafe when copied to a different process. The research cannot determine whether a particular organization meets every legal or contractual duty, and it cannot prove that a deleted copy no longer exists without the relevant system evidence. Minimized packets may also fail if reviewers bypass the source link or if a downstream recipient creates a new uncontrolled copy. Keep the method bounded, involve privacy or legal advisers when appropriate, and stop when the available evidence cannot support the requested decision.'),
      source('Reconstruction test', 'Give a reviewer the reduced packet, its source reference, and the stated question, then ask that reviewer to explain the decision without requesting the full export. The reviewer should be able to identify the population, period, source version, relevant field, exception, owner, and next action. If a missing field prevents that explanation, decide whether the field is genuinely necessary or whether the packet needs a better source link or definition. If the reviewer opens unrelated personal data to fill the gap, the design has not achieved its purpose. Repeat the test after a change to the source system or review question. It measures decision reproducibility, not legal compliance, and should be read with the organization’s approved privacy and retention rules.'),
      source('Evidence-led conclusion', 'The research supports purpose-first minimization for Philippines payroll review work. A useful packet contains the minimum information that answers the defined question, identifies the authoritative source, shows period and version, records the exception or decision, and allows a later reviewer to reconstruct the reasoning. It should not contain unrelated personal information simply because it was easy to export. The conclusion is not that smaller files eliminate risk; it is that a field should earn its place through purpose and traceability. Re-test after a system or policy change, retain the approved rationale, and distinguish the preparation role from the owner’s decision about access and disposition.')
    ],
    sources: [{label:'National Privacy Commission, Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{label:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{label:'International Labour Organization, Philippines resources',url:'https://www.ilo.org/manila'}],
    faq: [{question:'Does minimization mean deleting the authoritative payroll source?',answer:'No. It means defining what the review packet needs while preserving the authoritative source under approved policy.'},{question:'Who approves a reduced field set?',answer:'The accountable owner, with privacy, security, legal, or payroll advice where the data and process require it.'}], related: []
  }
] as const;
