import { sectionsFor, type ResearchStudyFrame } from './september22-research';

const DATE = '2026-09-28';
const sources = [
  { label: "Internal Revenue Service: Publication 15 (2026), Employer's Tax Guide (checked September 28, 2026)", url: 'https://www.irs.gov/publications/p15' },
  { label: 'U.S. Department of Labor: Fact Sheet #21, Recordkeeping Requirements under the FLSA (checked September 28, 2026)', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { label: 'NIST: SP 800-53 Rev. 5, Security and Privacy Controls (checked September 28, 2026)', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
  { label: 'Philippine National Privacy Commission: Data Privacy Act of 2012 (checked September 28, 2026)', url: 'https://privacy.gov.ph/data-privacy-act/' },
] as const;

type Study = ResearchStudyFrame & { uniqueSections: readonly {heading:string; body:string}[] };

const studies: readonly Study[] = [
  {
    slug:'payroll-funding-readiness-evidence-study', title:'Payroll funding readiness evidence study',
    question:'Before a payroll owner releases funds, can the review packet show that the approved population, provider output, funding request, destination, deadline, and exception decisions refer to the same run?',
    subject:'payroll funding readiness', unit:'one funding request tied to one entity, currency, provider output, and payroll period',
    states:'ready and bound to output, amount mismatch, destination mismatch, timing risk, approval scope unclear, superseded request, or unresolved',
    service:'/services/payroll-preparation', cta:'Review payroll preparation support',
    decision:'whether a preparation lane can assemble a funding-readiness packet without moving money, selecting an account, authenticating a payment instruction, or approving release',
    evidence:'run identifier, employing entity, pay period, currency, approved output hash, funding amount, destination reference, provider deadline and time zone, source request, approver scope, exception log, supersession chain, and release confirmation reference',
    image:'/research-heroes/philippines-payroll-remittance-source-match-research.png',
    uniqueSections:[
      {heading:'Why funding readiness is not a balance check',body:'A bank balance can be sufficient while the requested transfer is still unsafe to release. The funding amount may belong to another entity, an earlier correction, a test file, or an output that the owner has since rejected. This study therefore treats readiness as a binding problem. The packet must connect the authorized payroll output to one request, one protected destination reference, one currency, and one deadline. It does not copy full bank details into the research file. A reviewer records only the approved destination identifier and checks it against the controlled source. The distinction matters for outsourced payroll operations: a support specialist can reconcile references and expose mismatches, while the account owner retains control of authentication and release. Evidence that a request arrived does not prove it is genuine, and evidence that funds moved does not prove they supported the intended payroll. The defensible conclusion is narrower: the declared records agree, the named owner accepted the remaining exceptions, and the request has not been superseded.'},
      {heading:'Build the run-to-request bridge',body:'Start with the provider output accepted for owner review. Capture its stable file name or hash, entity, period, population count, gross-to-net control totals, currency, and generation time. Then locate the funding instruction through the approved portal or controlled repository rather than through a forwarded message. Compare the request amount and destination reference with the provider output and treasury instructions. Where the provider separates payroll, tax, fees, or multiple payment rails, record each component and the rule for reconstructing the total. A difference is not automatically an error: it may represent a fee, prefunding arrangement, rejected payment, or separately funded tax obligation. It remains unresolved until the authorized owner supplies a documented explanation. Preserve every revised request in a supersession chain. Never overwrite the earlier amount, because doing so removes the evidence needed to explain which version an approver saw. The resulting bridge should allow a second reviewer to reproduce the comparison without gaining authority to release funds.'},
      {heading:'Time-window and contingency analysis',body:'A readiness decision is also time dependent. Record the provider cutoff, banking cutoff, local holidays, currency date, requested value date, and the time zone attached to each. Avoid converting all events to the reviewer’s local clock without preserving the original offset. Test the contingency path before the deadline: identify the primary owner, backup owner, approved communication channel, and rule for pausing when an instruction changes. A late request should not be made to look timely by substituting upload time for receipt time. Likewise, early prefunding should not be called delayed merely because payroll settlement occurs later. Report waiting time separately from active preparation. For a missed window, classify whether the limiting event was missing approval, insufficient evidence, provider revision, treasury availability, technical access, or an external banking constraint. These categories support process improvement without assigning fault. They also show whether administrative support can improve earlier preparation or whether the organization must change an owner decision, banking arrangement, or provider commitment.'},
      {heading:'A practical funding packet test',body:'Run a tabletop test with one ordinary request, one revised request, and one request deliberately seeded with a mismatched period or destination reference. Give the preparer only the approved repositories and written routing rules. Observe whether the mismatch reaches the correct owner before the declared release gate, whether the older instruction remains visible, and whether the backup owner can understand the packet without oral history. Score individual evidence fields rather than giving the exercise a vague pass. A packet may have a correct amount but fail version control; another may be internally complete but arrive after the treasury window. Retain those distinctions in the finding. Then inspect the smallest useful daily status: run identifier, evidence state, blocking owner, next action, deadline in its source zone, and last verified version. Do not place account numbers or authentication material on that status view. The test is successful when authorized reviewers can distinguish ready, waiting, superseded, and stopped requests consistently. It does not require the research participant to initiate a bank action, and no production transfer should be created merely to validate the administrative process.'},
    ]
  },
  {
    slug:'payroll-variable-pay-source-lineage-study', title:'Payroll variable-pay source lineage study',
    question:'Can each bonus, commission, incentive, or allowance input be traced from an approved plan and performance source through calculation ownership, effective period, review, and payroll output?',
    subject:'variable-pay source lineage', unit:'one variable-pay line for one worker and earning period presented as a payroll input',
    states:'lineage complete, plan version missing, period mismatch, calculation owner unclear, duplicate line, approval detached, output unconfirmed, or unresolved',
    service:'/services/payroll-data-entry', cta:'Review payroll data-entry support',
    decision:'whether data-entry support can prepare variable-pay inputs while compensation owners retain plan interpretation, performance judgment, eligibility, calculation, tax, and approval decisions',
    evidence:'protected worker identifier, earning code, earning period, plan version, performance source, calculation source and owner, currency, effective payroll, approval reference, import identifier, output field, and exception disposition',
    image:'/research-heroes/philippines-payroll-correction-lineage-review.png',
    uniqueSections:[
      {heading:'Separate the award decision from payroll preparation',body:'Variable pay often reaches payroll as a spreadsheet total, but a total alone cannot show whether the line belongs to the worker, period, plan, currency, or earning code. The study begins upstream. It records the approved plan version and the authority that determined eligibility, performance, and amount. Payroll support does not recreate sales-credit policy or decide whether a manager exercised discretion correctly. Its bounded job is to test whether the approved decision can travel into payroll without losing identity or context. A useful record distinguishes the measurement period from the payroll period and the approval date from the effective date. Those dates can differ legitimately. It also distinguishes an original award from a correction, draw recovery, true-up, or reversal. Combining these events into one net value may make a file easier to import but makes the history harder to inspect. The protocol keeps the event lineage visible and routes interpretive questions back to compensation, finance, HR, or another named owner.'},
      {heading:'Reconcile at line, cohort, and control-total levels',body:'Use three complementary checks. At line level, match the protected worker identifier, earning code, currency, earning period, amount, and approval reference. At cohort level, compare the approved award population with the payroll import population to find omissions, additions, and duplicated workers. At control-total level, compare count and value totals by entity, currency, and earning code. A matching grand total is weak evidence because equal and opposite errors can cancel. A line match is also incomplete if a whole approved cohort never entered the import. Record normalization rules before comparison, including decimal precision, currency conversions, negative values, split payments, and identifier changes. Do not silently coerce text, strip leading zeros, or merge names. When a record changes after approval, require a new version or explicit correction link. Publish unresolved differences rather than forcing totals to agree. This layered design identifies the point where lineage broke and gives the owner a concrete question to answer.'},
      {heading:'Test period boundaries and later true-ups',body:'Variable pay is especially vulnerable at quarter ends, annual plan changes, transfers between entities, leaves, and terminations. Construct boundary cases that test an earning period spanning two payroll cycles, an approval after cutoff, a worker whose entity changes, a negative true-up, and an award that is approved but intentionally deferred. Declare the expected state for each case before examining production results. Later corrections should point to the original award and state whether they replace it, add to it, or reverse it. The study must not label every delayed line an error; a documented deferral can be valid. It must also avoid treating a later clean payslip as proof that the original process was controlled. Report the initial exception and the correction separately. This treatment supports operational learning: recurring plan-version gaps suggest an intake design problem, period mismatches suggest calendar or definition problems, and duplicated lines suggest version or import controls. None by itself establishes employee entitlement or liability.'},
      {heading:'Use disagreement to improve the award dictionary',body:'Ask two reviewers to classify a sample containing commissions, discretionary awards, recoverable draws, noncash incentives, guarantees, and retroactive true-ups. Do not let them confer during the first pass. A disagreement about whether a row is an original award or a correction may reveal that the event dictionary is too broad. A disagreement about the earning period may show that a sales report and payroll calendar use the same label for different intervals. Preserve both initial answers, identify the missing definition, and have the compensation owner adjudicate the rule. Revise the dictionary prospectively and retest the disputed sample; do not silently alter historical classifications. Useful dictionary fields include event type, allowed sign, authoritative source, permissible earning code, plan-version requirement, period convention, currency convention, and required approval. This exercise produces a more valuable result than a single accuracy percentage. It shows exactly which handoff concepts can be applied by administrative support and which still depend on compensation judgment. Publication should disclose the sample rule and initial disagreement count without exposing worker or award details.'},
    ]
  },
  {
    slug:'payroll-garnishment-order-intake-boundary-study', title:'Payroll garnishment order intake boundary study',
    question:'Can a sensitive withholding order be received, restricted, routed, interpreted by an authorized owner, converted into an approved payroll instruction, and later removed without the support lane making legal decisions?',
    subject:'garnishment-order intake boundaries', unit:'one withholding-order lifecycle from controlled receipt through owner-directed activation, change, suspension, or closure',
    states:'controlled route complete, authority review pending, identity mismatch, effective-period ambiguity, protected data overexposed, stop instruction missing, output unconfirmed, or unresolved',
    service:'/services/benefits-deduction-administration', cta:'Review deduction administration support',
    decision:'whether administrative support can log and route high-sensitivity orders while counsel, payroll leadership, or another authorized owner interprets jurisdiction, priority, limits, disputes, and required responses',
    evidence:'restricted case identifier, receipt channel and time, issuing-body reference, protected worker match, jurisdiction field, order dates, owner assignment, interpretation record, approved payroll instruction, effective periods, review dates, output confirmation, and closure evidence',
    image:'/research-heroes/philippines-payroll-approval-authority-boundary-research.png',
    uniqueSections:[
      {heading:'Design intake around sensitivity and authority',body:'A withholding order can contain government identifiers, addresses, financial details, family information, allegations, and strict response dates. The first control is therefore a restricted intake route, not a broad payroll mailbox. Log receipt with a protected case number, channel, timestamp, purported issuing body, and minimum matching fields. Do not reproduce the full document in a shared tracker. The support specialist may check whether the record is readable and route it to the designated owner, but should not decide that the document is valid, determine priority among orders, calculate a legal limit, answer the issuing body, or tell the worker what the law requires. Those are authority questions. The study asks whether the workflow makes that boundary observable. A case remains pending when the owner decision is absent even if a deadline is close. Urgency should trigger escalation, not invented authority. Access logs, retention rules, and named recipients are part of the evidence because a procedurally correct deduction can still be surrounded by excessive disclosure.'},
      {heading:'Translate an owner decision into a bounded instruction',body:'Once the authorized owner has interpreted the order, payroll needs a precise instruction rather than a forwarded document plus informal summary. The instruction should identify the protected case, worker record, deduction code, calculation or fixed amount supplied by the owner, start condition, priority rule if applicable, review point, stop condition, and source decision. The preparation lane checks that required fields exist and that dates map to the intended payroll calendar. It does not recalculate an owner-supplied legal rule. If the payroll system cannot represent the instruction, record the limitation and return the case for an owner decision rather than approximating. Use a maker-checker step before activation. After processing, compare the defined output field with the approved instruction while limiting access to people assigned to the case. The output check establishes execution evidence only; it does not prove that the owner’s interpretation was legally correct. This distinction keeps administrative QA useful without converting it into unauthorized advice.'},
      {heading:'Treat stopping as a first-class event',body:'Many workflows focus on starting a deduction and give too little structure to amendment, suspension, satisfaction, release, or employee departure. This study follows the entire lifecycle. A closure event must link to an approved source, state its effective boundary, identify affected future periods, and trigger both payroll removal and appropriate record disposition. Test a release received after cutoff, a replacement order, a worker transfer, an order with conflicting identifiers, and a system that carries the deduction forward automatically. The safest classifier does not assume that silence means continue or stop; it follows the written owner instruction. Reconcile the active-order register to payroll deductions periodically, but report false positives caused by timing separately from genuine orphaned deductions. Preserve proof that access was narrowed when the case closed. These checks reveal whether the organization can terminate sensitive processing as reliably as it begins it, while leaving jurisdiction-specific determinations to authorized professionals.'},
      {heading:'Audit exposure without reproducing protected contents',body:'The privacy review can use metadata instead of copying the order. Sample whether each access event belonged to a named role, occurred during the active case window, and used the approved repository. Compare the recipient list with the routing rule and note uncontrolled attachments, downloads, printouts, or ticket comments as separate exception types. Reviewers should not open protected content merely to prove that access exists; system logs, case permissions, and redacted field inventories may supply sufficient evidence. When deeper review is required, the privacy owner should approve its purpose and participants. Measure closure hygiene as well: removal from working queues, revocation of temporary permissions, disposition of local copies, and retention of the authoritative record under policy. A finding about excess access is an operational observation, not a public allegation about a person. The remediation question is whether role design, training, system configuration, or case routing needs correction. This approach keeps the study useful while honoring the principle that research should not create a second uncontrolled collection of sensitive withholding information.'},
    ]
  },
  {
    slug:'payroll-multi-currency-conversion-evidence-study', title:'Payroll multi-currency conversion evidence study',
    question:'When payroll-related values cross currencies, can the reviewer identify the source amount, approved rate source, quotation basis, rate date, rounding rule, converted value, and owner-approved exception?',
    subject:'multi-currency conversion evidence', unit:'one payroll input or funding component converted from a declared source currency to a declared payroll or settlement currency',
    states:'conversion reproducible, rate source missing, rate date mismatch, quotation inverted, rounding unexplained, manual override unapproved, downstream value differs, or unresolved',
    service:'/services/payroll-reporting', cta:'Review payroll reporting support',
    decision:'whether reporting support can reproduce conversions and surface variances without choosing treasury policy, promising exchange outcomes, interpreting tax treatment, or authorizing settlement',
    evidence:'source event identifier, source amount and currency, target currency, approved rate-source reference, direct or inverse quote, rate timestamp, rate value, precision and rounding rule, converted amount, override approval, output source, and variance disposition',
    image:'/research-heroes/philippines-payroll-source-output-bridge-study.png',
    uniqueSections:[
      {heading:'Define what the exchange rate is doing',body:'A payroll file may use exchange rates for compensation reporting, shadow payroll, accounting allocation, funding, reimbursement, or actual settlement. These purposes can legitimately use different dates and sources. The study therefore starts by naming the business purpose and owner-approved policy for each conversion. It records whether the quote expresses target currency per unit of source currency or the inverse. That small field prevents a common ambiguity that can produce a mathematically neat but economically wrong answer. The protocol does not select a preferable market rate or claim that one public benchmark fits a private contract. It asks whether another reviewer can reproduce the value from the declared source. The source record should be immutable or archived, because a web page showing a current rate cannot prove the rate available at an earlier cutoff. Support may capture the approved rate and apply a written formula. Treasury, finance, payroll, tax, and legal owners retain decisions about policy, contracts, accounting, settlement, and statutory reporting.'},
      {heading:'Recalculate before comparing totals',body:'For each sampled conversion, preserve the unrounded source value, currency codes, rate, quote direction, multiplication or division rule, intermediate precision, and final rounding convention. Recalculate the line independently before comparing it with payroll or funding output. Separate three variance types: a rate variance, a formula variance, and a rounding variance. A control total alone cannot locate the cause and may hide offsetting errors across positive and negative lines. Group results by rate source, rate date, currency pair, and process lane only after line-level testing. When the system stores fewer decimal places than the source, describe the resulting tolerance in advance and apply it consistently. A manual override should retain the original calculated value, the replacement value, the reason, and the authorized approver. Never rewrite the base record to erase a variance. The study’s evidence should show both the rule as designed and the value actually delivered downstream.'},
      {heading:'Stress-test calendar and reversal cases',body:'Rate timing becomes difficult around weekends, holidays, retroactive adjustments, reversals, and payrolls prepared in one zone but funded in another. Create prospective cases for a rate published after local cutoff, a missing market day, a reversed payment, a correction to a prior period, and a currency whose smallest unit differs from the reporting precision. State whether policy calls for the prior available rate, monthly average, transaction rate, or another owner-approved basis; the research protocol does not invent a fallback. Preserve the original period’s conversion when a later correction uses a new rate, unless the authorized policy explicitly requires restatement. Report nominal differences separately from process failures. A small monetary variance can still reveal an uncontrolled override, while a large difference may be an explainable timing effect. This approach keeps the analysis focused on reproducibility and authority rather than hindsight selection of the most favorable rate.'},
      {heading:'Present variance without implying currency advice',body:'A decision brief should show the source amount, declared policy basis, applied rate, independently recalculated value, delivered value, and categorized difference. It may aggregate exception counts by currency pair when the group is large enough to avoid identifying individual pay. It should not rank currencies, predict markets, or recommend when to exchange money. Those activities are outside this payroll evidence study. To make the operational conclusion actionable, connect each variance category to a process owner: unavailable archived rate to finance data ownership, inverted quotation to transformation design, unexplained rounding to system configuration, and unapproved override to the approval path. Keep actual monetary exposure separate from the evidence-completeness rate. A process can have complete evidence for an owner-approved exception, and it can have incomplete evidence even when the difference rounds to zero. That separation prevents teams from ignoring weak controls in low-value samples or overstating the significance of one high-value case. Reproduction files should use synthetic examples where possible and tightly controlled extracts where actual values are necessary.'},
    ]
  },
  {
    slug:'contractor-payment-to-payroll-boundary-study', title:'Contractor payment-to-payroll boundary study',
    question:'Can an organization show why a worker-related payment entered the contractor-payables lane or the employee-payroll lane, and whether later status or source changes were routed to an authorized owner?',
    subject:'contractor-payment and payroll boundaries', unit:'one worker-related payment request presented to either contractor administration or employee payroll for a defined service period',
    states:'approved lane evidenced, status decision missing, source conflict, duplicate across lanes, period mismatch, owner-directed reclassification pending, output unconfirmed, or unresolved',
    service:'/services/contractor-payment-administration', cta:'Review contractor payment administration support',
    decision:'whether administrative support can prepare invoices and payroll inputs without deciding worker classification, employment status, tax obligations, contract interpretation, or entitlement',
    evidence:'protected worker or vendor identifier, service period, payment request, contract or employment-source reference, status decision owner and date, approved processing lane, entity, currency, duplicate check, approval, output reference, and correction lineage',
    image:'/research-heroes/philippines-payroll-multi-entity-record-segregation-test.png',
    uniqueSections:[
      {heading:'Make the classification decision visible but separate',body:'The operational risk begins when a team treats the payment channel as evidence of worker status. An invoice does not by itself prove that contractor processing is correct, and appearance in payroll does not by itself resolve classification. This study never asks administrative support to make that decision. It asks whether each payment request points to a dated determination by the authorized company owner or qualified adviser and whether the selected processing lane matches that determination. The research record captures a protected identifier, service period, paying entity, currency, source agreement reference, decision owner, and decision date. It avoids copying whole contracts or personal records into the analysis. If the source documents conflict, the item is unresolved and returns to the owner. A deadline, familiar invoice format, or previous payment is not a substitute for current authority. By keeping decision evidence distinct from data preparation, the organization can inspect the handoff without suggesting that an outsourced administrator assumed employer, legal, or tax responsibility.'},
      {heading:'Search for duplicates across systems',body:'A duplicate check confined to accounts payable will miss a payment also prepared in payroll. Freeze both eligible populations for the same service and pay periods, normalize stable identifiers under controlled access, and compare amount, currency, entity, service period, invoice or earning reference, and intended payment date. Names are weak matching keys and should be used only as a review aid. Categorize exact duplicates, probable duplicates, deliberate split payments, reimbursements, reversals, and unresolved near matches. Do not delete either record during the study. Preserve source links and route the pair to the owner who can decide the correct lane. Compare control totals only after investigating line-level matches; totals cannot show that the same person was paid twice through different systems. The protocol should also test whether canceled and reissued requests remain connected. A support team can maintain this cross-lane exception register, but cannot conclude that a person should be moved from one legal or tax status to another.'},
      {heading:'Follow transitions without rewriting history',body:'Worker relationships can change. A contractor may later become an employee, an employee may provide a separately reviewed service, or a record may have been placed in the wrong lane and need correction. The study treats each change as a dated transition with an owner decision, not as permission to relabel historical records silently. Capture the last service period under the old instruction, first period under the new instruction, affected entity, open invoices or payroll inputs, access changes, and correction plan. Test boundary cases where periods overlap, approvals arrive after cutoff, or the same identifier exists in both systems. Report whether the downstream output matches the approved transition, but do not infer statutory correctness from a clean system result. A reproducible transition record helps the organization prevent duplicate payment and orphaned access while preserving the original evidence required for review. Any legal, tax, benefits, or employment consequence remains outside the administrative lane.'},
      {heading:'Evaluate queues without treating speed as correctness',body:'Compare elapsed time from complete authorized input to prepared record separately for contractor payables and employee payroll. Exclude time waiting for the status owner, but publish that waiting as its own category rather than making it disappear. A fast invoice entry with no status reference is not a better result than a carefully stopped item. Likewise, a long payroll case may reflect a deliberate owner review rather than administrative delay. Examine return reasons: missing service period, unmatched entity, absent approval, duplicate candidate, currency conflict, or unclear transition. Trend the reasons across cycles only after definitions stabilize. The operational opportunity may be a better intake form, a shared protected identifier, earlier cutoff, or clearer owner response window. It is not permission for support to decide ambiguous status so the queue closes faster. A balanced report combines timeliness, evidence completeness, duplicate detection, reviewer agreement, and unresolved-owner time. That combination supports a realistic staffing and process decision while preserving the company’s responsibility for classification and payment policy.'},
    ]
  },
] as const;

const faq = [
  { question:'Does a clean evidence classification prove legal or payroll correctness?', answer:'No. It shows whether the declared workflow evidence supports a reproducible state. Authorized owners and qualified advisers retain consequential decisions.' },
  { question:'What may an outsourced payroll support specialist do?', answer:'Within approved access, the specialist may assemble records, apply written checks, preserve versions, prepare exceptions, and compare a defined output. The specialist must stop at authority or interpretation questions.' },
  { question:'How should a buyer pilot the protocol?', answer:'Use one representative cycle, freeze the population and rules in advance, inspect every exception, and expand only after owners accept the evidence and stop conditions.' },
] as const;

export const september28ResearchPosts = studies.map((study,index)=>({
  slug:study.slug,title:study.title,excerpt:`Research protocol: ${study.question}`,published:DATE,order:1500+index,
  stat:`One ${study.unit} is the predeclared unit; no measured result is asserted.`,image:study.image,
  takeaways:[`Define ${study.subject} states and owner decisions before extracting records.`,'Keep facts, classifications, operational inferences, and unresolved evidence separate.','Use the result to bound administrative support; do not transfer consequential authority.'],
  sections:[...study.uniqueSections,...sectionsFor(study)],sources,faq,
  related:['payroll-event-sequence-integrity-study','payroll-approval-replay-detection-study','payroll-output-confirmation-gap-study'],
  serviceHandoff:{heading:'Apply the protocol to a bounded support lane',body:`Use one representative cycle to test ${study.decision}. Preserve source references and route interpretation or authority questions to the named owner.`,href:study.service,cta:study.cta},
}));
