import { sectionsFor, type ResearchStudyFrame } from './september22-research';

const DATE = '2026-09-23';
const sources = [
  { label: "Internal Revenue Service — Publication 15 (2026), Employer's Tax Guide (checked September 23, 2026)", url: 'https://www.irs.gov/publications/p15' },
  { label: 'U.S. Department of Labor — Fact Sheet #21: Recordkeeping Requirements under the FLSA (checked September 23, 2026)', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { label: 'National Institute of Standards and Technology — SP 800-53 Rev. 5, Security and Privacy Controls (checked September 23, 2026)', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
  { label: 'Philippine National Privacy Commission — Data Privacy Act of 2012 (checked September 23, 2026)', url: 'https://privacy.gov.ph/data-privacy-act/' },
] as const;

const studies: readonly ResearchStudyFrame[] = [
  { slug:'payroll-superseded-instruction-containment-study', title:'Payroll superseded instruction containment study', question:'When an owner replaces or withdraws a payroll instruction, can every working copy, queued action, reviewer packet, and downstream handoff be identified before the obsolete instruction is used?', subject:'superseded-instruction containment', unit:'one owner-authorized payroll instruction that is later replaced, withdrawn, or declared invalid before cycle close', states:'contained before use, replaced with linked authority, obsolete copy discovered in use, downstream recipient unconfirmed, conflicting instruction unresolved, population incomplete, or unresolved', service:'/services/payroll-preparation', cta:'Review payroll preparation support', decision:'whether a preparation lane can stop an obsolete but once-valid instruction from surviving in queues, attachments, exports, or provider packets', evidence:'instruction identifier, affected population and period, original authority, superseding authority, change time, reason category, copy locations, queue state, recipient acknowledgments, stop action, replacement link, and output check', image:'/research-heroes/philippines-payroll-effective-date-collision-research.png' },
  { slug:'payroll-evidence-provenance-break-study', title:'Payroll evidence provenance break study', question:'Can a reviewer trace each decision-supporting payroll value from the presented evidence back to its authoritative source, extraction rule, transformation, and version?', subject:'evidence-provenance breaks', unit:'one material value or status used in a payroll preparation, approval, exception, or reconciliation decision', states:'provenance complete, source identified but version missing, transformation unexplained, manual value unsupported, conflicting lineage, source inaccessible, or unresolved', service:'/services/payroll-reporting', cta:'Review payroll reporting support', decision:'whether an outsourced reporting lane can prepare review evidence whose origin and transformations remain inspectable without copying unnecessary sensitive data', evidence:'value identifier, decision use, authoritative source, source version, extraction time, query or selection rule, transformation steps, manual interventions, reviewer, retained source link, and final output reference', image:'/research-heroes/philippines-payroll-source-output-bridge-study.png' },
  { slug:'payroll-calendar-version-divergence-study', title:'Payroll calendar version divergence study', question:'When teams and systems hold different versions of the payroll calendar, which deadlines, populations, approvals, and handoffs are affected before the divergence is reconciled?', subject:'calendar-version divergence', unit:'one payroll cycle for which at least two operational records state different cutoff, review, submission, payment, or close dates', states:'single authoritative version, divergence detected before action, divergence detected after action, local exception authorized, version owner unclear, affected action unknown, or unresolved', service:'/services/payroll-preparation', cta:'Review payroll preparation support', decision:'whether a cross-border preparation lane uses one owner-approved calendar version across trackers, reminders, provider instructions, and reviewer packets', evidence:'cycle identifier, calendar versions, publishers, approval records, effective dates, time zones, changed fields, distribution list, acknowledgments, actions taken under each version, reconciliation decision, and downstream confirmation', image:'/research-heroes/philippines-payroll-deadline-review-slack-study.png' },
  { slug:'payroll-unresolved-case-carryforward-study', title:'Payroll unresolved case carry-forward study', question:'When a payroll exception remains open at cycle close, does the next cycle preserve its evidence, decision owner, risk, deadline, and relationship to later inputs without treating it as resolved?', subject:'unresolved-case carry-forward', unit:'one payroll exception still open at the declared close point of its originating cycle', states:'carried with complete context, resolved before next intake, replaced by linked case, duplicated across cycles, owner or deadline lost, silently omitted, or unresolved', service:'/services/payroll-query-support', cta:'Review payroll query support', decision:'whether a query-support lane can preserve open work across cycle boundaries while authorized owners retain disputed pay, policy, tax, banking, and employment decisions', evidence:'case identifier, originating period, affected person or population key, issue category, source links, last verified state, owner, authority boundary, next action, due date, linked later inputs, closure evidence, and next-cycle reference', image:'/research-heroes/philippines-payroll-correction-lineage-review.png' },
  { slug:'payroll-emergency-export-accountability-study', title:'Payroll emergency export accountability study', question:'When ordinary payroll access or reporting fails, can emergency export use be tied to a declared need, minimum dataset, authorized user, secure destination, review, and timely disposition?', subject:'emergency-export accountability', unit:'one export of payroll or employee data produced through an emergency, elevated, temporary, or out-of-band access path', states:'authorized and minimized, authorized but overbroad, destination unverified, temporary access not removed, use not independently reviewed, export disposition unknown, or unresolved', service:'/services/payroll-reporting', cta:'Review payroll reporting support', decision:'whether a reporting-support lane can recover necessary evidence during an access disruption without normalizing broad or persistent access to sensitive records', evidence:'incident or request identifier, business need, approving owner, user, access path, activation and expiry times, selected fields and population, destination, transfer method, recipient, use record, independent review, deletion or retention decision, and access-removal evidence', image:'/research-heroes/philippines-payroll-evidence-retention-minimization-study.png' },
] as const;

const faq = [
  { question:'Does this protocol determine whether a payroll outcome is legally correct?', answer:'No. It tests evidence and workflow states. Authorized company owners and qualified advisers decide pay, tax, employment, privacy, banking, benefit, and records treatment.' },
  { question:'What can a Philippines-based payroll support specialist do?', answer:'Within approved access, a specialist can assemble the population, preserve source links, apply written classifications, prepare exceptions, and verify a defined output. Consequential decisions stay with the designated owner.' },
  { question:'What should a buyer test before expanding the lane?', answer:'Test the source map, version rules, named owners, access limits, stop conditions, independent review, exception acceptance, output evidence, and disposition rules on one representative cycle.' },
] as const;

export const september23ResearchPosts = studies.map((study,index)=>({
  slug:study.slug,title:study.title,excerpt:`Research protocol: ${study.question}`,published:DATE,order:1200+index,
  stat:`One ${study.unit} is the predeclared unit; no measured result is asserted.`,image:study.image,
  takeaways:[`Define ${study.subject} states before extracting the population.`,'Publish missing evidence, reviewer disagreements, and unresolved units alongside successful classifications.','Use the finding to bound support work while named owners retain consequential decisions.'],
  sections:sectionsFor(study),sources,faq,
  related:['payroll-event-sequence-integrity-study','payroll-source-definition-change-detection-study','payroll-output-confirmation-gap-study'],
  serviceHandoff:{heading:'Apply the protocol to a bounded support lane',body:`Use the study to test ${study.decision}. Start with one representative cycle, preserve the source trail, and route every authority or interpretation question to the named owner.`,href:study.service,cta:study.cta},
}));
