import { sectionsFor, type ResearchStudyFrame } from './september22-research';

const DATE = '2026-09-24';
const sources = [
  { label: "Internal Revenue Service: Publication 15 (2026), Employer's Tax Guide (checked September 24, 2026)", url: 'https://www.irs.gov/publications/p15' },
  { label: 'U.S. Department of Labor: Fact Sheet #21, Recordkeeping Requirements under the FLSA (checked September 24, 2026)', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { label: 'National Institute of Standards and Technology: SP 800-53 Rev. 5, Security and Privacy Controls (checked September 24, 2026)', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
  { label: 'Philippine National Privacy Commission: Data Privacy Act of 2012 (checked September 24, 2026)', url: 'https://privacy.gov.ph/data-privacy-act/' },
] as const;

const studies: readonly ResearchStudyFrame[] = [
  { slug:'payroll-pay-group-configuration-drift-study', title:'Payroll pay-group configuration drift study', question:'When a pay group’s calendar, eligibility, earning, deduction, or approval settings change, can a reviewer identify the first affected population and distinguish an authorized configuration change from silent drift?', subject:'pay-group configuration drift', unit:'one material pay-group setting used to select, calculate, route, review, or release a payroll population', states:'configuration matched authority, authorized change implemented, unauthorized drift detected before use, drift detected after use, effective date ambiguous, affected population unknown, or unresolved', service:'/services/payroll-preparation', cta:'Review payroll preparation support', decision:'whether a preparation lane can detect material configuration drift before apparently valid records move into owner review or provider submission', evidence:'pay-group identifier, setting name, approved baseline, observed value, configuration version, effective date, change actor, authority record, first affected period, population query, test result, exception owner, and output confirmation', image:'/research-heroes/philippines-payroll-source-output-bridge-study.png' },
  { slug:'payroll-deduction-priority-conflict-study', title:'Payroll deduction priority conflict study', question:'When available pay cannot support every expected deduction, can the operating record show which instruction, owner, rule, and evidence governed the resulting priority or deferral?', subject:'deduction-priority conflicts', unit:'one payroll case in which two or more expected deductions compete for an amount that cannot satisfy all expected values', states:'priority supported by approved rule, owner decision documented, deduction deferred with traceable reason, conflicting instructions retained, priority inferred without authority, downstream result unconfirmed, or unresolved', service:'/services/benefits-deduction-administration', cta:'Review benefits deduction administration support', decision:'whether a deduction-administration lane can prepare the conflict evidence without allowing support staff to decide legal priority, employee entitlement, or recovery treatment', evidence:'case identifier, pay period, expected deductions, controlled source references, available amount, applicable written rule, authority owner, decision request, decision record, deferred item, employee or provider communication reference, and resulting output', image:'/research-heroes/philippines-payroll-correction-lineage-review.png' },
  { slug:'payroll-off-cycle-authority-boundary-study', title:'Payroll off-cycle authority boundary study', question:'Can each off-cycle payroll request be traced to a defined reason, affected population, authorized requester, funding and release decision, duplicate-prevention check, and confirmed result?', subject:'off-cycle authority boundaries', unit:'one request to calculate, correct, transmit, or release payroll outside the ordinary approved cycle', states:'authorized and bounded, returned for missing evidence, duplicate prevented, scope changed and reapproved, requester lacked current authority, release evidence missing, or unresolved', service:'/services/payroll-preparation', cta:'Review payroll preparation support', decision:'whether a support lane can prepare urgent off-cycle work without converting urgency, system access, or a prior approval into authority for a new payroll action', evidence:'request identifier, stated reason, affected people or cases, source period, requested values, requester, current authority record, duplicate search, preparation evidence, reviewer, approval time, release reference, and output confirmation', image:'/research-heroes/philippines-payroll-approval-authority-boundary-research.png' },
  { slug:'payroll-master-data-field-ownership-study', title:'Payroll master-data field ownership study', question:'For each payroll-relevant employee master-data field, are source authority, permitted editor, effective-date rule, reviewer, downstream consumers, and correction route explicit and consistent?', subject:'master-data field ownership', unit:'one payroll-relevant master-data field for one employing entity and defined system-of-record relationship', states:'ownership complete, source authority unclear, edit permission broader than authority, effective-date rule missing, downstream consumer unmapped, conflicting owner records, or unresolved', service:'/services/payroll-data-entry', cta:'Review payroll data-entry support', decision:'whether a data-entry support lane has a field-level boundary strong enough to prepare approved changes without deciding employment, tax, banking, benefit, or payroll policy', evidence:'field identifier, business meaning, authoritative source, permitted editor role, decision owner, approval requirement, effective-date rule, validation rule, downstream systems, sensitive-data class, correction route, and last review date', image:'/research-heroes/philippines-payroll-multi-entity-record-segregation-test.png' },
  { slug:'payroll-reconciliation-tolerance-override-study', title:'Payroll reconciliation tolerance override study', question:'When a payroll variance is accepted outside an ordinary tolerance, can a reviewer reconstruct the exact exception, rationale, approving authority, duration, affected population, and later verification?', subject:'reconciliation-tolerance overrides', unit:'one variance accepted, deferred, or routed differently because an ordinary reconciliation threshold or stop rule was overridden', states:'override fully authorized, temporary override expired, scope exceeded, rationale unsupported, approving authority mismatched, later verification missing, or unresolved', service:'/services/timesheet-reconciliation', cta:'Review timesheet reconciliation support', decision:'whether a reconciliation lane can apply owner-approved exception handling without normalizing unexplained differences or silently changing the threshold used to close a cycle', evidence:'reconciliation identifier, expected and observed values, variance, ordinary threshold, override value, stated rationale, approving owner, authority scope, affected period and population, start and expiry, compensating check, and later disposition', image:'/research-heroes/payroll-cutoff-evidence-window-study.png' },
] as const;

const faq = [
  { question:'Does this protocol determine whether a payroll outcome is legally correct?', answer:'No. It tests evidence and workflow states. Authorized company owners and qualified advisers decide pay, tax, employment, privacy, banking, benefit, and records treatment.' },
  { question:'What can a Philippines-based payroll support specialist do?', answer:'Within approved access, a specialist can freeze the population, preserve source links, apply written classifications, prepare exceptions, and verify a defined output. Consequential decisions stay with the designated owner.' },
  { question:'What should a buyer test before expanding the lane?', answer:'Test source definitions, version rules, named owners, access limits, stop conditions, independent review, exception acceptance, output evidence, and disposition rules on one representative cycle.' },
] as const;

export const september24ResearchPosts = studies.map((study,index)=>({
  slug:study.slug,title:study.title,excerpt:`Research protocol: ${study.question}`,published:DATE,order:1300+index,
  stat:`One ${study.unit} is the predeclared unit; no measured result is asserted.`,image:study.image,
  takeaways:[`Define ${study.subject} states before extracting the population.`,'Publish missing evidence, reviewer disagreements, and unresolved units alongside successful classifications.','Use the finding to bound support work while named owners retain consequential decisions.'],
  sections:sectionsFor(study),sources,faq,
  related:['payroll-event-sequence-integrity-study','payroll-evidence-provenance-break-study','payroll-output-confirmation-gap-study'],
  serviceHandoff:{heading:'Apply the protocol to a bounded support lane',body:`Use the study to test ${study.decision}. Start with one representative cycle, preserve the source trail, and route every authority or interpretation question to the named owner.`,href:study.service,cta:study.cta},
}));
