const DATE = '2026-09-24';

const sources = [
  { name: "IRS Publication 15 (2026), Employer's Tax Guide", url: 'https://www.irs.gov/publications/p15', note: 'Official U.S. employer guidance for payroll withholding, deposits, reporting, and records.' },
  { name: 'U.S. Department of Labor Fact Sheet #21', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping', note: 'Official federal summary of FLSA recordkeeping requirements.' },
  { name: 'NIST Zero Trust Architecture, SP 800-207', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Official guidance on explicit verification and least-privilege access.' },
  { name: 'Philippine National Privacy Commission: Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Official Philippine privacy resource for teams handling personal data.' },
];

const topics = [
  ['payroll-ach-notice-of-change-intake', 'Route an ACH notice of change into payroll safely', 'Preserve the bank notice, distinguish it from a worker instruction, and route account corrections through approved verification and ownership.', 'ACH notice-of-change intake', 'notice reference, receiving bank, original payment trace, reason code, worker reference, received time, protected source, and assigned owner', 'A notice of change is evidence of a payment-network event, not automatic authority to edit bank data. Account ownership, verification, correction timing, and resubmission require authorized payroll, treasury, provider, and security owners.', '/blog-heroes/payroll-sensitive-request-verification.png'],
  ['payroll-returned-direct-deposit-resolution', 'Resolve a returned payroll direct deposit with a controlled record', 'Connect the returned payment to its trace, worker, payroll result, provider status, verified contact path, and owner-approved next action.', 'returned direct-deposit resolution', 'worker reference, payroll period, payment trace, return date, return reason, amount, provider status, contact state, and decision owner', 'Support must not redirect funds, accept replacement bank details in an unverified channel, or promise a payment date. Treasury, payroll, provider, and security owners control verification, recovery, reissue, and communication.', '/blog-heroes/payroll-provider-rejection-response.png'],
  ['payroll-earned-wage-access-reconciliation', 'Reconcile earned-wage access activity before payroll close', 'Bridge provider advances, fees, recoveries, payroll deductions, reversals, and worker-level exceptions without treating an aggregate total as proof.', 'earned-wage access reconciliation', 'worker reference, provider transaction, earning period, advance date, supplied recovery amount, reversal state, payroll period, and owner', 'Eligibility, available-wage calculations, fee treatment, deduction limits, disputes, and payroll configuration belong to qualified payroll, legal, finance, and provider owners.', '/blog-heroes/payroll-cycle-closeout-ledger.png'],
  ['payroll-paycard-enrollment-exception', 'Review payroll paycard enrollment exceptions before payment', 'Separate enrollment, identity verification, consent, account activation, payroll destination, and failed-payment evidence so exceptions reach the right owner.', 'paycard enrollment exception', 'worker reference, enrollment source, consent record, verification state, card or account token, activation state, target payroll, and exception owner', 'Support must not choose a payment method, activate an account for a worker, bypass consent, or expose card data. Authorized payroll, HR, provider, legal, and security owners decide treatment.', '/blog-heroes/payroll-sensitive-request-verification.png'],
  ['payroll-multiple-job-record-reconciliation', 'Reconcile multiple job records before payroll processing', 'Compare worker identity, job records, rates, schedules, earning codes, costing, and effective dates without collapsing distinct assignments.', 'multiple-job-record reconciliation', 'worker reference, job identifiers, entities, positions, effective dates, pay groups, rate sources, time sources, costing fields, and owners', 'Employment status, primary-job rules, overtime treatment, benefit eligibility, taxation, allocation, and record consolidation require qualified HR, payroll, tax, legal, and finance decisions.', '/blog-heroes/payroll-input-control-map.png'],
  ['payroll-legal-entity-transfer-readiness', 'Prepare a payroll legal-entity transfer readiness packet', 'Map the last source-entity cycle and first destination-entity cycle, preserving approvals, identifiers, balances, open payments, and unresolved owner decisions.', 'legal-entity transfer readiness', 'worker reference, source and destination entities, authorized transfer record, effective date, pay groups, open balances, cutoff dates, and decision owners', 'A support specialist must not decide whether a transfer is a termination, new employment, continuity event, tax event, or benefit event. Qualified HR, payroll, tax, legal, benefits, and finance owners decide.', '/blog-heroes/payroll-employee-change-effective-date.png'],
  ['payroll-shadow-payroll-input-coordination', 'Coordinate shadow-payroll inputs without creating a second source of truth', 'Link assignment records, home and host payroll outputs, compensation inputs, currency dates, tax-owner instructions, and reconciliation states.', 'shadow-payroll input coordination', 'worker reference, assignment reference, home and host entities, covered period, input type, currency, source system, owner instruction, and cutoff', 'Tax equalization, hypothetical tax, sourcing, exchange-rate policy, withholding, social insurance, and reporting require authorized global mobility, tax, legal, finance, and payroll owners.', '/blog-heroes/payroll-record-source-register.png'],
  ['payroll-foreign-currency-input-bridge', 'Build a source-to-output bridge for foreign-currency payroll inputs', 'Keep the source amount, currency, conversion authority, rate date, target currency, rounding, approval, and payroll result visible as separate fields.', 'foreign-currency input bridge', 'worker reference, earning or deduction type, source amount and currency, covered period, approved conversion source, rate date, target amount, and owner', 'Support must not select an exchange-rate policy, change a rate date, decide tax treatment, or force a conversion to match an expected total. Finance, tax, payroll, legal, and provider owners decide.', '/blog-heroes/payroll-timesheet-source-check.png'],
  ['payroll-court-order-release-intake', 'Control the intake of a court-order release for payroll deductions', 'Preserve the release document, match it to the active order and worker, expose timing conflicts, and route stopping decisions to qualified owners.', 'court-order release intake', 'release reference, issuing authority, received time, worker reference, related order, effective language, next payroll cutoff, protected source, and owner', 'Validity, precedence, stop date, refund, remittance, notice, and legal interpretation require qualified payroll or legal owners. Intake staff should never infer that a deduction ends from an informal message.', '/blog-heroes/payroll-sensitive-request-verification.png'],
  ['payroll-cost-allocation-input-review', 'Review payroll cost-allocation inputs before close', 'Tie allocation percentages and dimensions to an approved source, effective period, complete population, payroll totals, and reconciled accounting output.', 'payroll cost-allocation input review', 'worker or population reference, earning period, allocation dimensions, supplied percentages, source version, effective period, approval, and accounting owner', 'Accounting treatment, allocation policy, project eligibility, capitalization, intercompany treatment, and corrections remain with authorized finance, payroll, tax, and legal owners.', '/blog-heroes/payroll-cycle-closeout-review.png'],
  ['payroll-workers-comp-code-change', 'Route a workers-compensation code change through payroll review', 'Connect the authorized role or location change to classification evidence, effective timing, payroll configuration, premiums, and owner verification.', 'workers-compensation code change', 'worker reference, current and requested code, role and location sources, effective date, payroll period, request source, impacted systems, and owners', 'Classification, coverage, premium treatment, retroactivity, reporting, and legal compliance require qualified risk, HR, payroll, broker, finance, and legal owners.', '/blog-heroes/employee-change-date-ledger.png'],
  ['payroll-paper-check-custody-register', 'Use a custody register for paper payroll checks', 'Track check stock, printed items, controlled handoffs, delivery evidence, voids, returns, and unresolved exceptions without exposing negotiable details.', 'paper-check custody register', 'payroll period, check batch reference, masked check reference, print count, custodian, handoff time, delivery state, void state, and exception owner', 'Support must not sign, endorse, redirect, release, destroy, or reissue checks without explicit authority. Payroll, treasury, finance, security, and legal owners define custody and disposition.', '/blog-heroes/payroll-approval-evidence-packet.png'],
] as const;

export const september24BlogPosts = topics.map(([slug, title, excerpt], batchIndex) => ({ slug, title, excerpt, minutes: 12, published: DATE, batchIndex }));

export const september24BlogDetails = Object.fromEntries(topics.map(([slug, title, excerpt, subject, intake, boundary, image], index) => [slug, {
  takeaways: [`Define the ${subject} population, period, sources, and cutoff before work begins.`, boundary, 'Verify the authorized outcome in a fresh payroll, provider, bank, or accounting record before closure.'],
  readinessRows: [
    { area: 'Scope', ready: `The ${subject} population, period, cutoff, source, and expected result are named.`, ownerCheck: 'Confirm inclusions, exclusions, and decision rights.' },
    { area: 'Evidence', ready: 'Original records remain linked in approved systems, with versions and observation times.', ownerCheck: 'Resolve missing, stale, or conflicting authority.' },
    { area: 'Access', ready: 'The preparer has named, task-limited access to the minimum population.', ownerCheck: 'Approve access, monitoring, and removal date.' },
    { area: 'Decision', ready: 'Every consequential question has a qualified owner and response deadline.', ownerCheck: 'Record approval, rejection, correction, or escalation.' },
  ],
  sections: [
    { heading: `Open the ${subject} with a bounded question`, paragraphs: [
      `${excerpt} The first question is not whether support can make the underlying decision. It is whether a support specialist can assemble complete, current evidence so the authorized owner can decide before an irreversible payroll step. Define the entity, pay group, worker or population, covered period, cutoff, and expected output. Name a preparer, reviewer, decision owner, backup, and system owner. Put stop conditions beside the assignment so a strange record does not drift into an unauthorized change.`,
      `Capture ${intake}. Preserve identifiers only in protected systems and use a masked case reference in general coordination tools. Record dates with time zones and identify whether each value is supplied, observed, calculated, approved, or verified. A copied value without a source, a screenshot without a timestamp, and an approval without a stated scope are gaps; label them rather than filling them from memory.`,
    ] },
    { heading: 'Separate evidence, preparation, and owner decisions', paragraphs: [
      `Build the case around what each authoritative source actually shows. Keep the original event, requester statement, system observation, comparison result, proposed input, and owner decision as distinct evidence. That separation matters when two systems disagree, an item arrives after cutoff, or a plausible request comes through the wrong channel. Preparation can collect records, normalize formats, compare fields, request missing context, and maintain status. It cannot turn ambiguity into a payroll instruction.`,
      `${boundary} Place each unresolved question with the person who has both authority and context. Payroll, HR, finance, treasury, tax, legal, benefits, security, privacy, risk, accounting, and a provider may own different parts of the same case. A shared record should coordinate those decisions without implying that one approval settles every downstream issue.`,
    ] },
    { heading: 'Create a source-to-result evidence bridge', paragraphs: [
      `Show how the initiating record reaches the proposed payroll action and the eventual result. Record the source version, covered period, effective date, mapping or transformation used, preparer, reviewer, approval time, submitted version, and final output. If a value changes during review, preserve the rejected or superseded version and its reason. Never edit history merely to make the case look linear after a correction.`,
      `Use statuses that name the next action: missing authoritative source, conflicting source, identity verification required, invalid format, unclear effective period, approval required, access blocked, provider rejected, output unverified, or downstream dependency open. Avoid vague labels such as handled and done. A reviewer should be able to see what remains open, who owns it, what evidence would resolve it, and when the next check will occur.`,
    ] },
    { heading: 'Plan the review around payroll cutoff', paragraphs: [
      `Work backward from the last reversible checkpoint, not just the nominal pay date. Allow time for collection, completeness review, identity or authority verification, owner decisions, correction, resubmission, and output inspection. Record every deadline with its time zone and source. A Philippines-based payroll support specialist may prepare the queue across a different workday from the client owner, so define the overlap window, backup contact, and escalation channel in advance.`,
      `Sort cases by consequence, proximity to cutoff, and reversibility. Items involving payment destination, identity, tax, court orders, entity movement, broad population changes, negotiable instruments, or a rapidly approaching release need prompt owner attention. Routine missing fields can remain in a normal follow-up lane with a dated reminder. Priority controls review order; it never grants the preparer additional authority.`,
    ] },
    { heading: 'Protect payroll data while coordinating the work', paragraphs: [
      `Keep payroll, tax, identity, banking, court, benefit, mobility, and employment details in approved systems. The coordination view usually needs only a case reference, masked person or population reference, period, status, owner, due time, and protected link. Do not paste full records into chat, attach sensitive exports to ordinary email, or create a private spreadsheet because the approved system takes longer to open.`,
      `Grant named access for the task and population, then review it after the first cycle. Remove permissions that are not used. Unexpected identity documents, payment instructions, bank changes, executable attachments, or urgent requests from an unverified sender belong in the company's verification or security process. Cutoff pressure does not make an unsafe channel acceptable, and familiarity with a sender is not a substitute for the approved control.`,
    ] },
    { heading: 'Give the owner a decision-ready packet', paragraphs: [
      `Lead with the decision needed, deadline, affected population, last confirmed state, authoritative source links, conflicts, prepared comparison, operational next step, and consequence of no response. State uncertainty plainly. The owner should be able to approve, reject, request a correction, or escalate with a dated reason without reconstructing the case from private messages. Include only the personal detail required for that owner's task.`,
      `When several owners participate, split the questions and acceptance criteria. Payroll may confirm an input while finance confirms accounting, treasury confirms a payment state, HR confirms an employment source, security confirms a verified channel, and qualified tax or legal owners interpret obligations. Record each decision beside its scope and effective period. Do not reuse a narrow approval as blanket authority for a later period or different system.`,
    ] },
    { heading: 'Verify the result after the approved action', paragraphs: [
      `Do not close the case when an email is sent, a file is uploaded, a ticket changes state, or a provider acknowledges receipt. Compare a fresh payroll, provider, banking, or accounting output with the approved instruction. Check the target person or population, period, amount or state, effective timing, and relevant control total. If a change touched a mapping or population rule, inspect nearby ordinary records for unintended effects.`,
      `When the result differs, reopen the exception with new evidence rather than revising the earlier record to look correct. Keep employee communication, accounting reconciliation, returned funds, provider acknowledgement, access removal, later-cycle monitoring, and policy review as separate dependencies with owners and dates. Completion means the intended result is observable and every residual action has an accountable owner.`,
    ] },
    { heading: 'Pilot one complete cycle before expanding the handoff', paragraphs: [
      `Test the ${subject} routine on one complete cycle using properly protected records. Count items received, items missing authoritative sources, owner questions returned before cutoff, rejected submissions, corrected items, and results verified against fresh output. These are workflow counts, not proof of payroll accuracy, legal compliance, or a business result. Keep the first population small enough for a reviewer to inspect every handoff.`,
      `At closeout, ask which fields supported a decision, which merely copied another source, where authority was unclear, and which access was unnecessary. Update instructions only with specific approved examples and preserve the reason for each change. Expand after the client owner can inspect the evidence without reconstructing events from memory. For Outsource Payroll Company, a practical first handoff is queue preparation and evidence follow-up while the client payroll owner keeps final approval and release authority.`,
      `If this issue repeatedly slows a payroll cycle, bring one redacted example, the cutoff, the relevant source systems, and the approving roles to the operations support team. That is enough to design a checked first cycle without moving the whole payroll process at once.`,
    ] },
  ],
  roleBrief: [`Routine: ${title}`, 'Output: dated evidence bridge, owner-ready review, and verified result', 'Access: named, least-privilege account for the declared population', 'Approval: authorized client payroll or functional owner', 'Stop rule: pause when source, scope, identity, channel, or authority is unclear'],
  faqs: [
    { question: `Can a Philippines-based payroll assistant own the ${subject}?`, answer: 'The assistant can prepare evidence, follow up on missing records, and maintain the queue. Authorized client owners decide consequential payroll, tax, banking, legal, employment, accounting, benefit, and release actions.' },
    { question: 'What should the working record contain?', answer: `Record ${intake}, plus the owner, next action, deadline, protected source link, approval scope, submitted version, and verified final state.` },
    { question: 'When is the item complete?', answer: 'Only after the authorized action appears in a fresh system output and every remaining dependency has a named owner and date.' },
  ],
  sources,
  rich: {
    keyword: subject,
    marker: `opc-20260924-${slug}`,
    published: DATE,
    image,
    directAnswer: [excerpt, 'The support specialist organizes evidence and exceptions; authorized client owners decide and verify the consequential action.'],
    stats: [],
    quote: { text: 'There is no implicit trust granted to assets or user accounts based solely on their physical or network location.', attribution: 'NIST SP 800-207, Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
    chart: { title: `A controlled ${subject} lane`, description: 'Source, preparation, owner decision, and output verification.', methods: 'Process illustration, not measured performance.' },
    graphic: { title: `${title} workflow`, description: 'A checked path from evidence to a verified result.', steps: ['Source', 'Prepare', 'Decide', 'Verify'] },
    banners: [{ eyebrow: 'Plan one payroll lane', heading: 'Start with a checked first cycle', text: 'Define source, access, stop rules, owner review, and verification before handoff.', href: '/contact', label: 'Plan payroll support' }],
    internalLinks: [{ href: '/services/operations-support', label: 'Payroll operations support' }, { href: '/services/reporting-and-qa', label: 'Payroll reporting and QA support' }, { href: '/contact', label: 'Plan a first payroll support cycle' }],
  },
  publication: { internalLinks: ['/services/operations-support', '/services/reporting-and-qa', '/contact'], externalLink: sources[index % sources.length].url, related: topics.filter((_, i) => i !== index).slice(0, 2).map(([relatedSlug]) => `/blog/${relatedSlug}`) },
}]));
