import { sectionsFor, type ResearchStudyFrame } from './september22-research';

const DATE = '2026-09-25';
const sources = [
  { label: "Internal Revenue Service: Publication 15 (2026), Employer's Tax Guide (checked September 25, 2026)", url: 'https://www.irs.gov/publications/p15' },
  { label: 'U.S. Department of Labor: Fact Sheet #21, Recordkeeping Requirements under the FLSA (checked September 25, 2026)', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { label: 'NIST: SP 800-53 Rev. 5, Security and Privacy Controls (checked September 25, 2026)', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
  { label: 'Philippine National Privacy Commission: Data Privacy Act of 2012 (checked September 25, 2026)', url: 'https://privacy.gov.ph/data-privacy-act/' },
] as const;

const studies: readonly ResearchStudyFrame[] = [
  { slug:'payroll-new-hire-input-readiness-study', title:'Payroll new-hire input readiness study', question:'Before a new hire enters payroll preparation, can the reviewer verify that every required input has a defined source, effective period, authority owner, completeness state, and safe exception route?', subject:'new-hire input readiness', unit:'one new-hire record expected to enter a defined payroll population for the first time', states:'ready by cutoff, ready after correction, held for missing source, held for conflicting effective date, authority unresolved, sensitive field exposed outside the approved path, or unresolved', service:'/services/new-hire-payroll-setup', cta:'Review new-hire payroll setup support', decision:'whether a new-hire setup lane can prepare complete, source-linked records without deciding employment status, entitlement, tax treatment, bank validity, or the correct first payment', evidence:'case identifier, employing entity, approved start event, source owner, required-field checklist, effective dates, receipt times, authority references, validation results, exceptions, reviewer decision, and first-output confirmation', image:'/research-heroes/philippines-payroll-source-output-bridge-study.png' },
  { slug:'payroll-leave-balance-interface-study', title:'Payroll leave-balance interface study', question:'When approved leave information crosses into payroll, can each balance-affecting event be traced through period, unit, source version, transformation, exception decision, and observable output?', subject:'leave-balance interfaces', unit:'one approved leave event expected to affect a payroll input, balance, or defined downstream output', states:'matched end to end, approved transformation documented, period mismatch, unit mismatch, duplicate event, source conflict, downstream confirmation missing, or unresolved', service:'/services/leave-balance-administration', cta:'Review leave balance administration support', decision:'whether a leave-administration support lane can reconcile records and prepare exceptions while owners retain decisions about entitlement, pay treatment, balances, and correction', evidence:'event identifier, leave type, source period, units and unit definition, approval reference, source version, transformation rule, payroll period, expected output field, observed output, variance, and disposition owner', image:'/research-heroes/philippines-payroll-correction-lineage-review.png' },
  { slug:'payroll-bank-change-channel-integrity-study', title:'Payroll bank-change channel integrity study', question:'Can a payroll workflow prove that a bank-detail change stayed within the approved intake, identity-check, access, approval, and downstream-confirmation channels without copying sensitive values into the study record?', subject:'bank-change channel integrity', unit:'one request to change the destination information used for a payroll payment', states:'approved channel complete, request redirected from an unapproved channel, identity check incomplete, authority missing, sensitive value overexposed, downstream result unconfirmed, or unresolved', service:'/services/payroll-data-entry', cta:'Review payroll data-entry support', decision:'whether a data-entry lane can log and route a sensitive change without authenticating a person, selecting a bank destination, approving payment, or treating message familiarity as authority', evidence:'protected case identifier, intake channel, receipt time, channel policy version, identity-check outcome reference, authorized decision reference, permitted editor, change event, independent review, output confirmation, access review, and exception owner', image:'/research-heroes/philippines-payroll-approval-authority-boundary-research.png' },
  { slug:'payroll-provider-file-receipt-study', title:'Payroll provider file receipt study', question:'After a payroll file is transmitted, can the team distinguish technical delivery, provider receipt, validation acceptance, processing status, and final output instead of treating one acknowledgement as completion?', subject:'provider-file receipt evidence', unit:'one versioned payroll file transmitted to a provider for a defined entity, population, and period', states:'delivery and receipt verified, provider validation accepted, rejected with traceable reason, later version superseded the file, acknowledgement ambiguous, processing or output unconfirmed, or unresolved', service:'/services/payroll-preparation', cta:'Review payroll preparation support', decision:'whether a preparation lane preserves enough evidence for an owner to know what the provider received without claiming that receipt proves calculation, payment, filing, or legal correctness', evidence:'file identifier and content hash, entity, period, population count, version, sender, approved transmission route, transmission time, delivery receipt, provider acknowledgement, validation response, supersession link, exception owner, and final-output reference', image:'/research-heroes/philippines-payroll-provider-rejection-cohort-study.png' },
  { slug:'payroll-termination-input-boundary-study', title:'Payroll termination input boundary study', question:'For a worker leaving a payroll population, can the preparation record separate the approved status event, effective date, ordinary payroll inputs, owner-decided final-pay items, access changes, and later corrections?', subject:'termination input boundaries', unit:'one approved leaver event expected to change membership or inputs for a defined payroll period', states:'boundary complete, status or date conflict, ordinary input incomplete, owner decision pending, population removal unconfirmed, access follow-up missing, later correction linked, or unresolved', service:'/services/payroll-preparation', cta:'Review payroll preparation support', decision:'whether an outsourced lane can assemble the leaver packet and population evidence without calculating an entitlement, interpreting an agreement, choosing legal treatment, or approving final pay', evidence:'case identifier, employing entity, approved status source, relevant dates and their meanings, affected periods, ordinary input checklist, reserved owner decisions, population comparison, access follow-up reference, approval, output confirmation, and correction links', image:'/research-heroes/philippines-payroll-transition-exit-evidence-research.png' },
] as const;

const faq = [
  { question:'Does this protocol determine whether a payroll outcome is legally correct?', answer:'No. It tests evidence and workflow states. Authorized company owners and qualified advisers decide pay, tax, employment, privacy, banking, benefit, and records treatment.' },
  { question:'What can a Philippines-based payroll support specialist do?', answer:'Within approved access, a specialist can freeze the population, preserve source links, apply written classifications, prepare exceptions, and verify a defined output. Consequential decisions stay with the designated owner.' },
  { question:'What should a buyer test before expanding the lane?', answer:'Test source definitions, version rules, named owners, access limits, stop conditions, independent review, exception acceptance, output evidence, and disposition rules on one representative cycle.' },
] as const;

export const september25ResearchPosts = studies.map((study,index)=>({
  slug:study.slug,title:study.title,excerpt:`Research protocol: ${study.question}`,published:DATE,order:1400+index,
  stat:`One ${study.unit} is the predeclared unit; no measured result is asserted.`,image:study.image,
  takeaways:[`Define ${study.subject} states before extracting the population.`,'Publish missing evidence, reviewer disagreements, and unresolved units alongside successful classifications.','Use the finding to bound support work while named owners retain consequential decisions.'],
  sections:sectionsFor(study),sources,faq,
  related:['payroll-master-data-field-ownership-study','payroll-event-sequence-integrity-study','payroll-output-confirmation-gap-study'],
  serviceHandoff:{heading:'Apply the protocol to a bounded support lane',body:`Use the study to test ${study.decision}. Start with one representative cycle, preserve the source trail, and route every authority or interpretation question to the named owner.`,href:study.service,cta:study.cta},
}));
