const DATE = '2026-09-14';

const blogSources = [
  { name: "IRS Publication 15 (2026), Employer's Tax Guide", url: 'https://www.irs.gov/publications/p15', note: 'Official U.S. guidance on payroll periods, withholding, deposits, reporting, and corrections.' },
  { name: 'U.S. Department of Labor Fact Sheet #21', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping', note: 'Official federal summary of FLSA recordkeeping requirements.' },
  { name: 'NIST Zero Trust Architecture, SP 800-207', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Official guidance on explicit verification and least-privilege access.' },
  { name: 'Philippine National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Official Philippine privacy-law resource; qualified advisers should assess specific obligations.' },
];

const blogSeeds = [
  ['payroll-calendar-cutoff-change-control', 'Control changes to the payroll cutoff calendar', 'Keep deadline changes, affected teams, owner approval, and provider acknowledgement in one dated record.', 'cutoff calendar change', '/blog-heroes/payroll-cycle-closeout-ledger.png', 'Record the worker, entity, original pay period, discovery date, source record, and exact field under review. Keep the historical source intact.', 'Separate the factual error from the proposed remedy. Pay, tax, benefits, accounting, and provider filings may have different owners and deadlines.', 'Give each owner the before value, proposed value, evidence, affected outputs, and open questions.', 'Match the approved instruction to corrected payroll and every required downstream record.'],
  ['payroll-new-entity-readiness-register', 'Build a payroll readiness register for a new entity', 'Coordinate population, registrations, banking, systems, owners, and first-cycle evidence without hiding unresolved launch risks.', 'new-entity readiness', '/blog-heroes/payroll-approval-evidence-packet.png', 'Assign a case ID and capture the worker, entity, reason, amount source, requested date, owner, and masked payment reference.', 'Treat preparation, signature, delivery, and accounting entry as separate events. Possession of check stock is not release authority.', 'Before release, compare the payee, amount, period, deductions, and approval with the prepared artifact.', 'Reconcile the instrument number to payroll, bank evidence, and the accounting handoff. Retain void or stop-payment evidence.'],
  ['payroll-approval-evidence-expiry-review', 'Review expiry dates in payroll approval evidence', 'Prevent stale delegations and time-limited instructions from silently carrying into a later pay cycle.', 'approval-evidence expiry', '/blog-heroes/aug21-payroll-exception-aging-review.png', 'Record the expected requirement, observed available amount, observation time, source, payment deadline, and authorized actors. Label estimates.', 'Keep payroll calculation status apart from cash status. A balanced register does not prove available funds.', 'Escalate with the gap, evidence freshness, affected populations, and next irreversible step. Do not invent prioritization rules.', 'Capture the authorized funding action, provider receipt, settlement evidence, and payments still pending.'],
  ['payroll-provider-sla-exception-log', 'Maintain a payroll provider SLA exception log', 'Measure missed acknowledgements and delivery windows with comparable timestamps, evidence, and owner-approved dispositions.', 'provider SLA exception', '/blog-heroes/payroll-timesheet-source-check.png', 'Name the plan, coverage period, payroll period, population source, instruction version, extraction time, and benefit owner.', 'Compare stable identifiers and classify missing, unexpected, duplicated, changed, and timing-related rows separately.', 'Send disputed eligibility, arrears, refunds, and imputed-income questions to the qualified owner.', 'Verify approved changes in payroll and the carrier or accounting output. Record legitimate future-cycle differences.'],
  ['payroll-retroactive-rate-change-bridge', 'Bridge a retroactive rate change into payroll', 'Connect approved effective dates to recalculation inputs, affected periods, owner decisions, and verified output.', 'retroactive-rate change', '/blog-heroes/payroll-employee-change-effective-date.png', 'Collect the authorized request, old and new locations, effective date, expected work pattern, entity, and first affected period.', 'A location update can raise payroll, tax, registration, employment, and benefit questions. Support routes them rather than inferring treatment.', 'Show the source facts, missing facts, date conflicts, stale systems, and upcoming cutoffs.', 'Check the approved location and codes in the next output. Keep jurisdictional review open with an owner and date.'],
  ['payroll-termination-date-conflict-triage', 'Triage conflicting payroll termination dates', 'Compare authorized status sources and effective dates before a payroll owner decides the affected cycle.', 'termination-date conflict', '/blog-heroes/payroll-handoff-qa-scorecard.png', 'Freeze source files and note location, business dates, worker IDs, reporting channel, adjustments, timestamp, and payroll period.', 'Test population coverage before totals. Classify duplicates, missing workers, out-of-period activity, and rejected imports.', 'Route allocation, withholding, credit-rule, and dispute questions to qualified owners. The reconciliation should not declare legal treatment.', 'Compare the approved import to payroll and preserve rejected-row evidence. Follow unresolved records after close.'],
  ['payroll-deduction-refund-case-register', 'Track payroll deduction refund cases', 'Keep the disputed deduction, authority, calculation proposal, approval, payment path, and employee communication aligned.', 'deduction-refund case', '/blog-heroes/employee-payroll-question-intake.png', 'Restrict the case. Record the notice source, time, worker ID, entity, payroll state, owner, and deadlines without unnecessary personal details.', 'Separate payroll, benefits, legal review, access, records, and communication workstreams. A checklist does not determine a recipient.', 'Give each qualified owner only the evidence needed. Require written authority before changing payment or recipient data.', 'Verify every authorized action, retain minimum evidence, and remove temporary collaborators after their work ends.'],
  ['payroll-parallel-run-coverage-matrix', 'Use a coverage matrix for a payroll parallel run', 'Prove which populations, earning types, deductions, and edge cases were compared before go-live.', 'parallel-run coverage', '/blog-heroes/payroll-record-source-register.png', 'Preserve the instruction and record the bargaining unit, worker population, effective period, formula source, version, requester, and approvals.', 'Compare the instruction population with payroll. Flag joiners, leavers, leave cases, retroactive instructions, and system conflicts.', 'Ask labor-relations, payroll, or legal owners to resolve interpretation questions. Support identifies differences.', 'Match approved deductions to payroll and remittance. Record rejected or returned amounts separately.'],
  ['payroll-cycle-version-release-note', 'Write a release note for each payroll cycle version', 'Make late inputs and recalculations traceable from a frozen candidate through the owner-approved final output.', 'cycle-version release', '/blog-heroes/payroll-sensitive-request-verification.png', 'Use a protected bank-instruction reference plus worker ID, channel, verification state, effective cycle, prenote status, and owner.', 'Distinguish pending validation, rejected routing, closed account, identity mismatch, expired request, and provider delay.', 'Escalate conflicts, rushed requests, changed destinations, and failed verification. Familiar email is not bank-change authority.', 'Confirm the authorized destination in provider output and settlement when observable. Remove temporary protected copies.'],
  ['payroll-support-access-breakglass-review', 'Review break-glass access used in payroll support', 'Constrain emergency access with explicit authority, time limits, activity evidence, and prompt revocation.', 'break-glass access', '/blog-heroes/aug21-repair-payroll-absence-continuity-runbook.png', 'Record the return notice, expected and actual dates, payroll period, status source, time source, dependencies, and owner. Exclude medical detail.', 'Lay out the timeline by effective date. Identify conflicts among HR status, schedule, time, approved instructions, and payroll.', 'Route entitlement, accommodation, benefit, and retroactive questions to qualified owners.', 'Verify approved status and pay treatment. Keep future benefit or catch-up actions as dated dependencies.'],
  ['payroll-unresolved-item-rollforward', 'Roll unresolved payroll items into the next cycle safely', 'Carry a payroll exception forward with its evidence, impact, owner, due date, and explicit interim decision.', 'unresolved-item rollforward', '/blog-heroes/payroll-cycle-closeout-review.png', 'Capture the approved provider, currency pair, rate type, timestamp and zone, covered elements, rounding source, period, and version.', 'Keep contractual, calculation, payment, and accounting currencies distinct. One authorized rate may not cover another conversion.', 'Present the rate, proposed use, exceptions, and sensitivity to payroll or finance owners. Support reproduces arithmetic.', 'Recalculate a sample from approved source through payroll and accounting. Preserve rate and rule versions.'],
  ['payroll-file-retention-disposition-check', 'Check disposition of temporary payroll files', 'Remove or retain working exports only through an approved, evidenced rule after the payroll purpose is complete.', 'temporary-file disposition', '/blog-heroes/payroll-cycle-closeout-ledger.png', 'Define the authority for each field, snapshot time, population, and age rule. Account for different refresh schedules.', 'Classify source lag, payroll lag, missing, unexpected, effective-date mismatch, and unresolved authority at field level.', 'Show owners conflicting values, source times, first affected period, and systems requiring action.', 'Confirm changes in a fresh extract and give legitimate exceptions expiry dates. Repeated gaps require source review.'],
] as const;

export const september14BlogPosts = blogSeeds.map(([slug, title, excerpt], index) => ({ slug, title, excerpt, minutes: 10, published: DATE, batchIndex: index }));

export const september14BlogDetails = Object.fromEntries(blogSeeds.map(([slug, title, excerpt, subject, image, intake, working, review, close], index) => [slug, {
  takeaways: [`Define the ${subject} scope and source before changing a record.`, 'Keep preparation, approval, and output verification separate.', 'Preserve conflicts and unresolved dependencies.'],
  readinessRows: [{ area: 'Scope', ready: `The ${subject} population, source, period, and cutoff are named.`, ownerCheck: 'Confirm inclusions and decision rights.' }, { area: 'Evidence', ready: 'Original and current records have timestamps and versions.', ownerCheck: 'Resolve conflicting authority.' }, { area: 'Close', ready: 'The approved action can be compared with its output.', ownerCheck: 'Confirm disposition and dependencies.' }],
  sections: [{ heading: `Open a bounded ${subject} record`, paragraphs: [intake] }, { heading: 'Separate the facts from the decision', paragraphs: [working] }, { heading: 'Prepare the owner review', paragraphs: [review] }, { heading: 'Verify the result and keep loose ends visible', paragraphs: [close] }, { heading: 'Use a short retrospective', paragraphs: [`Ask where the ${subject} first became observable and whether instructions were clear. Change the routine only when case evidence points to a specific gap. Keep payroll, tax, legal, benefit, banking, and employment decisions with company-designated owners.`] }],
  roleBrief: ['Role: bounded payroll preparation and evidence support', `Workflow: ${title}`, 'Access: named account with least privilege', 'Stop rule: escalate consequential decisions', 'Close: compare the approved instruction with output'],
  faqs: [{ question: `Can outsourced support approve a ${subject} decision?`, answer: 'No. Support can organize sources, compare records, track status, and prepare a decision packet. A company-designated owner approves consequential action.' }, { question: 'What should stay out of the coordination log?', answer: 'Do not copy credentials, full bank details, identity documents, health details, or other sensitive values when a protected reference is enough.' }, { question: 'When can the record close?', answer: 'Close after the approved action appears in the intended output and every later dependency has an owner and date.' }],
  sources: blogSources,
  rich: { keyword: title.toLowerCase(), marker: `opc-20260914-blog-${index + 1}`, published: DATE, image, directAnswer: [excerpt, `Run the ${subject} as a controlled evidence path with named authority.`], stats: [], quote: { text: 'A payroll status is useful only when its source, authority, and expected output are visible.', attribution: 'Outsource Payroll Company operating principle', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' }, chart: { title, description: 'Source, compare, decide, verify, and close.', methods: 'Illustrative operating model. It does not report measured performance.' }, graphic: { title: 'Controlled payroll path', description: 'A five-stage evidence workflow.', steps: ['Source', 'Compare', 'Decide', 'Verify', 'Close'] }, banners: [], internalLinks: [{ href: '/services/payroll-preparation', label: 'Payroll preparation support' }, { href: '/services/payroll-reporting', label: 'Payroll reporting support' }, { href: '/blog', label: 'Payroll operations guides' }] },
}]));

const researchSources = [
  { label: "IRS Publication 15 (2026), Employer's Tax Guide", url: 'https://www.irs.gov/publications/p15' },
  { label: 'U.S. Department of Labor Fact Sheet #21, FLSA Recordkeeping', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping' },
  { label: 'NIST SP 800-53 Revision 5, Security and Privacy Controls', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
  { label: 'Philippine National Privacy Commission, Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/' },
];

const researchSeeds = [
  ['payroll-cutoff-change-propagation-study', 'Payroll cutoff change propagation study', 'How consistently does an approved cutoff change reach every dependent owner and system before the affected cycle?', 'cutoff-change propagation', 'one approved cutoff change for one recipient or system', 'received, acknowledged, configured, verified, missed, superseded, or indeterminate', '/research-heroes/payroll-cutoff-evidence-window-study.png'],
  ['payroll-new-entity-launch-evidence-study', 'Payroll new-entity launch evidence study', 'Which readiness conditions are present when a first payroll cycle reaches verified closure without emergency rework?', 'new-entity launch readiness', 'one declared readiness condition for one entity launch', 'verified ready, conditionally ready, blocked, waived by owner, failed after launch, or indeterminate', '/research-heroes/philippines-payroll-source-output-bridge-study.png'],
  ['payroll-approval-expiry-exposure-study', 'Payroll approval expiry exposure study', 'Where do expired or time-limited approvals remain active across later payroll cycles?', 'approval-expiry exposure', 'one approval artifact applied to one payroll cycle', 'current, expired before use, renewed, superseded, used without current evidence, or indeterminate', '/research-heroes/philippines-payroll-approval-latency-cascade-study.png'],
  ['payroll-provider-sla-attribution-study', 'Payroll provider SLA attribution study', 'How often can a missed service window be attributed after input readiness and timestamp comparability are tested?', 'provider-SLA attribution', 'one contracted provider event in one payroll cycle', 'on time, provider delay, client-input delay, planned exception, disputed scope, incomparable, or indeterminate', '/research-heroes/payroll-provider-rejection-traceability-study.png'],
  ['payroll-retroactive-change-closure-study', 'Payroll retroactive change closure study', 'Which evidence links are associated with a retroactive change reaching all declared downstream outputs?', 'retroactive-change closure', 'one approved retroactive field change for one affected period', 'calculated, approved, payroll matched, downstream matched, dependency open, reversed, or indeterminate', '/research-heroes/philippines-payroll-retroactive-change-propagation-study.png'],
] as const;

const faq = [{ question: 'Does this research determine correct payroll or legal treatment?', answer: 'No. It studies workflow evidence and timing. Authorized owners and qualified advisers decide treatment.' }, { question: 'Can findings be generalized to every employer?', answer: 'No. Systems, providers, policies, event mix, access, and record quality differ. Repeat the protocol locally.' }, { question: 'What can outsourced support do?', answer: 'Support can prepare de-identified extracts, maintain evidence links, apply written classifications, and surface disagreements.' }];

export const september14ResearchPosts = researchSeeds.map(([slug, title, question, subject, unit, states, image], index) => ({
  slug, title, excerpt: `Research question: ${question}`, published: DATE, order: 900 + index, stat: `One ${unit} is the predeclared unit of analysis.`, image,
  takeaways: [`Define ${subject} states before selecting cases.`, 'Report counts, time, missing evidence, and unresolved records separately.', 'Treat association as an operating signal, not proof of cause or correct treatment.'],
  sections: [
    { heading: 'Scope and research question', body: `The study asks: ${question} Its scope is a bounded payroll operations lane and its unit is ${unit}. An eligible record identifies an entity, payroll period, source time, owner, and observable output. The study does not calculate entitlement, interpret law, inspect private provider internals, or score workers.` },
    { heading: 'Methodology and sampling plan', body: 'Define the observation window and freeze the eligible population before viewing outcomes. Include at least three comparable payroll cycles or publish the full dated case series for rare events. Record inclusion rules, exclusions, missing records, system changes, holidays, and extraction times. Preserve source versions and use de-identified fields where possible.' },
    { heading: 'Measures and classification rules', body: `Classify each unit as ${states}. Write definitions before review. Measure only between comparable timestamps and retain time zones. Report the denominator, state counts, missing fields, median and range when supported, and unresolved cases. Have a second reviewer repeat a declared sample and publish disagreements.` },
    { heading: 'Inference boundaries and competing explanations', body: 'The analysis can describe timing, co-occurrence, evidence breaks, and differences between declared groups. It cannot establish causation. Alternatives include late sources, unavailable owners, access failure, provider processing, calendar effects, changed case mix, and incomplete logging. A matching total does not prove each intermediate control worked.' },
    { heading: 'Limitations', body: 'The design may miss rare events, overwritten history, restricted decisions, seasonal workload, or events outside the window. Small or convenience samples do not support population rates. Public sources supply payroll, recordkeeping, security, and privacy context, but do not prove a private workflow or set a universal benchmark.' },
    { heading: 'Evidence-led conclusion', body: `For ${subject}, conclusions are limited to the declared population, definitions, and observable records. Publish uncertainty beside results. Support may maintain the register and rerun comparisons, while company-designated owners approve payroll action and decide whether evidence supports a control change.` },
    { heading: 'References', body: 'The numbered primary-source list below defines the external context for this protocol. It does not replace local policy, contracts, system documentation, or qualified payroll, tax, legal, privacy, benefit, banking, and employment advice.' },
  ], sources: researchSources, faq, related: ['philippines-payroll-reconciliation-evidence', 'philippines-payroll-source-validation', 'philippines-payroll-control-testing'], serviceHandoff: { heading: 'Apply the protocol to a payroll support lane', body: 'A scoped support team can maintain the case register and prepare comparisons while the payroll owner defines decisions and approves corrections.', href: '/services/payroll-reporting', cta: 'Review payroll reporting support' },
}));
