const DATE = '2026-09-25';

const sources = [
  { name: "IRS Publication 15 (2026), Employer's Tax Guide", url: 'https://www.irs.gov/publications/p15', note: 'Official U.S. employer guidance for payroll withholding, deposits, reporting, and records.' },
  { name: 'U.S. Department of Labor Fact Sheet #21', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping', note: 'Official federal summary of FLSA recordkeeping requirements.' },
  { name: 'NIST Zero Trust Architecture, SP 800-207', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Official guidance on explicit verification and least-privilege access.' },
  { name: 'Philippine National Privacy Commission: Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Official Philippine privacy resource for teams handling personal data.' },
];

const topics = [
  ['payroll-holiday-premium-input-review', 'Review holiday-premium inputs before payroll cutoff', 'Connect approved holiday calendars, eligibility records, time entries, premium codes, and owner decisions before an input reaches payroll.', 'holiday-premium input review', 'worker reference, work date, holiday calendar, time source, supplied premium code or multiplier, eligibility source, target payroll, and owner', 'Holiday eligibility, premium rates, collective-agreement terms, overtime interaction, and pay corrections require qualified HR, payroll, legal, or labor-relations owners.', '/blog-heroes/payroll-timesheet-source-check.png'],
  ['payroll-salary-proration-change-packet', 'Prepare a salary-proration change packet for payroll review', 'Show the approved salary event, effective date, pay-period boundaries, supplied calculation basis, and payroll result without hiding partial-period assumptions.', 'salary-proration change packet', 'worker reference, approved salary record, prior and new amounts, effective date, pay frequency, covered days, supplied proration method, target period, and owner', 'Proration method, salary basis, effective timing, contract interpretation, tax treatment, and final pay amount belong to authorized HR, payroll, finance, legal, or provider owners.', '/blog-heroes/payroll-employee-change-effective-date.png'],
  ['payroll-expense-reimbursement-separation', 'Separate expense reimbursements from payroll earnings inputs', 'Preserve the approved expense source, reimbursement category, payroll treatment instruction, and accounting result as distinct evidence.', 'expense-reimbursement separation', 'worker reference, expense report, approval, expense date, supplied category, reimbursement amount, payment route, payroll period, and accounting owner', 'Business-purpose eligibility, accountable-plan treatment, taxability, coding, payment method, and correction decisions require qualified finance, tax, legal, and payroll owners.', '/blog-heroes/payroll-input-control-map.png'],
  ['payroll-gross-up-request-intake', 'Control gross-up requests entering payroll', 'Give the payroll owner the approved benefit or payment, stated objective, supplied calculation instruction, tax review, deadline, and verification path.', 'gross-up request intake', 'worker reference, payment type, approved gross or target-net instruction, covered period, tax-owner guidance, calculation version, payroll code, and decision owner', 'Whether a payment should be grossed up, which taxes apply, the calculation method, limits, reporting, and final release require qualified tax, payroll, finance, and legal owners.', '/blog-heroes/payroll-approval-evidence-packet.png'],
  ['payroll-pay-frequency-transition-map', 'Map a pay-frequency transition without losing payroll inputs', 'Bridge the final old-frequency cycle and first new-frequency cycle across dates, recurring inputs, deductions, benefits, balances, and open exceptions.', 'pay-frequency transition map', 'entity and pay group, old and new frequencies, final and first period dates, pay dates, recurring inputs, deduction schedule, balances, cutoff, and owners', 'Frequency changes, wage-payment timing, deduction cadence, benefit treatment, notices, system configuration, and compliance require authorized HR, payroll, benefits, legal, finance, and provider owners.', '/blog-heroes/payroll-cycle-closeout-review.png'],
  ['payroll-deferred-compensation-input-bridge', 'Build a deferred-compensation input bridge for payroll', 'Link authorized elections and plan instructions to covered compensation, payroll codes, limits, exceptions, and verified output.', 'deferred-compensation input bridge', 'worker reference, plan and election source, covered period, compensation source, supplied contribution or deferral input, payroll code, limit-review state, and owner', 'Eligibility, election validity, plan interpretation, contribution limits, taxation, corrections, and remittance decisions belong to qualified benefits, tax, legal, payroll, and plan owners.', '/blog-heroes/payroll-record-source-register.png'],
  ['payroll-garnishment-remittance-reconciliation', 'Reconcile payroll garnishment remittances after deduction', 'Connect each authorized deduction to the payroll result, protected order reference, remittance batch, recipient acknowledgement, and unresolved exception.', 'garnishment-remittance reconciliation', 'masked worker and order references, payroll period, deducted amount, remittance batch, payment reference, recipient state, rejected or returned state, and owner', 'Order validity, priority, withholding limits, recipient details, remittance timing, refunds, and legal responses require qualified payroll, legal, treasury, or provider owners.', '/blog-heroes/payroll-cycle-closeout-ledger.png'],
  ['payroll-tax-registration-readiness-handoff', 'Prepare a payroll tax-registration readiness handoff', 'Organize entity, work-location, hiring, payroll-timing, agency, account, and provider dependencies without treating preparation as tax advice.', 'tax-registration readiness handoff', 'entity reference, work locations, first-work and first-pay dates, worker population, agency references, account status, provider dependency, deadlines, and decision owners', 'Registration obligations, nexus, effective dates, withholding setup, filing liability, agency responses, and legal or tax interpretations require qualified tax, legal, finance, and payroll owners.', '/blog-heroes/payroll-record-source-register.png'],
  ['payroll-void-after-release-control', 'Control a payroll void request after release', 'Preserve the released payment, request source, payment status, recoverability evidence, owner decision, replacement dependency, and final verification.', 'post-release payroll void request', 'worker reference, payroll period, payment reference, release time, current payment state, void reason, request source, replacement dependency, and decision owner', 'Whether a payment can be stopped or voided, how funds are recovered, whether a replacement is due, and how records or taxes change require authorized payroll, treasury, finance, legal, tax, and provider owners.', '/blog-heroes/payroll-provider-rejection-response.png'],
  ['payroll-new-jurisdiction-worker-intake', 'Route a new-jurisdiction worker record into payroll review', 'Expose the authorized work location, effective date, employing entity, payroll timing, registrations, provider setup, and unresolved owner decisions.', 'new-jurisdiction worker intake', 'worker reference, employing entity, authorized work location, effective date, work pattern, first payroll, registration state, provider state, and owners', 'Employment authorization, nexus, registrations, withholding, unemployment, leave, insurance, benefits, notices, and payroll eligibility require qualified HR, tax, legal, benefits, risk, and payroll owners.', '/blog-heroes/employee-change-date-ledger.png'],
  ['payroll-wage-repayment-intake', 'Prepare a wage-repayment request for owner review', 'Separate the original payment, identified issue, worker communication, proposed recovery, consent or authority, payroll effect, and accounting result.', 'wage-repayment request intake', 'worker reference, original payroll and payment, issue source, confirmed amount, communication state, supplied recovery instruction, target period, and owners', 'Whether money is owed, permissible recovery method and timing, consent, deduction limits, tax corrections, accounting, and employee communication require qualified payroll, HR, legal, tax, and finance owners.', '/blog-heroes/payroll-exception-root-cause-review.png'],
  ['payroll-special-bonus-payout-readiness', 'Check special-bonus payout readiness before payroll release', 'Tie the approved award population and amounts to eligibility, payroll codes, funding, tax-owner instructions, exceptions, and verified results.', 'special-bonus payout readiness', 'award plan or approval, worker population, supplied amounts and currency, earning period, target payroll, payroll codes, exception state, funding state, and owners', 'Eligibility, award amount, discretion, plan interpretation, withholding, clawbacks, funding, communication, and final release require authorized compensation, HR, payroll, tax, finance, and legal owners.', '/blog-heroes/payroll-approval-evidence-packet.png'],
] as const;

export const september25BlogPosts = topics.map(([slug, title, excerpt], batchIndex) => ({ slug, title, excerpt, minutes: 12, published: DATE, batchIndex }));

export const september25BlogDetails = Object.fromEntries(topics.map(([slug, title, excerpt, subject, intake, boundary, image], index) => [slug, {
  takeaways: [`Define the ${subject} population, period, sources, and cutoff before work begins.`, boundary, 'Verify the authorized outcome in a fresh payroll, provider, bank, or accounting record before closure.'],
  readinessRows: [
    { area: 'Scope', ready: `The ${subject} population, period, cutoff, source, and expected result are named.`, ownerCheck: 'Confirm inclusions, exclusions, and decision rights.' },
    { area: 'Evidence', ready: 'Original records remain linked in approved systems, with versions and observation times.', ownerCheck: 'Resolve missing, stale, or conflicting authority.' },
    { area: 'Access', ready: 'The preparer has named, task-limited access to the minimum population.', ownerCheck: 'Approve access, monitoring, and removal date.' },
    { area: 'Decision', ready: 'Every consequential question has a qualified owner and response deadline.', ownerCheck: 'Record approval, rejection, correction, or escalation.' },
  ],
  sections: [
    { heading: `Open the ${subject} with a bounded question`, paragraphs: [
      `${excerpt} The first question is not whether support can make the underlying decision. It is whether a support specialist can assemble complete, current evidence so the authorized owner can decide before an irreversible payroll step. Define the entity, pay group, worker or population, covered period, cutoff, and expected output. Name a preparer, reviewer, decision owner, backup, and system owner. Put stop conditions beside the assignment so a strange record does not drift into an unauthorized change.`,
      `Capture ${intake}. Preserve identifiers only in protected systems and use a masked case reference in general coordination tools. Record dates with time zones and identify whether each value is supplied, observed, calculated, approved, or verified. A copied value without a source, a screenshot without a timestamp, and an approval without a stated scope are gaps; label them rather than filling them from memory.`,
    ] },
    { heading: 'Separate evidence, preparation, and owner decisions', paragraphs: [
      `Build the case around what each authoritative source actually shows. Keep the original event, requester statement, system observation, comparison result, proposed input, and owner decision as distinct evidence. That separation matters when two systems disagree, an item arrives after cutoff, or a plausible request comes through the wrong channel. Preparation can collect records, normalize formats, compare fields, request missing context, and maintain status. It cannot turn ambiguity into a payroll instruction.`,
      `${boundary} Place each unresolved question with the person who has both authority and context. Payroll, HR, finance, treasury, tax, legal, benefits, security, privacy, risk, accounting, and a provider may own different parts of the same case. A shared record should coordinate those decisions without implying that one approval settles every downstream issue.`,
    ] },
    { heading: 'Create a source-to-result evidence bridge', paragraphs: [
      `Show how the initiating record reaches the proposed payroll action and the eventual result. Record the source version, covered period, effective date, mapping or transformation used, preparer, reviewer, approval time, submitted version, and final output. If a value changes during review, preserve the rejected or superseded version and its reason. Never edit history merely to make the case look linear after a correction.`,
      `Use statuses that name the next action: missing authoritative source, conflicting source, identity verification required, invalid format, unclear effective period, approval required, access blocked, provider rejected, output unverified, or downstream dependency open. Avoid vague labels such as handled and done. A reviewer should be able to see what remains open, who owns it, what evidence would resolve it, and when the next check will occur.`,
    ] },
    { heading: 'Plan the review around payroll cutoff', paragraphs: [
      `Work backward from the last reversible checkpoint rather than relying on the nominal pay date. Allow time for collection, completeness review, identity or authority verification, owner decisions, correction, resubmission, and output inspection. Record every deadline with its time zone and source. A Philippines-based payroll support specialist may prepare the queue across a different workday from the client owner, so define the overlap window, backup contact, and escalation channel in advance.`,
      `Sort cases by consequence, proximity to cutoff, and reversibility. Items involving payment destination, identity, tax, court orders, entity movement, broad population changes, negotiable instruments, or a rapidly approaching release need prompt owner attention. Routine missing fields can remain in a normal follow-up lane with a dated reminder. Priority controls review order; it never grants the preparer additional authority.`,
    ] },
    { heading: 'Protect payroll data while coordinating the work', paragraphs: [
      `Keep payroll, tax, identity, banking, court, benefit, mobility, and employment details in approved systems. The coordination view usually needs only a case reference, masked person or population reference, period, status, owner, due time, and protected link. Do not paste full records into chat, attach sensitive exports to ordinary email, or create a private spreadsheet because the approved system takes longer to open.`,
      `Grant named access for the task and population, then review it after the first cycle. Remove permissions that are not used. Unexpected identity documents, payment instructions, bank changes, executable attachments, or urgent requests from an unverified sender belong in the company's verification or security process. Cutoff pressure does not make an unsafe channel acceptable, and familiarity with a sender is not a substitute for the approved control.`,
    ] },
    { heading: 'Give the owner a decision-ready packet', paragraphs: [
      `Lead with the decision needed, deadline, affected population, last confirmed state, authoritative source links, conflicts, prepared comparison, operational next step, and consequence of no response. State uncertainty plainly. The owner should be able to approve, reject, request a correction, or escalate with a dated reason without reconstructing the case from private messages. Include only the personal detail required for that owner's task.`,
      `When several owners participate, split the questions and acceptance criteria. Payroll may confirm an input while finance confirms accounting, treasury confirms a payment state, HR confirms an employment source, security confirms a verified channel, and qualified tax or legal owners interpret obligations. Record each decision beside its scope and effective period. Do not reuse a narrow approval as blanket authority for a later period or different system.`,
    ] },
    { heading: 'Verify the result after the approved action', paragraphs: [
      `Do not close the case when an email is sent, a file is uploaded, a ticket changes state, or a provider acknowledges receipt. Compare a fresh payroll, provider, banking, or accounting output with the approved instruction. Check the target person or population, period, amount or state, effective timing, and relevant control total. If a change touched a mapping or population rule, inspect nearby ordinary records for unintended effects.`,
      `When the result differs, reopen the exception with new evidence rather than revising the earlier record to look correct. Keep employee communication, accounting reconciliation, returned funds, provider acknowledgement, access removal, later-cycle monitoring, and policy review as separate dependencies with owners and dates. Completion means the intended result is observable and every residual action has an accountable owner.`,
    ] },
    { heading: 'Pilot one complete cycle before expanding the handoff', paragraphs: [
      `Test the ${subject} routine on one complete cycle using properly protected records. Count items received, items missing authoritative sources, owner questions returned before cutoff, rejected submissions, corrected items, and results verified against fresh output. These are workflow counts, not proof of payroll accuracy, legal compliance, or a business result. Keep the first population small enough for a reviewer to inspect every handoff.`,
      `At closeout, ask which fields supported a decision, which merely copied another source, where authority was unclear, and which access was unnecessary. Update instructions only with specific approved examples and preserve the reason for each change. Expand after the client owner can inspect the evidence without reconstructing events from memory. For Outsource Payroll Company, a practical first handoff is queue preparation and evidence follow-up while the client payroll owner keeps final approval and release authority.`,
      `If this issue repeatedly slows a payroll cycle, bring one redacted example, the cutoff, the relevant source systems, and the approving roles to the operations support team. That is enough to design a checked first cycle without moving the whole payroll process at once.`,
    ] },
  ],
  roleBrief: [`Routine: ${title}`, 'Output: dated evidence bridge, owner-ready review, and verified result', 'Access: named, least-privilege account for the declared population', 'Approval: authorized client payroll or functional owner', 'Stop rule: pause when source, scope, identity, channel, or authority is unclear'],
  faqs: [
    { question: `Can a Philippines-based payroll assistant own the ${subject}?`, answer: 'The assistant can prepare evidence, follow up on missing records, and maintain the queue. Authorized client owners decide consequential payroll, tax, banking, legal, employment, accounting, benefit, and release actions.' },
    { question: 'What should the working record contain?', answer: `Record ${intake}, plus the owner, next action, deadline, protected source link, approval scope, submitted version, and verified final state.` },
    { question: 'When is the item complete?', answer: 'Only after the authorized action appears in a fresh system output and every remaining dependency has a named owner and date.' },
  ],
  sources,
  rich: {
    keyword: subject,
    marker: `opc-20260925-${slug}`,
    published: DATE,
    image,
    directAnswer: [excerpt, 'The support specialist organizes evidence and exceptions; authorized client owners decide and verify the consequential action.'],
    stats: [],
    quote: { text: 'There is no implicit trust granted to assets or user accounts based solely on their physical or network location.', attribution: 'NIST SP 800-207, Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
    chart: { title: `A controlled ${subject} lane`, description: 'Source, preparation, owner decision, and output verification.', methods: 'Process illustration, not measured performance.' },
    graphic: { title: `${title} workflow`, description: 'A checked path from evidence to a verified result.', steps: ['Source', 'Prepare', 'Decide', 'Verify'] },
    banners: [{ eyebrow: 'Plan one payroll lane', heading: 'Start with a checked first cycle', text: 'Define source, access, stop rules, owner review, and verification before handoff.', href: '/contact', label: 'Plan payroll support' }],
    internalLinks: [{ href: '/services/operations-support', label: 'Payroll operations support' }, { href: '/services/reporting-and-qa', label: 'Payroll reporting and QA support' }, { href: '/contact', label: 'Plan a first payroll support cycle' }],
  },
  publication: { internalLinks: ['/services/operations-support', '/services/reporting-and-qa', '/contact'], externalLink: sources[index % sources.length].url, related: topics.filter((_, i) => i !== index).slice(0, 2).map(([relatedSlug]) => `/blog/${relatedSlug}`) },
}]));
