const DATE = '2026-09-18';

const sources = [
  { name: "IRS Publication 15 (2026), Employer's Tax Guide", url: 'https://www.irs.gov/publications/p15', note: 'Official U.S. guidance on payroll periods, deposits, reporting, and corrections.' },
  { name: 'U.S. Department of Labor Fact Sheet #21', url: 'https://www.dol.gov/agencies/whd/fact-sheets/21-flsa-recordkeeping', note: 'Official federal summary of FLSA recordkeeping requirements.' },
  { name: 'NIST Zero Trust Architecture, SP 800-207', url: 'https://csrc.nist.gov/pubs/sp/800/207/final', note: 'Official guidance on explicit verification and least-privilege access.' },
  { name: 'Philippine National Privacy Commission: Data Privacy Act', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Official Philippine privacy-law resource; qualified advisers should assess specific obligations.' },
];

const seeds = [
  ['payroll-duplicate-payment-prevention-review', 'Review duplicate-payment signals before payroll release', 'Compare worker, period, earning, amount, and payment references without assuming that every repeated value is a duplicate.', 'duplicate-payment review', '/blog-heroes/payroll-approval-evidence-packet.png', 'Open a restricted review item for each signal. Record the worker reference, entity, pay group, covered period, earning or payment type, amount, source reports, and detection time. Preserve both candidate records instead of deleting one before the payroll owner has reviewed their lineage.', 'A repeated amount can be legitimate when two workers share a rate, one worker has two authorized payments, or a correction intentionally repeats a prior line. Compare stable identifiers, effective dates, source approvals, provider references, and payment states. Classify the signal as confirmed duplicate, expected repeat, unresolved, or outside scope.', 'Give the authorized payroll owner a side-by-side comparison with the suspected duplicate fields, source links, downstream state, cutoff, and exact decision needed. Route tax, banking, accounting, legal, and employee-relations questions to their designated owners rather than blending them into one support recommendation.', 'After an approved action, compare the final payroll output and payment evidence with the decision. Confirm that the intended record was held, corrected, or retained and that no legitimate payment disappeared. Keep recovery, employee communication, or accounting work open as dated dependencies.'],
  ['payroll-voided-payment-control-log', 'Build a control log for voided payroll payments', 'Trace a void request from verified source through authorization, provider action, replacement decision, and reconciliation.', 'voided-payment control', '/blog-heroes/payroll-cycle-closeout-ledger.png', 'Register the original payment reference, worker reference, pay period, amount, payment status, request source, reason stated, and observation time. Use masked values in coordination notes and link to the protected source. Do not treat a request to void as proof that the original payment has stopped.', 'Separate payroll calculation, payment release, settlement, void, stop-payment, replacement, and accounting states. Each event needs its own evidence and owner. A void can fail or arrive after settlement, while a replacement can create duplicate-payment risk if the original state is uncertain.', 'Prepare a decision packet that identifies the last confirmed payment state, available provider or bank evidence, deadlines, worker impact, and actions requiring authorization. Support staff may coordinate evidence but should not decide whether to stop, recover, reissue, or change payment details.', 'Verify the provider or bank outcome against the authorized instruction, then reconcile payroll and accounting records. If a replacement is approved, link it to the original item and test for double settlement. Close only when residual employee communication and later-cycle adjustments have owners and dates.'],
  ['payroll-provider-transition-access-inventory', 'Inventory payroll access during a provider transition', 'Map accounts, roles, exports, interfaces, approvals, and removal dates before old and new provider access overlaps.', 'provider-transition access', '/blog-heroes/payroll-sensitive-request-verification.png', 'List every named user, service account, integration, shared location, approval role, and support channel connected to the outgoing and incoming providers. Record the business purpose, system owner, permitted population, activation date, expected removal date, and evidence source.', 'Distinguish access needed for historical retrieval, parallel testing, live preparation, approval, release, and post-cutover support. A transition may justify temporary overlap, but it does not justify copying broad permissions from the old provider. Flag shared accounts and undocumented interfaces for owner review.', 'Ask system, payroll, security, privacy, and provider owners to confirm each role and its time window. Show unresolved dependencies such as historical reports, tax documents, open cases, or payment traces. Do not disable an account until its owner confirms the required evidence path and retention duties.', 'After cutover, verify active accounts and integrations from fresh system evidence, revoke expired temporary permissions, and confirm that necessary historical records remain reachable through approved paths. Record exceptions with an owner and expiry date rather than leaving transition access indefinitely open.'],
  ['payroll-holiday-calendar-exception-plan', 'Plan payroll calendar exceptions around holidays', 'Translate bank, provider, company, and team closures into dated preparation, review, submission, and release checkpoints.', 'holiday-calendar exception', '/blog-heroes/payroll-timesheet-source-check.png', 'Create a dated row for each affected payroll event: employee or manager input, support preparation, owner review, provider submission, funding, and expected payment. Preserve the original time zone and source for every deadline, including provider notices and bank calendars.', 'Do not assume that every deadline moves by the same number of days. A bank closure, provider window, company holiday, and regional team holiday can affect different steps. Work backward from the externally confirmed event and leave explicit time for exception correction and owner review.', 'Send the proposed calendar to named payroll, finance, provider, and operational owners. Highlight changed dates, unavailable reviewers, backup coverage, unresolved notices, and the last reversible checkpoint. Support can maintain reminders, but only an authorized owner may approve a changed payroll calendar.', 'During the cycle, record actual receipt and review times rather than marking reminders as completion evidence. After release, compare planned and actual checkpoints, explain misses, and update only the specific calendar rule supported by evidence. Keep future holiday assumptions subject to fresh confirmation.'],
  ['payroll-earning-code-retirement-checklist', 'Retire a payroll earning code without losing history', 'Control the final permitted use, replacement mapping, open transactions, reporting effect, access change, and post-retirement monitoring.', 'earning-code retirement', '/blog-heroes/payroll-record-source-register.png', 'Define the code, owning entity, populations, current purpose, approved replacement if any, last permitted earning date, last payroll period, and decision owner. Freeze a usage report and configuration snapshot so later reviewers can distinguish historical records from new use.', 'Search recurring inputs, templates, interfaces, imports, timekeeping mappings, adjustment queues, reports, accounting mappings, and provider instructions. Classify each reference as historical only, scheduled future use, replacement required, unresolved, or safe to remove. Do not infer treatment from a similar code name.', 'Prepare a change packet showing affected populations, open items, mapping decisions, testing cases, rollback conditions, and owners for payroll, HR, finance, tax, legal, systems, and provider questions. Support can inventory references and compare outputs but should not select the replacement treatment.', 'After the approved change, confirm that the retired code rejects or avoids new ordinary use while history remains reportable as required. Test the replacement in a bounded sample and inspect payroll and accounting outputs. Keep exceptions visible through the first affected live cycle.'],
  ['payroll-tax-notice-intake-routing', 'Route a payroll tax notice without losing deadlines or evidence', 'Capture receipt, jurisdiction, period, notice type, protected source, response deadline, and qualified owner before operational follow-up begins.', 'tax-notice intake', '/blog-heroes/employee-payroll-question-intake.png', 'Restrict the notice and record the receiving channel, receipt date, stated jurisdiction, tax type, period, entity, notice identifier, response date, payment date if separately stated, and designated owner. Use a protected link instead of copying taxpayer or banking details into general coordination tools.', 'Separate what the notice states from what the company concludes. A balance, discrepancy, filing request, account change, or identity concern may require different payroll, finance, provider, tax, legal, or security owners. Support should not interpret liability or promise a response outcome.', 'Create a decision-ready index of the notice, related filings or deposits, provider case, prior correspondence, deadlines, missing evidence, and questions for the qualified owner. Track acknowledgement and assignment separately; a routed email does not prove that an authorized response has been prepared or submitted.', 'Record the approved action, submission or payment evidence, agency or provider acknowledgement, and any future monitoring date. Do not close solely because a ticket changed status. Confirm that later correspondence and payroll or accounting corrections, when required, have named owners.'],
  ['payroll-provider-user-access-review', 'Review payroll provider portal users and approval roles', 'Reconcile named users, business need, approval authority, authentication, last use, and removal evidence in the provider portal.', 'provider-portal access review', '/blog-heroes/aug21-payroll-exception-aging-review.png', 'Obtain a current provider user and role export through an authorized account. Record extraction time, tenant or entity scope, role names, status, last-use field when reliable, and the system owner. Compare it with current workforce and responsibility records using protected identifiers.', 'Treat active status, business need, and decision authority as different tests. A current employee may no longer need payroll access, while a backup may need preparation access without approval or release rights. Flag shared identities, dormant accounts, excessive roles, and unowned service access.', 'Send each exception to the manager, payroll owner, system owner, security owner, or provider administrator who can confirm it. Require a dated decision and scope. Support may collect responses and update the review register; it should not approve its own access or grant consequential authority.', 'Verify approved removals and changes from a fresh portal export or provider evidence. Confirm that terminated and expired temporary access is gone, named accounts remain usable, and approval chains still have valid coverage. Carry unresolved cases with risk, owner, action, and due date.'],
  ['payroll-support-document-intake-safety', 'Handle payroll support documents through a safer intake lane', 'Reduce uncontrolled copies by defining approved channels, minimum fields, malware checks, identity verification, retention, and escalation.', 'support-document intake', '/blog-heroes/payroll-handoff-qa-scorecard.png', 'Define which payroll documents the support lane may receive, from whom, through which approved channel, and for what purpose. Record a case identifier, sender verification state, received time, protected location, intended owner, and retention rule without reproducing sensitive contents in the tracker.', 'A readable attachment is not automatically trustworthy or authorized. Preserve the original, avoid enabling active content, follow company malware controls, and compare the sender and request with an authoritative record. Unexpected bank, identity, tax, health, or employment documents require restricted escalation.', 'Route the document and a minimum necessary summary to the owner authorized for that category. State the payroll period, deadline, missing context, verification result, and action requested. Do not forward a sensitive attachment broadly to accelerate review or use a personal storage location as a temporary workaround.', 'Confirm that the owner received the protected reference and that any approved payroll action appears in the intended output. Remove temporary working copies through the company retention process, preserve required evidence, and document rejected or suspicious submissions through the appropriate security path.'],
  ['payroll-zero-net-pay-check', 'Check zero-net payroll records before final approval', 'Distinguish expected zero results from missing earnings, excessive deductions, status errors, and unresolved provider calculations.', 'zero-net pay review', '/blog-heroes/payroll-cycle-closeout-review.png', 'Create a restricted exception list for every zero-net result in scope. Capture entity, pay group, period, worker reference, gross amount, deduction total, tax total, status source, provider result, and evidence timestamp. Do not expose personal detail in a broad operational tracker.', 'Separate legitimate zero results from potential missing input or conflicting treatment. Compare population membership, employment status, time or salary source, leave or termination instructions, deductions, prior adjustments, and provider messages. Label uncertainty instead of inserting an amount to clear the alert.', 'Give the payroll owner a concise source-to-result bridge and the exact unresolved question. Split benefit, tax, employment, garnishment, accounting, or provider issues among their qualified owners. Support can prepare the comparison but should not decide whether an earning or deduction is due.', 'After authorized action, rerun the check against the final provider output. Confirm the target record and sample nearby ordinary records to detect unintended changes. Track employee communication or later-cycle adjustments separately and close only when the evidence explains the final zero or corrected result.'],
  ['payroll-pay-group-transfer-reconciliation', 'Reconcile a worker moving between payroll pay groups', 'Bridge effective dates, calendars, balances, deductions, approvals, and population membership across source and destination groups.', 'pay-group transfer', '/blog-heroes/payroll-employee-change-effective-date.png', 'Record the authorized transfer source, worker reference, source and destination groups, effective date, first affected periods, pay calendars, entities, status, and decision owners. Preserve the original request and do not overwrite the source-group history.', 'Map which records should end, continue, or begin: recurring earnings, deductions, time inputs, balances, provider identifiers, approvals, and reporting attributes. Different calendars can create gaps or overlaps. Support can expose those collisions but must not choose the payroll, tax, benefit, or employment treatment.', 'Prepare a timeline showing last source-group inclusion, first destination-group inclusion, cutoff conflicts, missing sources, proposed system changes, and owner questions. Require explicit authorization for sensitive changes and confirm that access to each population follows the worker and task rules.', 'Compare final outputs for both groups. Confirm the worker appears once where intended, does not disappear from required reports, and carries only owner-approved balances or instructions. Keep retroactive, accounting, benefit, or employee communication dependencies open with dates and owners.'],
  ['payroll-general-ledger-mapping-change-review', 'Review a payroll general-ledger mapping change', 'Connect an approved payroll code change to accounting destinations, test cases, effective periods, rollback criteria, and reconciled output.', 'general-ledger mapping change', '/blog-heroes/payroll-cycle-closeout-ledger.png', 'Identify the payroll code, current destination, proposed destination, entities, effective period, request source, accounting owner, payroll owner, system owner, and provider involvement. Preserve the current configuration and a representative pre-change output.', 'Inventory every population and transaction type that can use the mapping, including ordinary earnings, reversals, adjustments, employer costs, and off-cycle items. A code label alone does not establish accounting treatment. Keep unresolved combinations outside the ready change set.', 'Build a test packet with ordinary and edge cases, expected payroll and ledger references, control totals, reviewer responsibilities, change window, and rollback trigger. Support can run comparisons and maintain evidence; authorized payroll, finance, system, and provider owners approve interpretation and production change.', 'After implementation, compare employee-level payroll totals, mapped accounting lines, entity totals, and rejected or suspense items. Confirm the configured effective date and inspect a fresh live-cycle output. Retain the before-and-after evidence and keep unexplained variances open.'],
  ['payroll-worker-identifier-collision-triage', 'Triage a worker identifier collision across payroll systems', 'Protect two records from accidental merging while HR, payroll, provider, and system owners resolve identity and history.', 'worker-identifier collision', '/blog-heroes/payroll-sensitive-request-verification.png', 'Restrict the case and preserve both records. Capture masked identifiers, systems, entities, pay groups, periods, discovery source, current processing state, and named identity owner. Stop automatic merge, deletion, or carry-forward steps when the collision could affect active payroll.', 'Compare authoritative identity references through approved channels without copying full identity documents into the case log. Map which transactions, balances, payment instructions, tax records, time entries, and approvals attach to each record. Similar names or contact details are not sufficient evidence.', 'Prepare a discrepancy table for authorized HR, payroll, provider, security, privacy, or system owners. State which facts agree, which conflict, which deadlines are approaching, and which actions remain reversible. Support should not choose the surviving identity or redistribute payroll history.', 'After the owners resolve the collision, verify each affected population, balance, instruction, and output. Confirm that one person was not paid twice or omitted and that unrelated records did not move. Retain the minimum approved decision evidence and close temporary access or working copies.'],
] as const;

export const september18BlogPosts = seeds.map(([slug, title, excerpt], index) => ({ slug, title, excerpt, minutes: 12, published: DATE, batchIndex: index }));

export const september18BlogDetails = Object.fromEntries(seeds.map(([slug, title, excerpt, subject, image, intake, working, review, close], index) => [slug, {
  takeaways: [`Define the ${subject} scope, source, population, and period.`, 'Keep evidence preparation separate from consequential approval.', 'Verify the approved action in the final output and retain open dependencies.'],
  readinessRows: [
    { area: 'Scope', ready: `The ${subject} population, period, source, and cutoff are named.`, ownerCheck: 'Confirm inclusions and decision rights.' },
    { area: 'Evidence', ready: 'Original records, versions, timestamps, and conflicts are linked.', ownerCheck: 'Resolve missing or conflicting authority.' },
    { area: 'Close', ready: 'The authorized action can be compared with the intended output.', ownerCheck: 'Confirm results and remaining dependencies.' },
  ],
  sections: [
    { heading: `Open a bounded ${subject} record`, paragraphs: [intake] },
    { heading: 'Separate observation from decision', paragraphs: [working] },
    { heading: 'Prepare a decision-ready owner review', paragraphs: [review] },
    { heading: 'Verify the result across outputs', paragraphs: [close] },
    { heading: 'Build a practical operating rhythm', paragraphs: [`Assign one preparer and one accountable owner for the ${subject}. Use a dated queue with clear states such as received, evidence incomplete, owner review, approved action, output verification, and closed. Review approaching cutoffs daily during a live payroll cycle and age unresolved items by the next required action, not by how many messages have been sent.`, `After close, sample ordinary and exceptional records. Ask where the ${subject} first became observable, whether the source was authoritative, whether access stayed within scope, and whether the output proved the approved action. Change a checklist or system rule only when case evidence identifies a repeatable gap; keep one-off judgments attached to their own facts.`] },
    { heading: 'Boundaries for outsourced payroll support', paragraphs: ['A Philippines-based payroll support specialist can maintain the register, request missing records through approved channels, compare versions, prepare a concise owner packet, track deadlines, and verify observable outputs. Final payroll approval, payment release, disputed pay, tax interpretation, legal conclusions, benefit eligibility, employment decisions, bank-detail changes, and production permission changes stay with company-designated owners or qualified advisers.', 'Use named accounts, multifactor authentication, least privilege, and protected source links. Do not put credentials, full bank details, government identifiers, identity documents, health information, or unnecessary employee data in coordination notes. If the evidence or authority is unclear, the safe operational result is a visible exception with an owner—not an invented answer.'] },
  ],
  roleBrief: ['Role: bounded payroll preparation and evidence support', `Workflow: ${title}`, 'Output: dated case record with source links, decisions, and verification', 'Access: named account, multifactor authentication, and least privilege', 'Stop rule: escalate consequential payroll, tax, legal, benefit, employment, banking, and approval decisions', 'Review: a company-designated owner confirms action and closure'],
  faqs: [
    { question: `Can outsourced payroll support approve a ${subject} decision?`, answer: 'No. Support can organize sources, compare records, track status, and prepare a decision packet. A company-designated owner or qualified adviser approves consequential action.' },
    { question: 'What belongs in the working record?', answer: 'Keep the case identifier, source reference, period, population, timestamps, status, owner, next action, deadline, decision, and output evidence. Use protected links instead of copying sensitive values.' },
    { question: 'When can the item close?', answer: 'Close after the authorized action appears in the intended output and every remaining dependency has a named owner and date. A sent message, uploaded file, or ticket status alone is not verification.' },
  ],
  sources,
  rich: {
    keyword: title.toLowerCase(), marker: `opc-20260918-blog-${index + 1}`, published: DATE, image,
    directAnswer: [excerpt, `Run the ${subject} as a controlled evidence path with named authority, minimum necessary access, and output verification.`],
    stats: [], quote: { text: 'A payroll status is useful only when its source, authority, and expected output are visible.', attribution: 'Outsource Payroll Company operating principle', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
    chart: { title, description: 'Source, compare, decide, verify, and close.', methods: 'Illustrative operating model. It does not report measured performance.' },
    graphic: { title: 'Controlled payroll path', description: 'A five-stage evidence workflow.', steps: ['Source', 'Compare', 'Decide', 'Verify', 'Close'] },
    banners: [], internalLinks: [{ href: '/services/payroll-preparation', label: 'Payroll preparation support' }, { href: '/services/payroll-reporting', label: 'Payroll reporting support' }, { href: '/contact', label: 'Discuss a payroll support workflow' }],
  },
}]));
